package main

import (
	"fmt"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

func seedPhongThuyArticles(db *gorm.DB, tagMap map[string]uuid.UUID, authorID *uuid.UUID) int {
	fmt.Println("\n   🏠 Seeding Phong Thủy articles...")

	seeds := []ArticleSeed{
		{
			Title:           "Phong thủy là gì? Kiến thức cơ bản về phong thủy cho người mới",
			Slug:            "phong-thuy-la-gi-kien-thuc-co-ban",
			Excerpt:         "Phong thủy là gì? Nguồn gốc, nguyên lý cơ bản về khí, âm dương, ngũ hành. Hướng dẫn ứng dụng phong thủy trong đời sống.",
			Content:         `<h2>Phong thủy là gì?</h2><p>Phong thủy (風水) nghĩa đen là "gió và nước" – hai yếu tố tự nhiên chi phối dòng chảy năng lượng (khí). Phong thủy là bộ môn nghiên cứu cách sắp xếp không gian sống hài hòa với thiên nhiên để mang lại may mắn, sức khỏe và thịnh vượng.</p><h3>Nguyên lý cơ bản</h3><ul><li><strong>Khí:</strong> Năng lượng vũ trụ lưu thông trong mọi không gian</li><li><strong>Âm Dương:</strong> Sự cân bằng giữa hai thái cực</li><li><strong>Ngũ Hành:</strong> Kim, Mộc, Thủy, Hỏa, Thổ tương sinh tương khắc</li><li><strong>Bát Quái:</strong> 8 hướng tương ứng 8 lĩnh vực cuộc sống</li></ul><h3>Ứng dụng</h3><p>Phong thủy áp dụng trong xây nhà, bài trí nội thất, chọn hướng bàn làm việc, đặt cây xanh, sử dụng màu sắc phù hợp.</p>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Phong thủy là gì? Kiến thức cơ bản",
			MetaDescription: "Phong thủy là gì? Nguồn gốc, nguyên lý khí - âm dương - ngũ hành. Hướng dẫn phong thủy cơ bản.",
			ReadingTime:     7,
			IsFeatured:      true,
			TagNames:        []string{"Phong thủy", "Ngũ hành"},
		},
		{
			Title:       "Phong thủy phòng khách: 15 nguyên tắc vàng cho không gian đón tài lộc",
			Slug:        "phong-thuy-phong-khach-15-nguyen-tac",
			Excerpt:     "Phòng khách là nơi đón khí vào nhà. 15 nguyên tắc phong thủy giúp phòng khách thu hút tài lộc, vượng khí.",
			Content:     `<h2>Phong thủy phòng khách</h2><p>Phòng khách là không gian quan trọng nhất trong nhà, nơi tiếp nhận và phân phối năng lượng. Bài trí phong thủy tốt sẽ mang lại tài lộc và hạnh phúc.</p><h3>15 nguyên tắc</h3><ol><li>Phòng khách nên ở gần cửa chính</li><li>Ghế sofa tựa vào tường vững chắc</li><li>Không đặt ghế quay lưng ra cửa</li><li>Ánh sáng tự nhiên đầy đủ</li><li>Tránh dầm ngang đè lên chỗ ngồi</li><li>Gương không đối diện cửa chính</li><li>Cây xanh tạo sinh khí</li><li>Bể cá phong thủy đặt đúng vị trí</li><li>Màu sắc hài hòa theo mệnh gia chủ</li><li>Tránh góc nhọn hướng vào chỗ ngồi</li><li>Bàn trà hình oval hoặc tròn</li><li>Tranh ảnh tích cực, không treo ảnh u ám</li><li>Giữ phòng khách gọn gàng, thoáng đãng</li><li>Đèn chiếu sáng ấm áp</li><li>Không để giày dép bừa bãi trước cửa</li></ol>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Phong thủy phòng khách - 15 nguyên tắc vàng",
			MetaDescription: "15 nguyên tắc phong thủy phòng khách: đón tài lộc, vượng khí. Bài trí sofa, ánh sáng, cây xanh.",
			ReadingTime:     6,
			IsFeatured:      true,
			TagNames:        []string{"Phong thủy", "Nhà ở"},
		},
		{
			Title:       "Phong thủy phòng ngủ: Bí quyết ngủ ngon và hạnh phúc lứa đôi",
			Slug:        "phong-thuy-phong-ngu-bi-quyet-ngu-ngon",
			Excerpt:     "Phòng ngủ phong thủy tốt giúp ngủ ngon, tăng cường sức khỏe và hạnh phúc hôn nhân. 12 điều cần biết.",
			Content:     `<h2>Phong thủy phòng ngủ</h2><p>Phòng ngủ là nơi con người dành 1/3 cuộc đời. Phong thủy phòng ngủ tốt ảnh hưởng trực tiếp đến sức khỏe, giấc ngủ và mối quan hệ vợ chồng.</p><h3>Nguyên tắc quan trọng</h3><ul><li><strong>Vị trí giường:</strong> Đầu giường tựa vào tường, không đối diện cửa</li><li><strong>Không đặt gương đối diện giường:</strong> Gây mất ngủ, tà khí</li><li><strong>Tránh dầm ngang:</strong> Không nằm dưới dầm, gây áp lực</li><li><strong>Màu sắc:</strong> Tông ấm nhẹ nhàng: hồng nhạt, be, kem</li><li><strong>Ánh sáng:</strong> Dịu nhẹ, có rèm che</li><li><strong>Không đặt bể cá:</strong> Nước trong phòng ngủ gây hao tài</li></ul>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Phong thủy phòng ngủ - Ngủ ngon, hạnh phúc",
			MetaDescription: "Phong thủy phòng ngủ: vị trí giường, gương, màu sắc. Bí quyết ngủ ngon và hạnh phúc lứa đôi.",
			ReadingTime:     5,
			TagNames:        []string{"Phong thủy", "Nhà ở"},
		},
		{
			Title:       "Phong thủy bàn làm việc: Cách sắp xếp bàn làm việc hút tài lộc",
			Slug:        "phong-thuy-ban-lam-viec-hut-tai-loc",
			Excerpt:     "Sắp xếp bàn làm việc theo phong thủy giúp tăng năng suất, thu hút tài lộc và thăng tiến. 10 mẹo cần biết.",
			Content:     `<h2>Phong thủy bàn làm việc</h2><p>Bàn làm việc là nơi bạn dành nhiều thời gian nhất trong ngày. Phong thủy bàn làm việc ảnh hưởng trực tiếp đến năng suất, sáng tạo và cơ hội thăng tiến.</p><h3>10 mẹo phong thủy</h3><ol><li>Ngồi quay lưng vào tường, không ngồi lưng ra cửa</li><li>Nhìn ra cửa hoặc không gian mở</li><li>Đặt cây xanh nhỏ bên trái (vị trí Thanh Long)</li><li>Bên phải để gọn gàng (vị trí Bạch Hổ)</li><li>Đèn bàn đặt bên trái</li><li>Không để đồ vật nhọn hướng vào mình</li><li>Giữ bàn gọn gàng, sạch sẽ</li><li>Đặt vật phẩm phong thủy phù hợp mệnh</li><li>Không ngồi dưới dầm hoặc thiết bị treo</li><li>Màu bàn và ghế phù hợp ngũ hành gia chủ</li></ol>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Phong thủy bàn làm việc - 10 mẹo hút tài lộc",
			MetaDescription: "Phong thủy bàn làm việc: 10 mẹo sắp xếp hút tài lộc, thăng tiến. Hướng ngồi, cây xanh, vật phẩm.",
			ReadingTime:     5,
			TagNames:        []string{"Phong thủy", "Sự nghiệp"},
		},
		{
			Title:       "Cây phong thủy trong nhà: Top 20 loại cây mang tài lộc, may mắn",
			Slug:        "cay-phong-thuy-trong-nha-top-20",
			Excerpt:     "Top 20 cây phong thủy trồng trong nhà giúp hút tài lộc, thanh lọc không khí. Cách chọn cây phù hợp với mệnh.",
			Content:     `<h2>Top 20 cây phong thủy trong nhà</h2><p>Cây xanh không chỉ làm đẹp không gian mà còn là vật phẩm phong thủy mạnh mẽ, giúp cải thiện năng lượng và thu hút tài lộc.</p><h3>Cây hút tài lộc</h3><ul><li><strong>Kim Ngân:</strong> "Cây tiền" – tượng trưng cho sự giàu có</li><li><strong>Phát Tài:</strong> Lá xòe như bàn tay hứng lộc</li><li><strong>Trầu Bà:</strong> Thanh lọc khí, mang lại bình an</li><li><strong>Lan Ý:</strong> Hóa giải sát khí, thu hút may mắn</li><li><strong>Cau Tiểu Trâm:</strong> Thanh lọc không khí cực tốt</li></ul><h3>Chọn cây theo mệnh</h3><ul><li><strong>Mệnh Kim:</strong> Cây lá vàng, trắng – Cúc, Lan</li><li><strong>Mệnh Mộc:</strong> Cây lá xanh – Trúc, Phú Quý</li><li><strong>Mệnh Thủy:</strong> Cây thủy sinh – Sen, Thủy Trúc</li><li><strong>Mệnh Hỏa:</strong> Cây hoa đỏ – Đỗ Quyên, Hồng</li><li><strong>Mệnh Thổ:</strong> Cây mọng nước – Sen Đá, Xương Rồng</li></ul>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Top 20 cây phong thủy trong nhà",
			MetaDescription: "20 cây phong thủy hút tài lộc: Kim Ngân, Phát Tài, Lan Ý. Chọn cây theo mệnh ngũ hành.",
			ReadingTime:     6,
			TagNames:        []string{"Phong thủy", "Nhà ở"},
		},
		{
			Title:       "Ngũ hành tương sinh tương khắc: Bảng tra cứu và ứng dụng",
			Slug:        "ngu-hanh-tuong-sinh-tuong-khac-bang-tra-cuu",
			Excerpt:     "Ngũ hành Kim Mộc Thủy Hỏa Thổ: bảng tương sinh tương khắc chi tiết. Cách ứng dụng trong phong thủy, chọn màu, hướng nhà.",
			Content:     `<h2>Ngũ hành tương sinh tương khắc</h2><p>Ngũ hành là nền tảng của phong thủy và triết học phương Đông. Hiểu rõ ngũ hành giúp ứng dụng phong thủy hiệu quả.</p><h3>Tương sinh</h3><p>Kim sinh Thủy → Thủy sinh Mộc → Mộc sinh Hỏa → Hỏa sinh Thổ → Thổ sinh Kim</p><h3>Tương khắc</h3><p>Kim khắc Mộc → Mộc khắc Thổ → Thổ khắc Thủy → Thủy khắc Hỏa → Hỏa khắc Kim</p><h3>Bảng màu sắc</h3><ul><li><strong>Kim:</strong> Trắng, xám, bạc, vàng kim</li><li><strong>Mộc:</strong> Xanh lá, xanh ngọc</li><li><strong>Thủy:</strong> Đen, xanh dương, tím</li><li><strong>Hỏa:</strong> Đỏ, cam, hồng</li><li><strong>Thổ:</strong> Vàng, nâu, be</li></ul><h3>Bảng hướng</h3><ul><li><strong>Kim:</strong> Tây, Tây Bắc</li><li><strong>Mộc:</strong> Đông, Đông Nam</li><li><strong>Thủy:</strong> Bắc</li><li><strong>Hỏa:</strong> Nam</li><li><strong>Thổ:</strong> Đông Bắc, Tây Nam, Trung tâm</li></ul>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Ngũ hành tương sinh tương khắc - Bảng tra cứu",
			MetaDescription: "Ngũ hành Kim Mộc Thủy Hỏa Thổ: bảng tương sinh tương khắc, màu sắc, hướng. Ứng dụng phong thủy.",
			ReadingTime:     6,
			IsFeatured:      true,
			TagNames:        []string{"Phong thủy", "Ngũ hành"},
		},
		{
			Title:       "Phong thủy nhà bếp: Vị trí, hướng bếp và những điều cấm kỵ",
			Slug:        "phong-thuy-nha-bep-vi-tri-huong-bep",
			Excerpt:     "Bếp là trái tim của ngôi nhà. Phong thủy nhà bếp ảnh hưởng đến sức khỏe, tài lộc và hạnh phúc gia đình.",
			Content:     `<h2>Phong thủy nhà bếp</h2><p>Trong phong thủy, bếp tượng trưng cho Hỏa – nguồn năng lượng nuôi dưỡng gia đình. Vị trí và cách bài trí bếp ảnh hưởng lớn đến sức khỏe và tài lộc.</p><h3>Nguyên tắc</h3><ul><li>Bếp không đối diện cửa chính</li><li>Bếp không đặt dưới nhà vệ sinh tầng trên</li><li>Bếp và bồn rửa không đặt cạnh nhau (Hỏa – Thủy xung khắc)</li><li>Hướng bếp phù hợp mệnh gia chủ</li><li>Bếp sáng sủa, sạch sẽ, thông thoáng</li></ul><h3>Điều cấm kỵ</h3><ul><li>Không đặt bếp giữa hai cửa</li><li>Không để gương phản chiếu bếp</li><li>Không đặt bếp ngay cạnh bồn nước</li></ul>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Phong thủy nhà bếp - Hướng bếp và cấm kỵ",
			MetaDescription: "Phong thủy nhà bếp: vị trí, hướng bếp, điều cấm kỵ. Bếp tốt cho sức khỏe và tài lộc.",
			ReadingTime:     5,
			TagNames:        []string{"Phong thủy", "Nhà ở"},
		},
		{
			Title:       "Phong thủy cửa chính: Hướng cửa, kích thước và cách hóa giải",
			Slug:        "phong-thuy-cua-chinh-huong-kich-thuoc",
			Excerpt:     "Cửa chính là 'miệng' của ngôi nhà, nơi đón khí vào. Chọn hướng cửa, kích thước hợp phong thủy và cách hóa giải.",
			Content:     `<h2>Phong thủy cửa chính</h2><p>Cửa chính (cửa miệng) là vị trí quan trọng nhất trong phong thủy, quyết định lượng khí lành hay khí xấu vào nhà.</p><h3>Hướng cửa tốt</h3><p>Chọn hướng cửa dựa trên bát trạch của gia chủ (Đông tứ mệnh hoặc Tây tứ mệnh).</p><h3>Kích thước</h3><p>Cửa chính nên lớn hơn các cửa phụ. Chiều cao tối thiểu 2.1m. Sử dụng thước Lỗ Ban để đo kích thước hợp phong thủy.</p><h3>Điều cần tránh</h3><ul><li>Cửa chính đối diện cửa sau (khí xuyên thẳng)</li><li>Cửa đối diện cầu thang (khí thoát nhanh)</li><li>Cửa đối diện nhà vệ sinh</li></ul>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Phong thủy cửa chính - Hướng và kích thước",
			MetaDescription: "Phong thủy cửa chính: hướng cửa, kích thước Lỗ Ban, cách hóa giải. Đón khí lành vào nhà.",
			ReadingTime:     5,
			TagNames:        []string{"Phong thủy", "Nhà ở"},
		},
		{
			Title:       "Bát trạch phong thủy: Cách xác định mệnh quái và hướng tốt xấu",
			Slug:        "bat-trach-phong-thuy-menh-quai-huong",
			Excerpt:     "Bát trạch là phương pháp phong thủy dùng năm sinh để tính mệnh quái. Xác định 4 hướng tốt và 4 hướng xấu cho bạn.",
			Content:     `<h2>Bát trạch phong thủy</h2><p>Bát trạch chia người thành hai nhóm: Đông tứ mệnh (Khảm, Ly, Chấn, Tốn) và Tây tứ mệnh (Càn, Khôn, Cấn, Đoài).</p><h3>Cách tính mệnh quái</h3><p><strong>Nam:</strong> (100 - 2 chữ số cuối năm sinh) / 9 → Số dư<br><strong>Nữ:</strong> (2 chữ số cuối năm sinh - 4) / 9 → Số dư</p><h3>4 hướng tốt</h3><ul><li><strong>Sinh Khí:</strong> Hướng tốt nhất, mang lại sinh lực</li><li><strong>Thiên Y:</strong> Sức khỏe, quý nhân phù trợ</li><li><strong>Diên Niên:</strong> Hôn nhân, mối quan hệ</li><li><strong>Phục Vị:</strong> Ổn định, bình an</li></ul><h3>4 hướng xấu</h3><ul><li>Tuyệt Mệnh, Ngũ Quỷ, Lục Sát, Họa Hại</li></ul>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Bát trạch phong thủy - Mệnh quái và hướng",
			MetaDescription: "Bát trạch: tính mệnh quái từ năm sinh, xác định 4 hướng tốt 4 hướng xấu. Phong thủy nhà ở.",
			ReadingTime:     6,
			TagNames:        []string{"Phong thủy", "Ngũ hành"},
		},
		{
			Title:       "Thước Lỗ Ban: Cách đo kích thước phong thủy chuẩn nhất",
			Slug:        "thuoc-lo-ban-do-kich-thuoc-phong-thuy",
			Excerpt:     "Thước Lỗ Ban là công cụ đo phong thủy quan trọng. Cách đọc 8 cung, kích thước tốt xấu cho cửa, bàn thờ, giường.",
			Content:     `<h2>Thước Lỗ Ban</h2><p>Thước Lỗ Ban (hay thước phong thủy) là công cụ đo kích thước do Lỗ Ban – ông tổ nghề mộc – sáng tạo. Mỗi kích thước ứng với cung tốt hoặc xấu.</p><h3>8 cung thước Lỗ Ban</h3><ol><li><strong>Tài (Lộc):</strong> Tốt – tiền bạc, tài lộc</li><li><strong>Bệnh (Ly):</strong> Xấu – bệnh tật, ốm đau</li><li><strong>Ly (Biệt):</strong> Xấu – chia ly, mất mát</li><li><strong>Nghĩa:</strong> Tốt – nghĩa khí, quý nhân</li><li><strong>Quan:</strong> Tốt – thăng quan, danh vọng</li><li><strong>Kiếp (Cướp):</strong> Xấu – hao tài</li><li><strong>Hại:</strong> Xấu – tai họa</li><li><strong>Bản (Vốn):</strong> Tốt – nền tảng vững chắc</li></ol>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Thước Lỗ Ban - Đo kích thước phong thủy",
			MetaDescription: "Thước Lỗ Ban: 8 cung kích thước tốt xấu. Cách đo cửa, bàn thờ, giường theo phong thủy.",
			ReadingTime:     5,
			TagNames:        []string{"Phong thủy", "Nhà ở"},
		},
		{
			Title:       "Phong thủy bể cá: Vị trí đặt bể cá và số lượng cá phù hợp",
			Slug:        "phong-thuy-be-ca-vi-tri-so-luong",
			Excerpt:     "Bể cá phong thủy giúp kích hoạt tài lộc. Vị trí đặt bể, số lượng cá, loại cá phù hợp theo mệnh ngũ hành.",
			Content:     `<h2>Phong thủy bể cá</h2><p>Nước trong phong thủy tượng trưng cho tài lộc. Bể cá là vật phẩm phong thủy mạnh mẽ khi đặt đúng vị trí.</p><h3>Vị trí đặt</h3><ul><li>Phòng khách: bên trái cửa chính nhìn từ trong ra</li><li>Không đặt trong phòng ngủ</li><li>Không đặt đối diện bàn thờ</li><li>Không đặt dưới dầm</li></ul><h3>Số lượng cá</h3><ul><li>1 con: Bạch Thủy tinh</li><li>6 con: Kim sinh Thủy</li><li>8 con: Bạch Tiểu tài</li><li>9 con: Tử Hữu khánh</li></ul><h3>Loại cá</h3><p>Cá rồng, cá chép, cá La Hán là những loại cá phong thủy phổ biến nhất.</p>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Phong thủy bể cá - Vị trí và số lượng cá",
			MetaDescription: "Bể cá phong thủy: vị trí đặt, số lượng cá, loại cá phù hợp. Kích hoạt tài lộc theo ngũ hành.",
			ReadingTime:     5,
			TagNames:        []string{"Phong thủy", "Nhà ở"},
		},
		{
			Title:       "Hướng nhà hợp tuổi: Cách chọn hướng nhà theo năm sinh gia chủ",
			Slug:        "huong-nha-hop-tuoi-theo-nam-sinh",
			Excerpt:     "Chọn hướng nhà phù hợp tuổi gia chủ theo phong thủy Bát trạch. Bảng tra cứu hướng tốt cho 8 mệnh quái.",
			Content:     `<h2>Hướng nhà hợp tuổi</h2><p>Chọn hướng nhà phù hợp với mệnh quái giúp gia đình thịnh vượng, sức khỏe tốt. Mỗi mệnh quái có 4 hướng tốt và 4 hướng xấu.</p><h3>Đông tứ mệnh</h3><ul><li><strong>Khảm (1):</strong> Tốt: Đông Nam, Đông, Nam, Bắc</li><li><strong>Ly (9):</strong> Tốt: Đông, Đông Nam, Bắc, Nam</li><li><strong>Chấn (3):</strong> Tốt: Nam, Bắc, Đông Nam, Đông</li><li><strong>Tốn (4):</strong> Tốt: Bắc, Nam, Đông, Đông Nam</li></ul><h3>Tây tứ mệnh</h3><ul><li><strong>Càn (6):</strong> Tốt: Tây, Đông Bắc, Tây Nam, Tây Bắc</li><li><strong>Khôn (2):</strong> Tốt: Đông Bắc, Tây, Tây Bắc, Tây Nam</li><li><strong>Cấn (8):</strong> Tốt: Tây Nam, Tây Bắc, Tây, Đông Bắc</li><li><strong>Đoài (7):</strong> Tốt: Tây Bắc, Tây Nam, Đông Bắc, Tây</li></ul>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Hướng nhà hợp tuổi - Bảng tra cứu",
			MetaDescription: "Chọn hướng nhà hợp tuổi: Bát trạch, mệnh quái. Bảng tra cứu hướng tốt cho từng mệnh.",
			ReadingTime:     5,
			TagNames:        []string{"Phong thủy", "Nhà ở", "Ngũ hành"},
		},
		{
			Title:       "Phong thủy màu sắc: Chọn màu may mắn theo mệnh ngũ hành",
			Slug:        "phong-thuy-mau-sac-chon-mau-theo-menh",
			Excerpt:     "Mỗi mệnh ngũ hành có màu sắc phù hợp. Hướng dẫn chọn màu may mắn cho nhà ở, quần áo, xe cộ theo mệnh.",
			Content:     `<h2>Phong thủy màu sắc</h2><p>Màu sắc ảnh hưởng mạnh đến tâm lý và năng lượng. Chọn màu phù hợp mệnh ngũ hành giúp tăng cường vận may.</p><h3>Màu sắc theo mệnh</h3><ul><li><strong>Mệnh Kim:</strong> Tốt: trắng, bạc, vàng kim, xám. Tránh: đỏ, cam</li><li><strong>Mệnh Mộc:</strong> Tốt: xanh lá, xanh ngọc, đen, xanh dương. Tránh: trắng, bạc</li><li><strong>Mệnh Thủy:</strong> Tốt: đen, xanh dương, tím, trắng. Tránh: vàng, nâu</li><li><strong>Mệnh Hỏa:</strong> Tốt: đỏ, cam, hồng, xanh lá. Tránh: đen, xanh dương</li><li><strong>Mệnh Thổ:</strong> Tốt: vàng, nâu, cam, đỏ. Tránh: xanh lá, xanh ngọc</li></ul>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Phong thủy màu sắc - Chọn màu theo mệnh",
			MetaDescription: "Chọn màu may mắn theo mệnh ngũ hành: Kim, Mộc, Thủy, Hỏa, Thổ. Phong thủy màu sắc.",
			ReadingTime:     5,
			TagNames:        []string{"Phong thủy", "Ngũ hành"},
		},
		{
			Title:       "10 vật phẩm phong thủy cần có trong nhà để chiêu tài",
			Slug:        "10-vat-pham-phong-thuy-chieu-tai",
			Excerpt:     "Top 10 vật phẩm phong thủy mang lại tài lộc, bình an: Tỳ Hưu, Cóc Ba Chân, Bát Quái, Thuyền Buồm...",
			Content:     `<h2>10 vật phẩm phong thủy</h2><p>Vật phẩm phong thủy được sử dụng để kích hoạt năng lượng tốt, hóa giải sát khí và thu hút tài lộc.</p><h3>Top 10</h3><ol><li><strong>Tỳ Hưu:</strong> Linh vật chiêu tài số 1, chỉ ăn không nhả</li><li><strong>Cóc Ba Chân (Thiềm Thừ):</strong> Ngậm tiền, chiêu tài lộc</li><li><strong>Long Quy:</strong> Rùa đầu rồng, trường thọ và thăng tiến</li><li><strong>Bát Quái:</strong> Hóa giải sát khí, bảo vệ ngôi nhà</li><li><strong>Thuyền Buồm:</strong> Thuận buồm xuôi gió, kinh doanh phát đạt</li><li><strong>Cây Tài Lộc:</strong> Cây đá phong thủy thu hút tiền bạc</li><li><strong>Tượng Phật Di Lặc:</strong> Bình an, vui vẻ, may mắn</li><li><strong>Lục Bình:</strong> Lộc bình, tài lộc</li><li><strong>Chuông Gió:</strong> Xua đuổi tà khí</li><li><strong>Tượng Ngựa:</strong> Mã đáo thành công</li></ol>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "10 vật phẩm phong thủy chiêu tài",
			MetaDescription: "Top 10 vật phẩm phong thủy: Tỳ Hưu, Cóc Ba Chân, Long Quy. Chiêu tài, hóa sát, bình an.",
			ReadingTime:     6,
			TagNames:        []string{"Phong thủy"},
		},
		{
			Title:       "Phong thủy bàn thờ: Cách đặt bàn thờ đúng chuẩn tâm linh",
			Slug:        "phong-thuy-ban-tho-dat-dung-chuan",
			Excerpt:     "Bàn thờ là nơi trang nghiêm nhất trong nhà. Vị trí, hướng, kích thước bàn thờ chuẩn phong thủy và những điều kiêng kỵ.",
			Content:     `<h2>Phong thủy bàn thờ</h2><p>Bàn thờ gia tiên là nơi linh thiêng nhất trong gia đình Việt. Đặt bàn thờ đúng phong thủy giúp gia đình được phù hộ, bình an.</p><h3>Vị trí</h3><ul><li>Đặt ở nơi trang trọng, yên tĩnh</li><li>Cao hơn tầm đầu người</li><li>Lưng bàn thờ tựa vào tường vững chắc</li><li>Không đặt ở hướng nhà vệ sinh</li></ul><h3>Kích thước</h3><p>Dùng thước Lỗ Ban đo kích thước. Chọn cung Tài, Nghĩa, Quan, Bản. Chiều cao bàn thờ thường 1.5-1.7m.</p><h3>Kiêng kỵ</h3><ul><li>Không đặt dưới cầu thang</li><li>Không đặt trong phòng ngủ</li><li>Không để bàn thờ bẩn, bụi</li></ul>`,
			CategorySlug:    "phong-thuy",
			MetaTitle:       "Phong thủy bàn thờ - Đặt đúng chuẩn",
			MetaDescription: "Phong thủy bàn thờ: vị trí, hướng, kích thước Lỗ Ban. Cách đặt bàn thờ đúng chuẩn tâm linh.",
			ReadingTime:     5,
			TagNames:        []string{"Phong thủy", "Nhà ở"},
		},
	}

	return createSeedArticles(db, seeds, tagMap, authorID)
}
