package main

import (
	"fmt"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

func seedLeHoiArticles(db *gorm.DB, tagMap map[string]uuid.UUID, authorID *uuid.UUID) int {
	fmt.Println("\n   🎉 Seeding Lễ Hội articles...")

	seeds := []ArticleSeed{
		{
			Title:           "Tết Nguyên Đán: Nguồn gốc, ý nghĩa và phong tục truyền thống",
			Slug:            "tet-nguyen-dan-nguon-goc-y-nghia-phong-tuc",
			Excerpt:         "Tết Nguyên Đán là lễ hội quan trọng nhất của người Việt. Tìm hiểu nguồn gốc, ý nghĩa văn hóa và những phong tục truyền thống.",
			Content:         `<h2>Tết Nguyên Đán – Lễ hội lớn nhất Việt Nam</h2><p>Tết Nguyên Đán (hay Tết Âm lịch) là lễ hội truyền thống quan trọng nhất của người Việt Nam, đánh dấu sự chuyển giao giữa năm cũ và năm mới theo lịch âm.</p><h3>Nguồn gốc</h3><p>Tết Nguyên Đán có lịch sử hàng nghìn năm, gắn liền với nền văn minh lúa nước. "Nguyên" nghĩa là khởi đầu, "Đán" nghĩa là buổi sáng sớm – Tết Nguyên Đán là buổi sáng đầu tiên của năm mới.</p><h3>Phong tục truyền thống</h3><ul><li><strong>Giao thừa:</strong> Thời khắc thiêng liêng chuyển giao năm cũ sang năm mới</li><li><strong>Xông đất:</strong> Người đầu tiên bước vào nhà đầu năm mang lại vận may</li><li><strong>Lì xì:</strong> Tặng phong bao đỏ chúc may mắn</li><li><strong>Cúng ông Công ông Táo:</strong> Tiễn Táo quân về trời (23 tháng Chạp)</li></ul><h3>Ẩm thực Tết</h3><p>Bánh chưng, bánh tét là món ăn biểu tượng. Mâm ngũ quả trang trí bàn thờ tổ tiên. Mứt Tết, hạt dưa dùng tiếp khách.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Tết Nguyên Đán - Nguồn gốc, ý nghĩa, phong tục",
			MetaDescription: "Tết Nguyên Đán: nguồn gốc, ý nghĩa và phong tục truyền thống. Tìm hiểu lễ hội lớn nhất của người Việt.",
			ReadingTime:     7,
			IsFeatured:      true,
			TagNames:        []string{"Lễ hội", "Tết Nguyên Đán", "Phong tục"},
		},
		{
			Title:           "Tết Trung Thu: Lễ hội trăng rằm và ý nghĩa đoàn viên",
			Slug:            "tet-trung-thu-le-hoi-trang-ram",
			Excerpt:         "Tết Trung Thu rằm tháng 8 – lễ hội của trẻ em và sự đoàn viên gia đình. Nguồn gốc, truyền thuyết và phong tục.",
			Content:         `<h2>Tết Trung Thu – Lễ hội trăng rằm</h2><p>Tết Trung Thu (rằm tháng 8 âm lịch) là lễ hội truyền thống gắn liền với tuổi thơ và ý nghĩa đoàn viên gia đình.</p><h3>Truyền thuyết</h3><p>Truyện chú Cuội ngồi gốc cây đa, chị Hằng trên cung trăng là những câu chuyện gắn liền với Trung Thu trong ký ức mỗi người Việt.</p><h3>Phong tục</h3><ul><li><strong>Rước đèn:</strong> Trẻ em rước đèn ông sao, đèn cá chép đi khắp phố</li><li><strong>Phá cỗ:</strong> Bày mâm cỗ với bánh nướng, bánh dẻo, trái cây</li><li><strong>Múa lân:</strong> Đoàn lân biểu diễn sôi động</li></ul><h3>Bánh Trung Thu</h3><p>Bánh nướng và bánh dẻo là hai loại bánh truyền thống. Hiện nay có thêm nhiều hương vị mới: trà xanh, dừa, sầu riêng.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Tết Trung Thu - Lễ hội trăng rằm đoàn viên",
			MetaDescription: "Tết Trung Thu: nguồn gốc, truyền thuyết, phong tục rước đèn, phá cỗ. Ý nghĩa đoàn viên gia đình.",
			ReadingTime:     6,
			IsFeatured:      true,
			TagNames:        []string{"Lễ hội", "Tết Trung Thu", "Phong tục"},
		},
		{
			Title:       "Lễ hội Đền Hùng: Giỗ Tổ Hùng Vương mùng 10 tháng 3",
			Slug:        "le-hoi-den-hung-gio-to-hung-vuong",
			Excerpt:     "Giỗ Tổ Hùng Vương 10/3 âm lịch – lễ hội thiêng liêng nhất tưởng nhớ các Vua Hùng dựng nước. Di sản văn hóa phi vật thể.",
			Content:     `<h2>Lễ hội Đền Hùng – Giỗ Tổ Hùng Vương</h2><p>Mùng 10 tháng 3 âm lịch hàng năm, cả nước hướng về Đền Hùng (Phú Thọ) để tưởng nhớ các Vua Hùng – những người đã có công dựng nước.</p><h3>Ý nghĩa</h3><p>"Dù ai đi ngược về xuôi, nhớ ngày Giỗ Tổ mùng Mười tháng Ba." Lễ hội Đền Hùng thể hiện đạo lý "Uống nước nhớ nguồn" – giá trị cốt lõi của văn hóa Việt.</p><h3>Nghi lễ</h3><ul><li>Lễ dâng hương tại Đền Thượng</li><li>Lễ rước kiệu vua</li><li>Hội trại các dân tộc</li></ul><h3>Di sản UNESCO</h3><p>Năm 2012, "Tín ngưỡng thờ cúng Hùng Vương" được UNESCO công nhận là Di sản văn hóa phi vật thể đại diện của nhân loại.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Lễ hội Đền Hùng - Giỗ Tổ Hùng Vương 10/3",
			MetaDescription: "Giỗ Tổ Hùng Vương 10/3 âm lịch tại Đền Hùng, Phú Thọ. Nguồn gốc, nghi lễ và di sản UNESCO.",
			ReadingTime:     6,
			IsFeatured:      true,
			TagNames:        []string{"Lễ hội", "Đền Hùng", "Di sản văn hóa"},
		},
		{
			Title:       "Lễ Vu Lan báo hiếu: Mùa hiếu hạnh tháng 7 âm lịch",
			Slug:        "le-vu-lan-bao-hieu-thang-7",
			Excerpt:     "Vu Lan rằm tháng 7 – mùa báo hiếu cha mẹ, tưởng nhớ người đã khuất. Nguồn gốc, ý nghĩa và phong tục.",
			Content:     `<h2>Lễ Vu Lan Báo Hiếu</h2><p>Vu Lan (rằm tháng 7 âm lịch) là dịp người Việt thể hiện lòng hiếu thảo với cha mẹ và tưởng nhớ tổ tiên. Ngày này gắn liền với tích Mục Kiền Liên cứu mẹ.</p><h3>Nguồn gốc</h3><p>Theo kinh Phật, Bồ tát Mục Kiền Liên dùng phép thuật tìm mẹ trong địa ngục. Nhờ lời Phật dạy, ông tổ chức lễ cúng vào rằm tháng 7 để cứu mẹ khỏi kiếp ngạ quỷ.</p><h3>Phong tục</h3><ul><li><strong>Cài hoa hồng:</strong> Hồng đỏ – còn mẹ, hồng trắng – mất mẹ</li><li><strong>Cúng cô hồn:</strong> Bố thí cho những vong linh không nơi nương tựa</li><li><strong>Phóng sinh:</strong> Thả chim, cá để tích đức</li></ul>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Lễ Vu Lan Báo Hiếu - Rằm tháng 7",
			MetaDescription: "Vu Lan rằm tháng 7: báo hiếu cha mẹ. Nguồn gốc, ý nghĩa và phong tục truyền thống.",
			ReadingTime:     5,
			TagNames:        []string{"Lễ hội", "Vu Lan", "Phong tục"},
		},
		{
			Title:       "Tết Đoan Ngọ mùng 5 tháng 5: Tết diệt sâu bọ và phong tục thú vị",
			Slug:        "tet-doan-ngo-mung-5-thang-5",
			Excerpt:     "Tết Đoan Ngọ (5/5 âm lịch) – lễ hội diệt sâu bọ với nhiều phong tục thú vị như ăn rượu nếp, trái cây và tắm nước lá.",
			Content:     `<h2>Tết Đoan Ngọ – Tết diệt sâu bọ</h2><p>Tết Đoan Ngọ diễn ra vào mùng 5 tháng 5 âm lịch, còn gọi là "Tết diệt sâu bọ" hay "Tết Nửa năm". Đây là một trong những lễ tết truyền thống lâu đời của người Việt.</p><h3>Ý nghĩa</h3><p>Theo quan niệm dân gian, đây là thời điểm sâu bọ phát triển mạnh. Các phong tục trong ngày này nhằm tiêu diệt mầm bệnh, cầu sức khỏe.</p><h3>Phong tục</h3><ul><li>Ăn rượu nếp và trái cây vào sáng sớm</li><li>Tắm nước lá mùi</li><li>Nhuộm móng tay bằng lá móng</li><li>Hái thuốc vào giờ Ngọ</li></ul>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Tết Đoan Ngọ 5/5 - Diệt sâu bọ, phong tục",
			MetaDescription: "Tết Đoan Ngọ mùng 5 tháng 5: tết diệt sâu bọ, ăn rượu nếp. Nguồn gốc và phong tục.",
			ReadingTime:     5,
			TagNames:        []string{"Lễ hội", "Phong tục"},
		},
		{
			Title:       "Lễ hội Chùa Hương: Hành trình tâm linh đất Phật",
			Slug:        "le-hoi-chua-huong-hanh-trinh-tam-linh",
			Excerpt:     "Lễ hội Chùa Hương kéo dài 3 tháng mùa xuân – lễ hội tâm linh lớn nhất Việt Nam với cảnh sắc hữu tình và tín ngưỡng sâu sắc.",
			Content:     `<h2>Lễ hội Chùa Hương</h2><p>Chùa Hương (Mỹ Đức, Hà Nội) là quần thể di tích và danh lam thắng cảnh nổi tiếng. Lễ hội Chùa Hương diễn ra từ mùng 6 tháng Giêng đến hết tháng 3 âm lịch.</p><h3>Hành trình</h3><p>Du khách đi thuyền trên suối Yến giữa cảnh núi non hùng vĩ, ghé thăm các đền chùa dọc đường. Đỉnh điểm là Động Hương Tích – "Nam thiên đệ nhất động".</p><h3>Tín ngưỡng</h3><p>Hàng triệu phật tử và du khách đến cầu may, cầu tài lộc, sức khỏe. Đây là lễ hội tâm linh thu hút nhiều người nhất Việt Nam.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Lễ hội Chùa Hương - Hành trình tâm linh",
			MetaDescription: "Lễ hội Chùa Hương: hành trình tâm linh mùa xuân. Suối Yến, Động Hương Tích và tín ngưỡng.",
			ReadingTime:     5,
			TagNames:        []string{"Lễ hội", "Du lịch tâm linh", "Di sản văn hóa"},
		},
		{
			Title:       "Lễ hội Gióng: Tái hiện truyền thuyết Thánh Gióng đánh giặc Ân",
			Slug:        "le-hoi-giong-truyen-thuyet-thanh-giong",
			Excerpt:     "Lễ hội Gióng tại Sóc Sơn – di sản UNESCO, tái hiện truyền thuyết Phù Đổng Thiên Vương đánh giặc Ân bảo vệ đất nước.",
			Content:     `<h2>Lễ hội Gióng – Di sản UNESCO</h2><p>Lễ hội Gióng được tổ chức tại đền Sóc (Sóc Sơn, Hà Nội) và đền Phù Đổng (Gia Lâm), tái hiện truyền thuyết Thánh Gióng đánh giặc Ân.</p><h3>Truyền thuyết</h3><p>Cậu bé Gióng 3 tuổi bỗng cất tiếng nói đòi đánh giặc. Vươn mình thành tráng sĩ, mặc áo giáp sắt, cưỡi ngựa sắt phun lửa đánh tan giặc Ân rồi bay về trời.</p><h3>Di sản</h3><p>Năm 2010, UNESCO công nhận Hội Gióng đền Phù Đổng và đền Sóc là Di sản văn hóa phi vật thể đại diện của nhân loại.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Lễ hội Gióng - Di sản UNESCO, truyền thuyết Thánh Gióng",
			MetaDescription: "Lễ hội Gióng: tái hiện truyền thuyết Thánh Gióng. Di sản UNESCO tại Sóc Sơn, Hà Nội.",
			ReadingTime:     5,
			TagNames:        []string{"Lễ hội", "Di sản văn hóa", "Truyền thuyết"},
		},
		{
			Title:       "Lễ hội Cầu Ngư: Tín ngưỡng thờ Cá Ông của ngư dân miền Trung",
			Slug:        "le-hoi-cau-ngu-tho-ca-ong",
			Excerpt:     "Lễ hội Cầu Ngư – tín ngưỡng thờ Cá Ông (cá voi) của ngư dân ven biển miền Trung, cầu mong biển lặng, mùa cá bội thu.",
			Content:     `<h2>Lễ hội Cầu Ngư</h2><p>Lễ hội Cầu Ngư là tín ngưỡng đặc trưng của ngư dân ven biển miền Trung Việt Nam, thể hiện lòng tôn kính với Cá Ông (cá voi) – vị thần bảo hộ trên biển.</p><h3>Tín ngưỡng</h3><p>Ngư dân coi cá voi là vị thần cứu nạn trên biển. Khi cá voi chết dạt vào bờ, họ tổ chức tang lễ trang trọng và lập miếu thờ.</p><h3>Nghi lễ</h3><ul><li>Lễ rước Cá Ông</li><li>Hát bả trạo (bài hát chèo thuyền)</li><li>Các trò chơi dân gian: đua thuyền, bơi lội</li></ul>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Lễ hội Cầu Ngư - Tín ngưỡng thờ Cá Ông",
			MetaDescription: "Lễ hội Cầu Ngư: tín ngưỡng thờ Cá Ông, cầu bình an cho ngư dân miền Trung.",
			ReadingTime:     5,
			TagNames:        []string{"Lễ hội", "Phong tục", "Di sản văn hóa"},
		},
		{
			Title:       "Lễ hội Đua Ghe Ngo: Hội đua truyền thống của người Khmer Nam Bộ",
			Slug:        "le-hoi-dua-ghe-ngo-khmer-nam-bo",
			Excerpt:     "Đua Ghe Ngo – lễ hội đua thuyền truyền thống của người Khmer ở Sóc Trăng, diễn ra trong dịp Oóc Om Bóc rằm tháng 10.",
			Content:     `<h2>Lễ hội Đua Ghe Ngo</h2><p>Lễ hội Đua Ghe Ngo là sự kiện thể thao và văn hóa đặc sắc của đồng bào Khmer Nam Bộ, diễn ra hàng năm tại Sóc Trăng vào dịp Oóc Om Bóc (rằm tháng 10 âm lịch).</p><h3>Ghe Ngo</h3><p>Ghe Ngo dài 25-30m, chở 40-60 tay chèo. Mỗi chiếc ghe được trang trí đẹp mắt, đại diện cho một chùa Khmer. Việc đóng và hạ thủy ghe là nghi lễ thiêng liêng.</p><h3>Ý nghĩa</h3><p>Lễ hội thể hiện tinh thần đoàn kết, sức mạnh tập thể và tín ngưỡng cảm tạ thần Mặt Trăng của người Khmer.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Lễ hội Đua Ghe Ngo - Khmer Nam Bộ",
			MetaDescription: "Đua Ghe Ngo: lễ hội đua thuyền truyền thống Khmer Nam Bộ, Sóc Trăng. Oóc Om Bóc rằm tháng 10.",
			ReadingTime:     5,
			TagNames:        []string{"Lễ hội", "Di sản văn hóa", "Phong tục"},
		},
		{
			Title:       "Lễ hội Chọi Trâu Đồ Sơn: Truyền thống độc đáo xứ biển Hải Phòng",
			Slug:        "le-hoi-choi-trau-do-son-hai-phong",
			Excerpt:     "Chọi Trâu Đồ Sơn – lễ hội truyền thống hàng trăm năm tại Hải Phòng. Nguồn gốc, nghi lễ và giá trị văn hóa.",
			Content:     `<h2>Lễ hội Chọi Trâu Đồ Sơn</h2><p>Lễ hội Chọi Trâu Đồ Sơn diễn ra vào ngày 9 tháng 8 âm lịch tại Đồ Sơn, Hải Phòng. Đây là di sản văn hóa phi vật thể quốc gia với lịch sử hàng trăm năm.</p><h3>Chuẩn bị</h3><p>Các chủ trâu chọn mua và huấn luyện trâu từ nhiều tháng trước. Con trâu chọi phải có tướng mạo uy nghi, sức khỏe dẻo dai.</p><h3>Diễn ra</h3><p>Trâu được trang trí và rước từ đình ra sới chọi. Trận đấu diễn ra với sự cổ vũ nồng nhiệt của hàng nghìn khán giả.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Lễ hội Chọi Trâu Đồ Sơn, Hải Phòng",
			MetaDescription: "Chọi Trâu Đồ Sơn: lễ hội truyền thống Hải Phòng. Nguồn gốc, nghi lễ và ý nghĩa văn hóa.",
			ReadingTime:     5,
			TagNames:        []string{"Lễ hội", "Di sản văn hóa"},
		},
		{
			Title:       "Tết Thanh Minh: Ngày tảo mộ và tưởng nhớ tổ tiên",
			Slug:        "tet-thanh-minh-tao-mo-tuong-nho-to-tien",
			Excerpt:     "Tết Thanh Minh (3/3 âm lịch) – ngày tảo mộ, sửa sang mồ mả tổ tiên. Ý nghĩa tâm linh và phong tục truyền thống.",
			Content:     `<h2>Tết Thanh Minh</h2><p>Tết Thanh Minh diễn ra vào khoảng tháng 3 âm lịch, là dịp người Việt đi tảo mộ, sửa sang mồ mả và cúng tế tổ tiên.</p><h3>Ý nghĩa</h3><p>Thanh Minh thể hiện đạo lý "Uống nước nhớ nguồn", lòng hiếu kính đối với ông bà tổ tiên. Đây cũng là dịp gia đình sum họp, gắn kết.</p><h3>Phong tục</h3><ul><li>Dọn dẹp, sửa sang phần mộ tổ tiên</li><li>Đắp thêm đất, trồng cây quanh mộ</li><li>Cúng lễ tại mộ và tại nhà</li><li>Sum họp gia đình</li></ul>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Tết Thanh Minh - Tảo mộ tưởng nhớ tổ tiên",
			MetaDescription: "Tết Thanh Minh: ngày tảo mộ, sửa mồ mả tổ tiên. Ý nghĩa và phong tục truyền thống.",
			ReadingTime:     4,
			TagNames:        []string{"Lễ hội", "Phong tục", "Tết Thanh Minh"},
		},
		{
			Title:       "Lễ hội Lồng Tồng: Hội xuống đồng của đồng bào dân tộc thiểu số",
			Slug:        "le-hoi-long-tong-hoi-xuong-dong",
			Excerpt:     "Lồng Tồng – lễ hội xuống đồng truyền thống của người Tày, Nùng vùng Đông Bắc. Cầu mùa màng bội thu, dân khang vật thịnh.",
			Content:     `<h2>Lễ hội Lồng Tồng</h2><p>Lồng Tồng (nghĩa là "xuống đồng") là lễ hội nông nghiệp truyền thống của đồng bào Tày, Nùng vùng Đông Bắc Việt Nam.</p><h3>Thời gian</h3><p>Lễ hội diễn ra vào đầu xuân, thường từ mùng 4 đến mùng 10 tháng Giêng âm lịch.</p><h3>Nghi lễ</h3><p>Thầy Tào làm lễ cúng thần nông, cầu cho mưa thuận gió hòa. Sau phần lễ là phần hội với các trò chơi: tung còn, múa sư tử, đánh đu, kéo co.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Lễ hội Lồng Tồng - Hội xuống đồng",
			MetaDescription: "Lồng Tồng: lễ hội xuống đồng của người Tày, Nùng vùng Đông Bắc. Phong tục và trò chơi dân gian.",
			ReadingTime:     4,
			TagNames:        []string{"Lễ hội", "Di sản văn hóa", "Phong tục"},
		},
		{
			Title:       "Lễ hội Đền Trần: Khai ấn đầu xuân và tín ngưỡng thờ Trần",
			Slug:        "le-hoi-den-tran-khai-an-dau-xuan",
			Excerpt:     "Lễ hội Đền Trần (Nam Định) với nghi lễ khai ấn đêm 14 tháng Giêng – cầu tài lộc, thăng quan tiến chức.",
			Content:     `<h2>Lễ hội Đền Trần</h2><p>Lễ hội Đền Trần diễn ra tại phủ Thiên Trường (Nam Định), nơi thờ 14 vị vua nhà Trần. Nghi lễ khai ấn đêm 14 tháng Giêng thu hút hàng vạn người.</p><h3>Khai ấn</h3><p>Đúng giờ Tý đêm 14 rạng 15 tháng Giêng, nghi lễ khai ấn được tiến hành. Ấn "Trần miếu tự điển" được đóng lên giấy đỏ, phát cho người dân cầu may.</p><h3>Ý nghĩa</h3><p>Khai ấn tượng trưng cho việc khai mở công việc đầu năm, cầu mong sự hanh thông trong sự nghiệp.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Lễ hội Đền Trần - Khai ấn đầu xuân Nam Định",
			MetaDescription: "Lễ hội Đền Trần: khai ấn đêm 14 tháng Giêng. Tín ngưỡng thờ nhà Trần tại Nam Định.",
			ReadingTime:     5,
			TagNames:        []string{"Lễ hội", "Du lịch tâm linh"},
		},
		{
			Title:       "Lễ hội Katê: Tết của người Chăm tôn vinh thần Shiva",
			Slug:        "le-hoi-kate-tet-nguoi-cham",
			Excerpt:     "Katê – lễ hội lớn nhất của người Chăm Bà La Môn, diễn ra tại tháp Po Klong Garai (Ninh Thuận), tôn vinh các vị vua Chăm.",
			Content:     `<h2>Lễ hội Katê của người Chăm</h2><p>Katê là lễ hội truyền thống quan trọng nhất của người Chăm theo đạo Bà La Môn, diễn ra vào ngày 1 tháng 7 lịch Chăm (khoảng tháng 9-10 dương lịch).</p><h3>Địa điểm</h3><p>Lễ hội diễn ra tại các tháp Chăm cổ, nổi tiếng nhất là tháp Po Klong Garai ở Ninh Thuận.</p><h3>Nghi lễ</h3><ul><li>Lễ rước y trang lên tháp</li><li>Lễ mở cửa tháp</li><li>Lễ tắm tượng thần</li><li>Múa quạt, múa trống, nhạc lễ truyền thống</li></ul>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Lễ hội Katê - Tết người Chăm, Ninh Thuận",
			MetaDescription: "Katê: lễ hội lớn nhất người Chăm Bà La Môn tại tháp Po Klong Garai, Ninh Thuận.",
			ReadingTime:     5,
			TagNames:        []string{"Lễ hội", "Di sản văn hóa", "Phong tục"},
		},
		{
			Title:       "Hội Lim: Lễ hội quan họ Bắc Ninh – Di sản phi vật thể UNESCO",
			Slug:        "hoi-lim-le-hoi-quan-ho-bac-ninh",
			Excerpt:     "Hội Lim – lễ hội quan họ nổi tiếng nhất vùng Kinh Bắc. Hát quan họ trên thuyền, các trò chơi dân gian đặc sắc.",
			Content:     `<h2>Hội Lim – Vùng Kinh Bắc</h2><p>Hội Lim diễn ra ngày 13 tháng Giêng tại Tiên Du, Bắc Ninh. Đây là lễ hội nổi tiếng nhất gắn với dân ca Quan họ – di sản UNESCO.</p><h3>Quan họ</h3><p>Liền anh liền chị hát đối đáp giao duyên trên thuyền rồng giữa hồ. Giọng hát quan họ ngọt ngào, da diết, là biểu tượng văn hóa vùng Kinh Bắc.</p><h3>Hoạt động</h3><ul><li>Hát quan họ trên thuyền</li><li>Đấu vật, đánh đu, chọi gà</li><li>Thi dệt vải, nấu cơm</li></ul>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Hội Lim - Quan họ Bắc Ninh UNESCO",
			MetaDescription: "Hội Lim: lễ hội quan họ Bắc Ninh. Hát giao duyên trên thuyền, di sản UNESCO.",
			ReadingTime:     5,
			TagNames:        []string{"Lễ hội", "Di sản văn hóa"},
		},
		{
			Title:       "Lễ hội Đua Bò Bảy Núi: Truyền thống độc đáo của người Khmer An Giang",
			Slug:        "le-hoi-dua-bo-bay-nui-an-giang",
			Excerpt:     "Đua Bò Bảy Núi – lễ hội thể thao truyền thống của đồng bào Khmer ở An Giang. Những cặp bò kéo bừa phi nước đại trên ruộng.",
			Content:     `<h2>Lễ hội Đua Bò Bảy Núi</h2><p>Đua Bò Bảy Núi diễn ra vào dịp lễ Sene Dolta (lễ cúng ông bà) của người Khmer, tại vùng Bảy Núi, An Giang.</p><h3>Cách thức</h3><p>Mỗi đội gồm cặp bò kéo bừa với một người điều khiển. Đường đua là ruộng nước ngập 20-30cm. Cặp bò phi nước đại tung bùn nước tạo nên cảnh tượng ngoạn mục.</p><h3>Ý nghĩa</h3><p>Lễ hội gắn liền với nền nông nghiệp lúa nước, tôn vinh sức mạnh của con bò – người bạn đồng hành của nông dân.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Đua Bò Bảy Núi An Giang",
			MetaDescription: "Đua Bò Bảy Núi: lễ hội thể thao truyền thống Khmer An Giang. Bò kéo bừa phi nước đại.",
			ReadingTime:     4,
			TagNames:        []string{"Lễ hội", "Di sản văn hóa", "Phong tục"},
		},
		{
			Title:       "Tết Hàn Thực mùng 3 tháng 3: Ngày bánh trôi bánh chay",
			Slug:        "tet-han-thuc-mung-3-thang-3",
			Excerpt:     "Tết Hàn Thực (3/3 âm lịch) – ngày ăn đồ nguội với bánh trôi, bánh chay. Nguồn gốc, ý nghĩa và cách người Việt biến đổi.",
			Content:     `<h2>Tết Hàn Thực</h2><p>Tết Hàn Thực diễn ra vào mùng 3 tháng 3 âm lịch. Tuy có nguồn gốc từ Trung Quốc nhưng người Việt đã biến đổi với ý nghĩa riêng.</p><h3>Nguồn gốc</h3><p>"Hàn Thực" nghĩa là ăn đồ nguội. Truyền thuyết kể về Giới Tử Thôi trung thành với vua Tấn Văn Công thời Xuân Thu.</p><h3>Ý nghĩa Việt</h3><p>Người Việt dùng ngày này để tưởng nhớ tổ tiên, cha mẹ. Bánh trôi, bánh chay được dâng lên bàn thờ với lòng thành kính.</p><h3>Bánh trôi bánh chay</h3><p>Bánh trôi làm từ bột nếp, nhân đường phên. Bánh chay không nhân, ăn với nước đường pha gừng.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Tết Hàn Thực 3/3 - Bánh trôi bánh chay",
			MetaDescription: "Tết Hàn Thực mùng 3 tháng 3: nguồn gốc, ý nghĩa. Bánh trôi bánh chay truyền thống.",
			ReadingTime:     4,
			TagNames:        []string{"Lễ hội", "Phong tục"},
		},
		{
			Title:       "Lễ hội Nghinh Ông: Rước Ông Nam Hải về bảo hộ ngư dân",
			Slug:        "le-hoi-nghinh-ong-ruck-nam-hai",
			Excerpt:     "Lễ hội Nghinh Ông tại Cần Giờ, TP.HCM – lễ rước cá voi trên biển lớn nhất Nam Bộ, cầu bình an cho ngư dân.",
			Content:     `<h2>Lễ hội Nghinh Ông – Cần Giờ</h2><p>Lễ hội Nghinh Ông diễn ra vào ngày 15-16 tháng 8 âm lịch tại Cần Giờ, TP.HCM, là lễ hội dân gian gắn với biển lớn nhất Nam Bộ.</p><h3>Nghi lễ</h3><p>Hàng trăm ghe thuyền trang hoàng lộng lẫy ra biển rước Ông (cá voi) về đình. Đoàn rước kéo dài hàng km trên biển, tạo nên cảnh tượng ngoạn mục.</p><h3>Ý nghĩa</h3><p>Cầu mong Ông Nam Hải phù hộ cho ngư dân bình an, mùa cá bội thu.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Lễ hội Nghinh Ông Cần Giờ",
			MetaDescription: "Nghinh Ông Cần Giờ: lễ rước cá voi trên biển lớn nhất Nam Bộ, cầu bình an cho ngư dân.",
			ReadingTime:     4,
			TagNames:        []string{"Lễ hội", "Phong tục"},
		},
		{
			Title:       "Lễ hội Yên Tử: Hành hương về miền đất Phật",
			Slug:        "le-hoi-yen-tu-hanh-huong-dat-phat",
			Excerpt:     "Hành hương Yên Tử (Quảng Ninh) – nơi Phật hoàng Trần Nhân Tông sáng lập Thiền phái Trúc Lâm. Lễ hội tâm linh đặc sắc.",
			Content:     `<h2>Lễ hội Yên Tử</h2><p>Yên Tử (Quảng Ninh) được mệnh danh là "đất tổ Phật giáo Việt Nam" – nơi Phật hoàng Trần Nhân Tông sáng lập Thiền phái Trúc Lâm. Lễ hội diễn ra từ mùng 10 tháng Giêng đến hết tháng 3 âm lịch.</p><h3>Hành hương</h3><p>Từ chân núi lên chùa Đồng trên đỉnh Yên Tử (1068m) phải leo hàng nghìn bậc đá qua rừng trúc, suối trong, mây mù. Đây là hành trình tu tâm đầy ý nghĩa.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Lễ hội Yên Tử - Hành hương đất Phật",
			MetaDescription: "Lễ hội Yên Tử: hành hương về miền đất Phật, Thiền phái Trúc Lâm, Quảng Ninh.",
			ReadingTime:     5,
			TagNames:        []string{"Lễ hội", "Du lịch tâm linh", "Di sản văn hóa"},
		},
		{
			Title:       "Lễ Cúng Ông Công Ông Táo 23 tháng Chạp: Ý nghĩa và nghi thức",
			Slug:        "cung-ong-cong-ong-tao-23-thang-chap",
			Excerpt:     "Ngày 23 tháng Chạp – tiễn ông Công ông Táo về trời. Nguồn gốc truyền thuyết, ý nghĩa tâm linh và nghi thức thả cá chép.",
			Content:     `<h2>Cúng Ông Công Ông Táo</h2><p>Ngày 23 tháng Chạp hàng năm, người Việt tiễn ông Công ông Táo (Táo quân) lên thiên đình báo cáo việc tốt xấu của gia đình trong năm qua.</p><h3>Truyền thuyết</h3><p>Truyện kể về hai ông một bà – Trọng Cao, Thị Nhi và Phạm Lang – ba người sau khi mất được Ngọc Hoàng phong làm Táo quân coi việc bếp núc.</p><h3>Nghi thức</h3><ul><li>Chuẩn bị lễ vật: mũ, áo, hia cho Táo quân</li><li>Thả cá chép để Táo quân cưỡi về trời</li><li>Đốt vàng mã</li><li>Dọn dẹp nhà bếp sạch sẽ</li></ul><h3>Ý nghĩa</h3><p>Đây là dịp để gia đình nhìn lại năm cũ, dọn dẹp nhà cửa chuẩn bị đón Tết.</p>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Cúng Ông Công Ông Táo 23 tháng Chạp",
			MetaDescription: "Ông Công Ông Táo 23 tháng Chạp: truyền thuyết, ý nghĩa, nghi thức thả cá chép.",
			ReadingTime:     5,
			TagNames:        []string{"Lễ hội", "Phong tục", "Tết Nguyên Đán"},
		},
		{
			Title:       "Lễ hội Bà Chúa Xứ núi Sam: Thánh địa tâm linh An Giang",
			Slug:        "le-hoi-ba-chua-xu-nui-sam",
			Excerpt:     "Lễ hội Bà Chúa Xứ núi Sam (Châu Đốc, An Giang) – lễ hội tâm linh lớn nhất Nam Bộ, thu hút hàng triệu khách hành hương.",
			Content:     `<h2>Lễ hội Bà Chúa Xứ</h2><p>Miếu Bà Chúa Xứ núi Sam (Châu Đốc, An Giang) là điểm hành hương tâm linh nổi tiếng nhất Nam Bộ. Lễ hội diễn ra từ 23 đến 27 tháng 4 âm lịch.</p><h3>Tín ngưỡng</h3><p>Bà Chúa Xứ được người dân tôn thờ cầu tài lộc, bình an. Tượng Bà bằng đá xanh, có từ thế kỷ 6, ngự trên đỉnh núi Sam.</p><h3>Lễ hội</h3><ul><li>Lễ tắm Bà: rửa tượng, thay y phục mới</li><li>Lễ rước tượng Bà</li><li>Lễ túc yết và xây chầu</li></ul>`,
			CategorySlug:    "le-hoi",
			MetaTitle:       "Lễ hội Bà Chúa Xứ núi Sam, An Giang",
			MetaDescription: "Lễ hội Bà Chúa Xứ: thánh địa tâm linh An Giang. Lễ tắm Bà, rước tượng và tín ngưỡng.",
			ReadingTime:     5,
			TagNames:        []string{"Lễ hội", "Du lịch tâm linh"},
		},
	}

	return createSeedArticles(db, seeds, tagMap, authorID)
}
