package main

import (
	"fmt"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

func seedThanSoHocArticles(db *gorm.DB, tagMap map[string]uuid.UUID, authorID *uuid.UUID) int {
	fmt.Println("\n   🔢 Seeding Thần Số Học articles...")

	seeds := []ArticleSeed{
		{
			Title:           "Thần số học là gì? Hướng dẫn toàn diện cho người mới bắt đầu",
			Slug:            "than-so-hoc-la-gi-huong-dan-toan-dien",
			Excerpt:         "Thần số học (Numerology) là gì? Cách tính số chủ đạo, ý nghĩa các con số và cách áp dụng vào cuộc sống. Hướng dẫn chi tiết.",
			Content:         `<h2>Thần số học là gì?</h2><p>Thần số học (Numerology) là bộ môn nghiên cứu mối quan hệ thần bí giữa các con số và sự kiện trong cuộc sống. Mỗi con số mang một rung động năng lượng riêng, ảnh hưởng đến tính cách, vận mệnh và mối quan hệ.</p><h3>Lịch sử thần số học</h3><p>Thần số học có nguồn gốc từ thời Pythagoras (Hy Lạp cổ đại), được phát triển qua các nền văn minh Babylon, Ai Cập, Ấn Độ và Trung Quốc.</p><h3>Các hệ thống chính</h3><ul><li><strong>Pythagorean:</strong> Hệ thống phổ biến nhất, sử dụng số 1-9</li><li><strong>Chaldean:</strong> Hệ thống cổ đại từ Babylon</li><li><strong>Kabbalah:</strong> Dựa trên bảng chữ cái Hebrew</li></ul><h3>Cách tính số chủ đạo</h3><p>Cộng tất cả các chữ số trong ngày sinh, rút gọn thành một chữ số (1-9) hoặc số master (11, 22, 33). Ví dụ: 15/08/1990 → 1+5+0+8+1+9+9+0 = 33 → Số master 33.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Thần số học là gì? Hướng dẫn toàn diện",
			MetaDescription: "Thần số học là gì? Cách tính số chủ đạo, ý nghĩa các con số. Hướng dẫn chi tiết cho người mới bắt đầu.",
			ReadingTime:     7,
			IsFeatured:      true,
			TagNames:        []string{"Thần số học", "Huyền học"},
		},
		{
			Title:       "Số chủ đạo 1: Người lãnh đạo bẩm sinh và tiên phong",
			Slug:        "so-chu-dao-1-nguoi-lanh-dao-bam-sinh",
			Excerpt:     "Ý nghĩa số chủ đạo 1 trong thần số học: tính cách lãnh đạo, độc lập, sáng tạo. Sự nghiệp, tình yêu và lời khuyên.",
			Content:     `<h2>Số chủ đạo 1 – Người tiên phong</h2><p>Số 1 là con số của sự khởi đầu, lãnh đạo và độc lập. Người mang số chủ đạo 1 có bản năng dẫn dắt, sáng tạo và luôn muốn đứng đầu.</p><h3>Tính cách</h3><ul><li>Độc lập, tự tin, quyết đoán</li><li>Sáng tạo, có tầm nhìn</li><li>Tham vọng, không chấp nhận thất bại</li></ul><h3>Sự nghiệp phù hợp</h3><p>CEO, doanh nhân, nhà sáng lập, chính trị gia, quản lý cấp cao.</p><h3>Tình yêu</h3><p>Cần đối tác tôn trọng sự độc lập. Hợp với số 3, 5, 7.</p><h3>Thách thức</h3><p>Cần tránh độc đoán, học cách lắng nghe và hợp tác.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Số chủ đạo 1 - Thần số học",
			MetaDescription: "Số chủ đạo 1: người lãnh đạo bẩm sinh. Tính cách, sự nghiệp, tình yêu trong thần số học.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Số chủ đạo"},
		},
		{
			Title:       "Số chủ đạo 2: Người hòa giải và kết nối",
			Slug:        "so-chu-dao-2-nguoi-hoa-giai-ket-noi",
			Excerpt:     "Số chủ đạo 2 trong thần số học: nhạy cảm, hợp tác, hài hòa. Khám phá tính cách và vận mệnh của người mang số 2.",
			Content:     `<h2>Số chủ đạo 2 – Người hòa giải</h2><p>Số 2 đại diện cho sự cân bằng, hợp tác và nhạy cảm. Người số 2 là cầu nối giữa con người, mang lại hài hòa cho mọi mối quan hệ.</p><h3>Tính cách</h3><ul><li>Nhạy cảm, đồng cảm cao</li><li>Giỏi lắng nghe và hòa giải</li><li>Kiên nhẫn, trung thành</li></ul><h3>Sự nghiệp phù hợp</h3><p>Tư vấn, ngoại giao, nhân sự, tâm lý, nghệ thuật, dịch vụ khách hàng.</p><h3>Tình yêu</h3><p>Người số 2 yêu sâu sắc, cần sự an toàn. Hợp với số 4, 6, 8.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Số chủ đạo 2 - Thần số học",
			MetaDescription: "Số chủ đạo 2: người hòa giải, nhạy cảm, hợp tác. Tính cách và vận mệnh trong thần số học.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Số chủ đạo"},
		},
		{
			Title:       "Số chủ đạo 3: Người sáng tạo và truyền cảm hứng",
			Slug:        "so-chu-dao-3-nguoi-sang-tao-truyen-cam-hung",
			Excerpt:     "Số 3 trong thần số học: sáng tạo, lạc quan, giao tiếp xuất sắc. Tìm hiểu con đường sự nghiệp và tình yêu của số 3.",
			Content:     `<h2>Số chủ đạo 3 – Người sáng tạo</h2><p>Số 3 là con số của sáng tạo, biểu đạt và niềm vui. Người số 3 có khả năng truyền cảm hứng cho mọi người xung quanh bằng sự lạc quan và tài năng nghệ thuật.</p><h3>Tính cách</h3><ul><li>Sáng tạo, có năng khiếu nghệ thuật</li><li>Lạc quan, vui vẻ, hài hước</li><li>Giao tiếp xuất sắc, thu hút</li></ul><h3>Sự nghiệp phù hợp</h3><p>Nghệ sĩ, nhà văn, diễn giả, marketing, truyền thông, giải trí, thiết kế.</p><h3>Thách thức</h3><p>Cần tập trung, tránh phân tán năng lượng vào quá nhiều dự án.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Số chủ đạo 3 - Thần số học",
			MetaDescription: "Số chủ đạo 3: sáng tạo, lạc quan, truyền cảm hứng. Sự nghiệp và tình yêu trong thần số học.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Số chủ đạo"},
		},
		{
			Title:       "Số chủ đạo 4: Người xây dựng nền tảng vững chắc",
			Slug:        "so-chu-dao-4-nguoi-xay-dung-nen-tang",
			Excerpt:     "Số 4 trong thần số học: kỷ luật, chăm chỉ, đáng tin cậy. Khám phá sức mạnh và thách thức của người số 4.",
			Content:     `<h2>Số chủ đạo 4 – Người xây dựng</h2><p>Số 4 tượng trưng cho sự ổn định, kỷ luật và làm việc chăm chỉ. Người số 4 là nền tảng vững chắc trong mọi tổ chức và gia đình.</p><h3>Tính cách</h3><ul><li>Kỷ luật, có tổ chức, hệ thống</li><li>Chăm chỉ, bền bỉ, không bỏ cuộc</li><li>Trung thành, đáng tin cậy</li></ul><h3>Sự nghiệp phù hợp</h3><p>Kỹ sư, kiến trúc sư, kế toán, quản lý dự án, xây dựng, công nghệ thông tin.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Số chủ đạo 4 - Thần số học",
			MetaDescription: "Số chủ đạo 4: kỷ luật, chăm chỉ, đáng tin. Nền tảng vững chắc trong thần số học.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Số chủ đạo"},
		},
		{
			Title:       "Số chủ đạo 5: Người tự do và phiêu lưu",
			Slug:        "so-chu-dao-5-nguoi-tu-do-phieu-luu",
			Excerpt:     "Số 5 thần số học: tự do, phiêu lưu, thích thay đổi. Tính cách năng động và đa tài của người mang số 5.",
			Content:     `<h2>Số chủ đạo 5 – Người tự do</h2><p>Số 5 đại diện cho tự do, phiêu lưu và thay đổi. Người số 5 khao khát trải nghiệm, ghét sự đơn điệu và luôn tìm kiếm điều mới mẻ.</p><h3>Tính cách</h3><ul><li>Năng động, thích phiêu lưu</li><li>Linh hoạt, thích ứng nhanh</li><li>Đa tài, hiểu biết rộng</li></ul><h3>Sự nghiệp phù hợp</h3><p>Du lịch, truyền thông, sales, kinh doanh, thể thao, giải trí.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Số chủ đạo 5 - Thần số học",
			MetaDescription: "Số chủ đạo 5: tự do, phiêu lưu, đa tài. Tính cách và sự nghiệp trong thần số học.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Số chủ đạo"},
		},
		{
			Title:       "Số chủ đạo 6: Người chăm sóc và yêu thương",
			Slug:        "so-chu-dao-6-nguoi-cham-soc-yeu-thuong",
			Excerpt:     "Số 6 thần số học: yêu thương, trách nhiệm, hài hòa. Khám phá trái tim ấm áp của người mang số chủ đạo 6.",
			Content:     `<h2>Số chủ đạo 6 – Người chăm sóc</h2><p>Số 6 là con số của tình yêu, gia đình và trách nhiệm. Người số 6 có trái tim ấm áp, luôn đặt hạnh phúc gia đình lên hàng đầu.</p><h3>Tính cách</h3><ul><li>Yêu thương, chu đáo, ấm áp</li><li>Có trách nhiệm cao với gia đình</li><li>Khiếu thẩm mỹ, yêu cái đẹp</li></ul><h3>Sự nghiệp phù hợp</h3><p>Giáo viên, bác sĩ, nhà tâm lý, thiết kế nội thất, nhà hàng, chăm sóc sức khỏe.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Số chủ đạo 6 - Thần số học",
			MetaDescription: "Số chủ đạo 6: yêu thương, chăm sóc, hài hòa. Trái tim ấm áp trong thần số học.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Số chủ đạo"},
		},
		{
			Title:       "Số chủ đạo 7: Người tìm kiếm chân lý và trí tuệ",
			Slug:        "so-chu-dao-7-nguoi-tim-kiem-chan-ly",
			Excerpt:     "Số 7 thần số học: trí tuệ, tâm linh, phân tích. Hành trình tìm kiếm chân lý của người mang số chủ đạo 7.",
			Content:     `<h2>Số chủ đạo 7 – Người trí tuệ</h2><p>Số 7 là con số thiêng liêng, đại diện cho trí tuệ, tâm linh và sự tìm kiếm chân lý. Người số 7 là những nhà tư tưởng sâu sắc.</p><h3>Tính cách</h3><ul><li>Trí tuệ sắc bén, phân tích giỏi</li><li>Hướng nội, thích suy tư</li><li>Tâm linh, trực giác mạnh</li></ul><h3>Sự nghiệp phù hợp</h3><p>Nhà khoa học, triết gia, nhà nghiên cứu, chuyên gia phân tích, lập trình viên, giảng viên.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Số chủ đạo 7 - Thần số học",
			MetaDescription: "Số chủ đạo 7: trí tuệ, tâm linh, chân lý. Hành trình tìm kiếm tri thức trong thần số học.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Số chủ đạo"},
		},
		{
			Title:       "Số chủ đạo 8: Người quyền lực và thịnh vượng",
			Slug:        "so-chu-dao-8-nguoi-quyen-luc-thinh-vuong",
			Excerpt:     "Số 8 thần số học: quyền lực, tham vọng, thành công vật chất. Bí quyết thịnh vượng của người mang số 8.",
			Content:     `<h2>Số chủ đạo 8 – Người quyền lực</h2><p>Số 8 là con số của quyền lực, thịnh vượng và thành tựu vật chất. Biểu tượng vô cực (∞) nằm ngang cho thấy dòng chảy không ngừng của năng lượng.</p><h3>Tính cách</h3><ul><li>Tham vọng lớn, quyết tâm cao</li><li>Giỏi quản lý tài chính</li><li>Có tầm nhìn chiến lược</li></ul><h3>Sự nghiệp phù hợp</h3><p>Doanh nhân, tài chính, ngân hàng, bất động sản, luật sư, chính trị.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Số chủ đạo 8 - Thần số học",
			MetaDescription: "Số chủ đạo 8: quyền lực, thịnh vượng. Bí quyết thành công vật chất trong thần số học.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Số chủ đạo"},
		},
		{
			Title:       "Số chủ đạo 9: Người nhân đạo và giàu lòng trắc ẩn",
			Slug:        "so-chu-dao-9-nguoi-nhan-dao-trac-an",
			Excerpt:     "Số 9 thần số học: nhân đạo, rộng lượng, lý tưởng. Con số của sự hoàn thiện và cống hiến cho nhân loại.",
			Content:     `<h2>Số chủ đạo 9 – Người nhân đạo</h2><p>Số 9 là con số của sự hoàn thiện, lý tưởng và nhân đạo. Người số 9 mang sứ mệnh cống hiến cho cộng đồng và thế giới.</p><h3>Tính cách</h3><ul><li>Rộng lượng, từ bi, bao dung</li><li>Lý tưởng, có tầm nhìn lớn</li><li>Sáng tạo, đa tài</li></ul><h3>Sự nghiệp phù hợp</h3><p>Bác sĩ, luật sư nhân quyền, nghệ sĩ, giáo viên, tổ chức phi lợi nhuận, tâm linh.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Số chủ đạo 9 - Thần số học",
			MetaDescription: "Số chủ đạo 9: nhân đạo, rộng lượng, hoàn thiện. Sứ mệnh cống hiến trong thần số học.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Số chủ đạo"},
		},
		{
			Title:       "Số Master 11 trong thần số học: Trực giác siêu phàm và sứ mệnh tâm linh",
			Slug:        "so-master-11-truc-giac-su-menh-tam-linh",
			Excerpt:     "Số Master 11 – con số đặc biệt nhất thần số học. Trực giác siêu phàm, nhạy cảm tâm linh và sứ mệnh truyền cảm hứng.",
			Content:     `<h2>Số Master 11</h2><p>Số 11 là một trong ba "Số Master" (11, 22, 33) – những con số đặc biệt không rút gọn trong thần số học. Người mang số 11 có trực giác phi thường và sứ mệnh tâm linh.</p><h3>Đặc điểm</h3><ul><li>Trực giác cực kỳ nhạy bén</li><li>Nhạy cảm với năng lượng xung quanh</li><li>Có khả năng truyền cảm hứng mạnh mẽ</li></ul><h3>Thách thức</h3><p>Dễ bị quá tải cảm xúc, lo lắng. Cần học cách cân bằng giữa thế giới tinh thần và vật chất.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Số Master 11 - Trực giác siêu phàm",
			MetaDescription: "Số Master 11 thần số học: trực giác siêu phàm, sứ mệnh tâm linh. Con số đặc biệt nhất.",
			ReadingTime:     5,
			IsFeatured:      true,
			TagNames:        []string{"Thần số học", "Số chủ đạo", "Huyền học"},
		},
		{
			Title:       "Số Master 22 trong thần số học: Kiến trúc sư vĩ đại của cuộc đời",
			Slug:        "so-master-22-kien-truc-su-vi-dai",
			Excerpt:     "Số Master 22 – 'Master Builder'. Khả năng biến giấc mơ lớn thành hiện thực, xây dựng di sản lâu dài cho nhân loại.",
			Content:     `<h2>Số Master 22 – Master Builder</h2><p>Số 22 được gọi là "Master Builder" – kiến trúc sư vĩ đại. Đây là con số mạnh nhất trong thần số học, kết hợp trực giác của số 11 với khả năng thực hiện của số 4.</p><h3>Đặc điểm</h3><ul><li>Có tầm nhìn vĩ đại</li><li>Khả năng thực hiện những dự án lớn</li><li>Lãnh đạo và tổ chức xuất sắc</li></ul><h3>Sự nghiệp</h3><p>Thích hợp với vị trí lãnh đạo các dự án quy mô lớn, từ kinh doanh đến nhân đạo.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Số Master 22 - Kiến trúc sư vĩ đại",
			MetaDescription: "Số Master 22: Master Builder, biến giấc mơ lớn thành hiện thực trong thần số học.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Số chủ đạo", "Huyền học"},
		},
		{
			Title:       "Số Master 33 trong thần số học: Bậc thầy chữa lành và giác ngộ",
			Slug:        "so-master-33-bac-thay-chua-lanh",
			Excerpt:     "Số Master 33 – 'Master Teacher'. Con số hiếm hoi nhất, mang sứ mệnh chữa lành và nâng cao ý thức nhân loại.",
			Content:     `<h2>Số Master 33 – Master Teacher</h2><p>Số 33 là con số Master cao nhất và hiếm nhất. Người mang số 33 có sứ mệnh chữa lành, giáo dục và nâng cao nhận thức của nhân loại.</p><h3>Đặc điểm</h3><ul><li>Tình yêu vô điều kiện</li><li>Khả năng chữa lành tinh thần</li><li>Sứ mệnh phục vụ nhân loại</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Số Master 33 - Bậc thầy chữa lành",
			MetaDescription: "Số Master 33: Master Teacher, sứ mệnh chữa lành nhân loại. Con số hiếm nhất thần số học.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Số chủ đạo", "Huyền học"},
		},
		{
			Title:       "Cách tính số đường đời (Life Path Number) trong thần số học",
			Slug:        "cach-tinh-so-duong-doi-life-path",
			Excerpt:     "Hướng dẫn chi tiết cách tính số đường đời từ ngày sinh. Phương pháp đúng, sai lầm thường gặp và ví dụ cụ thể.",
			Content:     `<h2>Cách tính số đường đời</h2><p>Số đường đời (Life Path Number) là con số quan trọng nhất trong thần số học, được tính từ ngày, tháng, năm sinh.</p><h3>Phương pháp tính</h3><p><strong>Bước 1:</strong> Cộng riêng ngày, tháng, năm sinh<br><strong>Bước 2:</strong> Rút gọn từng thành phần về 1 chữ số (trừ 11, 22, 33)<br><strong>Bước 3:</strong> Cộng 3 kết quả, rút gọn lần nữa</p><h3>Ví dụ</h3><p>Ngày sinh: 29/11/1990<br>Ngày: 2+9 = 11 (giữ nguyên)<br>Tháng: 1+1 = 2<br>Năm: 1+9+9+0 = 19 → 1+0 = 1<br>Tổng: 11+2+1 = 14 → 1+4 = 5<br>→ Số đường đời: 5</p><h3>Sai lầm thường gặp</h3><ul><li>Cộng tất cả chữ số cùng lúc thay vì tách riêng ngày, tháng, năm</li><li>Rút gọn số Master (11, 22, 33)</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Cách tính số đường đời - Thần số học",
			MetaDescription: "Hướng dẫn tính số đường đời (Life Path) từ ngày sinh. Phương pháp đúng và ví dụ cụ thể.",
			ReadingTime:     5,
			IsFeatured:      true,
			TagNames:        []string{"Thần số học", "Huyền học"},
		},
		{
			Title:       "Biểu đồ ngày sinh trong thần số học: Cách vẽ và phân tích",
			Slug:        "bieu-do-ngay-sinh-than-so-hoc",
			Excerpt:     "Biểu đồ ngày sinh (Birth Chart) tiết lộ điểm mạnh, yếu và tiềm năng. Hướng dẫn vẽ và đọc biểu đồ chi tiết.",
			Content:     `<h2>Biểu đồ ngày sinh</h2><p>Biểu đồ ngày sinh (hay lưới Pythagorean) là công cụ quan trọng trong thần số học, cho thấy sự hiện diện hoặc vắng mặt của các con số từ 1-9 trong ngày sinh.</p><h3>Cách vẽ</h3><p>Lưới 3x3 với vị trí cố định cho mỗi số:<br>3 6 9<br>2 5 8<br>1 4 7</p><h3>Phân tích</h3><ul><li><strong>Số xuất hiện nhiều:</strong> Năng lượng mạnh, có thể quá dư thừa</li><li><strong>Số vắng mặt:</strong> Bài học cần học, thử thách cần vượt qua</li><li><strong>Mũi tên:</strong> Khi 3 số tạo thành đường thẳng (ngang, dọc, chéo)</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Biểu đồ ngày sinh - Thần số học",
			MetaDescription: "Biểu đồ ngày sinh thần số học: cách vẽ lưới Pythagorean, phân tích điểm mạnh yếu từ ngày sinh.",
			ReadingTime:     6,
			TagNames:        []string{"Thần số học", "Huyền học"},
		},
		{
			Title:       "Thần số học và tình yêu: Tìm người tương hợp qua các con số",
			Slug:        "than-so-hoc-tinh-yeu-tuong-hop",
			Excerpt:     "Ứng dụng thần số học trong tình yêu: bảng tương hợp các số chủ đạo, cách tìm người phù hợp và bí quyết hòa hợp.",
			Content:     `<h2>Thần số học và tình yêu</h2><p>Thần số học giúp hiểu sâu hơn về sự tương hợp trong tình yêu bằng cách so sánh số chủ đạo của hai người.</p><h3>Bảng tương hợp</h3><ul><li><strong>Rất hợp:</strong> 1-5, 2-6, 3-9, 4-8, 7-7</li><li><strong>Khá hợp:</strong> 1-3, 2-4, 5-7, 6-9, 8-2</li><li><strong>Cần nỗ lực:</strong> 1-8, 3-4, 5-6, 7-9</li></ul><h3>Không chỉ số chủ đạo</h3><p>Ngoài số chủ đạo, cần xem xét số linh hồn, số biểu đạt và số sứ mệnh để đánh giá toàn diện.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Thần số học tình yêu - Tương hợp con số",
			MetaDescription: "Thần số học tình yêu: bảng tương hợp, tìm người phù hợp qua số chủ đạo.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Tình yêu"},
		},
		{
			Title:       "Số linh hồn (Soul Urge Number): Khao khát sâu thẳm bên trong bạn",
			Slug:        "so-linh-hon-soul-urge-number",
			Excerpt:     "Số linh hồn tiết lộ khao khát thầm kín nhất. Cách tính từ nguyên âm trong tên và ý nghĩa cho từng con số.",
			Content:     `<h2>Số linh hồn – Soul Urge Number</h2><p>Số linh hồn (Soul Urge hay Heart's Desire) tiết lộ những khao khát sâu thẳm nhất trong tâm hồn bạn – những gì bạn thực sự muốn, không phải những gì bạn thể hiện ra ngoài.</p><h3>Cách tính</h3><p>Lấy tất cả nguyên âm (A, E, I, O, U) trong tên đầy đủ, chuyển thành số theo bảng Pythagorean, cộng lại và rút gọn.</p><h3>Ý nghĩa</h3><ul><li><strong>Số 1:</strong> Khao khát độc lập, dẫn đầu</li><li><strong>Số 2:</strong> Khao khát tình yêu, hòa hợp</li><li><strong>Số 3:</strong> Khao khát biểu đạt sáng tạo</li><li><strong>Số 4:</strong> Khao khát ổn định, an toàn</li><li><strong>Số 5:</strong> Khao khát tự do, trải nghiệm</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Số linh hồn Soul Urge - Thần số học",
			MetaDescription: "Số linh hồn: khao khát sâu thẳm bên trong. Cách tính từ nguyên âm và ý nghĩa từng con số.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Huyền học"},
		},
		{
			Title:       "Năm cá nhân trong thần số học: Chu kỳ 9 năm và cách tận dụng",
			Slug:        "nam-ca-nhan-than-so-hoc-chu-ky-9-nam",
			Excerpt:     "Năm cá nhân (Personal Year) là gì? Cách tính và ý nghĩa chu kỳ 9 năm trong thần số học. Biết được năm nay nên làm gì.",
			Content:     `<h2>Năm cá nhân trong thần số học</h2><p>Năm cá nhân (Personal Year) cho biết chủ đề và năng lượng chủ đạo của bạn trong một năm cụ thể. Mỗi người đều trải qua chu kỳ 9 năm lặp lại.</p><h3>Cách tính</h3><p>Cộng ngày sinh + tháng sinh + năm hiện tại, rút gọn.<br>Ví dụ: Sinh 15/8, năm 2026 → 1+5+8+2+0+2+6 = 24 → 2+4 = 6 → Năm cá nhân 6.</p><h3>Ý nghĩa từng năm</h3><ul><li><strong>Năm 1:</strong> Khởi đầu mới, gieo hạt</li><li><strong>Năm 2:</strong> Kiên nhẫn, hợp tác</li><li><strong>Năm 3:</strong> Sáng tạo, giao tiếp</li><li><strong>Năm 4:</strong> Xây dựng nền tảng</li><li><strong>Năm 5:</strong> Thay đổi, tự do</li><li><strong>Năm 6:</strong> Gia đình, trách nhiệm</li><li><strong>Năm 7:</strong> Suy tư, tâm linh</li><li><strong>Năm 8:</strong> Thu hoạch, thịnh vượng</li><li><strong>Năm 9:</strong> Kết thúc, buông bỏ</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Năm cá nhân - Chu kỳ 9 năm thần số học",
			MetaDescription: "Năm cá nhân thần số học: cách tính, chu kỳ 9 năm và ý nghĩa. Biết năm nay nên làm gì.",
			ReadingTime:     6,
			TagNames:        []string{"Thần số học", "Huyền học"},
		},
		{
			Title:       "Thần số học cho sự nghiệp: Chọn nghề phù hợp theo số chủ đạo",
			Slug:        "than-so-hoc-su-nghiep-chon-nghe-phu-hop",
			Excerpt:     "Ứng dụng thần số học để chọn nghề nghiệp phù hợp. Mỗi số chủ đạo phù hợp với lĩnh vực nào? Hướng dẫn chi tiết.",
			Content:     `<h2>Thần số học cho sự nghiệp</h2><p>Thần số học có thể giúp bạn tìm ra con đường sự nghiệp phù hợp nhất dựa trên năng lượng tự nhiên của số chủ đạo.</p><h3>Gợi ý nghề nghiệp</h3><ul><li><strong>Số 1:</strong> CEO, doanh nhân, chính trị</li><li><strong>Số 2:</strong> Tư vấn, ngoại giao, HR</li><li><strong>Số 3:</strong> Nghệ sĩ, marketing, MC</li><li><strong>Số 4:</strong> Kỹ sư, kế toán, IT</li><li><strong>Số 5:</strong> Du lịch, truyền thông, sales</li><li><strong>Số 6:</strong> Giáo viên, bác sĩ, thiết kế</li><li><strong>Số 7:</strong> Nhà khoa học, triết gia, lập trình</li><li><strong>Số 8:</strong> Tài chính, ngân hàng, luật</li><li><strong>Số 9:</strong> Nhân đạo, nghệ thuật, giáo dục</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Thần số học sự nghiệp - Chọn nghề theo số chủ đạo",
			MetaDescription: "Thần số học cho sự nghiệp: chọn nghề phù hợp theo số chủ đạo. Gợi ý chi tiết từng con số.",
			ReadingTime:     5,
			TagNames:        []string{"Thần số học", "Sự nghiệp"},
		},
	}

	return createSeedArticles(db, seeds, tagMap, authorID)
}
