package main

import (
	"fmt"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

func seedNhanVatArticles(db *gorm.DB, tagMap map[string]uuid.UUID, authorID *uuid.UUID) int {
	fmt.Println("\n   👤 Seeding Nhân Vật Lịch Sử articles...")

	seeds := []ArticleSeed{
		// === VUA CHÚA & HOÀNG ĐẾ ===
		{
			Title:           "Vua Lý Thái Tổ: Người sáng lập triều Lý và dời đô về Thăng Long",
			Slug:            "vua-ly-thai-to-sang-lap-trieu-ly",
			Excerpt:         "Tìm hiểu về Lý Thái Tổ – vị vua sáng lập triều Lý, người có công dời đô từ Hoa Lư về Đại La (Thăng Long), mở ra kỷ nguyên phát triển rực rỡ.",
			Content:         `<h2>Lý Thái Tổ – Người dời đô về Thăng Long</h2><p>Lý Thái Tổ (tên thật Lý Công Uẩn, 974-1028) là vị hoàng đế sáng lập nhà Lý, một trong những triều đại huy hoàng nhất lịch sử Việt Nam. Ông sinh ra ở Bắc Ninh, được sư Vạn Hạnh nuôi dạy từ nhỏ.</p><h3>Cuộc đời và sự nghiệp</h3><p>Lý Công Uẩn lớn lên trong chùa, được giáo dục toàn diện. Khi nhà Lê suy yếu, ông được triều thần tôn lên ngôi vua năm 1009, lập ra nhà Lý.</p><h3>Chiếu dời đô</h3><p>Năm 1010, Lý Thái Tổ ban bố Chiếu dời đô – một văn kiện lịch sử quan trọng. Ông nhận thấy Đại La (Hà Nội ngày nay) là vùng đất "rồng cuộn hổ ngồi", thuận lợi cho việc xây dựng kinh đô.</p><h3>Di sản</h3><ul><li>Sáng lập triều Lý kéo dài 216 năm</li><li>Dời đô về Thăng Long, nền tảng cho Hà Nội ngày nay</li><li>Xây dựng nền tảng cho nhà nước phong kiến tập quyền</li></ul>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Vua Lý Thái Tổ - Sáng lập triều Lý, dời đô Thăng Long",
			MetaDescription: "Lý Thái Tổ - vị vua sáng lập triều Lý, người dời đô về Thăng Long năm 1010. Tiểu sử, sự nghiệp và di sản.",
			ReadingTime:     6,
			IsFeatured:      true,
			TagNames:        []string{"Nhân vật lịch sử", "Triều đại Việt Nam", "Vua chúa"},
		},
		{
			Title:           "Vua Lê Thánh Tông: Minh quân vĩ đại nhất lịch sử Việt Nam",
			Slug:            "vua-le-thanh-tong-minh-quan-vi-dai",
			Excerpt:         "Lê Thánh Tông được xem là vị minh quân vĩ đại nhất sử Việt. Tìm hiểu về cuộc đời, cải cách và di sản văn hóa của ông.",
			Content:         `<h2>Lê Thánh Tông – Vị vua anh minh</h2><p>Lê Thánh Tông (1442-1497) trị vì từ 1460 đến 1497, là giai đoạn thịnh trị nhất của nhà Lê sơ. Dưới thời ông, Đại Việt đạt đỉnh cao về mọi mặt.</p><h3>Cải cách hành chính</h3><p>Ông chia nước thành 13 đạo, xây dựng hệ thống quan lại chặt chẽ. Bộ luật Hồng Đức được ban hành, trở thành bộ luật tiến bộ nhất Đông Nam Á thời bấy giờ.</p><h3>Văn hóa – Giáo dục</h3><p>Lê Thánh Tông sáng lập Hội Tao Đàn, thúc đẩy văn chương. Ông cũng mở rộng hệ thống khoa cử, đào tạo nhân tài cho đất nước.</p><h3>Di sản</h3><ul><li>Bộ luật Hồng Đức – bộ luật thành văn hoàn chỉnh nhất</li><li>Lãnh thổ Đại Việt mở rộng nhất</li><li>Đỉnh cao văn hóa – giáo dục phong kiến</li></ul>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Vua Lê Thánh Tông - Minh quân vĩ đại nhất Việt Nam",
			MetaDescription: "Lê Thánh Tông - minh quân vĩ đại nhất: cải cách Hồng Đức, Hội Tao Đàn, mở rộng lãnh thổ Đại Việt.",
			ReadingTime:     7,
			IsFeatured:      true,
			TagNames:        []string{"Nhân vật lịch sử", "Triều đại Việt Nam", "Vua chúa"},
		},
		{
			Title:           "Vua Quang Trung – Nguyễn Huệ: Thiên tài quân sự lẫy lừng",
			Slug:            "vua-quang-trung-nguyen-hue-thien-tai-quan-su",
			Excerpt:         "Quang Trung Nguyễn Huệ – vị hoàng đế với tài dụng binh xuất chúng, đánh tan 29 vạn quân Thanh trong vỏn vẹn 5 ngày Tết Kỷ Dậu.",
			Content:         `<h2>Quang Trung – Nguyễn Huệ</h2><p>Nguyễn Huệ (1753-1792) là anh hùng dân tộc, vị hoàng đế sáng lập nhà Tây Sơn. Ông nổi tiếng với tài dụng binh như thần và tầm nhìn cải cách đất nước.</p><h3>Chiến công hiển hách</h3><p>Chiến thắng Rạch Gầm – Xoài Mút (1785) đánh tan 5 vạn quân Xiêm. Đại thắng Ngọc Hồi – Đống Đa (1789) tiêu diệt 29 vạn quân Thanh chỉ trong 5 ngày xuân Kỷ Dậu.</p><h3>Cải cách</h3><ul><li>Ban bố Chiếu lập học, đề cao chữ Nôm</li><li>Cải cách hành chính, thuế khóa</li><li>Khuyến khích khai hoang, phát triển nông nghiệp</li></ul><h3>Đánh giá</h3><p>Quang Trung được xem là một trong những thiên tài quân sự vĩ đại nhất lịch sử Việt Nam, sánh ngang với Napoléon của phương Tây.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Quang Trung Nguyễn Huệ - Thiên tài quân sự Việt Nam",
			MetaDescription: "Quang Trung Nguyễn Huệ: thiên tài quân sự đánh tan 29 vạn quân Thanh, cải cách đất nước. Tiểu sử chi tiết.",
			ReadingTime:     7,
			IsFeatured:      true,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc", "Vua chúa"},
		},
		{
			Title:           "Trần Hưng Đạo: Đại danh tướng ba lần đánh bại Nguyên Mông",
			Slug:            "tran-hung-dao-dai-danh-tuong",
			Excerpt:         "Hưng Đạo Đại Vương Trần Quốc Tuấn – vị tướng tài ba nhất lịch sử Việt Nam, ba lần đánh bại đế quốc Nguyên Mông hùng mạnh.",
			Content:         `<h2>Trần Hưng Đạo – Đại danh tướng</h2><p>Trần Quốc Tuấn (1228-1300), hiệu Hưng Đạo Đại Vương, là danh tướng kiệt xuất thời nhà Trần. Ông được nhân dân tôn sùng như một vị thánh.</p><h3>Ba lần đánh bại Nguyên Mông</h3><p>Đế quốc Nguyên Mông – lực lượng quân sự mạnh nhất thế giới lúc bấy giờ – đã ba lần xâm lược Đại Việt (1258, 1285, 1288) và cả ba lần đều thảm bại dưới tay Trần Hưng Đạo.</p><h3>Hịch tướng sĩ</h3><p>Bài Hịch tướng sĩ của ông là áng văn bất hủ, thể hiện tinh thần yêu nước và quyết tâm bảo vệ tổ quốc.</p><h3>Binh pháp</h3><p>Trần Hưng Đạo soạn "Vạn Kiếp tông bí truyền thư" – cuốn binh pháp nổi tiếng của Việt Nam.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Trần Hưng Đạo - 3 lần đánh bại Nguyên Mông",
			MetaDescription: "Trần Hưng Đạo - danh tướng kiệt xuất ba lần đánh thắng Nguyên Mông. Hịch tướng sĩ và binh pháp Việt Nam.",
			ReadingTime:     7,
			IsFeatured:      true,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc", "Danh tướng"},
		},
		{
			Title:       "Lý Thường Kiệt: Tướng quân tiên phát chế nhân, tác giả Nam quốc sơn hà",
			Slug:        "ly-thuong-kiet-tien-phat-che-nhan",
			Excerpt:     "Lý Thường Kiệt – danh tướng với chiến lược 'tiên phát chế nhân', chủ động tấn công Ung Châu và bài thơ thần Nam quốc sơn hà.",
			Content:     `<h2>Lý Thường Kiệt – Danh tướng thời Lý</h2><p>Lý Thường Kiệt (1019-1105) là danh tướng xuất chúng thời nhà Lý. Ông nổi tiếng với chiến lược "tiên phát chế nhân" – chủ động tấn công trước để phòng thủ.</p><h3>Chiến dịch tấn công Ung Châu</h3><p>Năm 1075, ông dẫn quân đánh sang lãnh thổ nhà Tống, phá hủy các kho quân lương tại Ung Châu, Khâm Châu, Liêm Châu.</p><h3>Phòng tuyến sông Như Nguyệt</h3><p>Năm 1077, ông xây dựng phòng tuyến sông Như Nguyệt đánh bại 30 vạn quân Tống xâm lược.</p><h3>Nam quốc sơn hà</h3><p>Bài thơ thần "Nam quốc sơn hà" được coi là bản tuyên ngôn độc lập đầu tiên của Việt Nam.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Lý Thường Kiệt - Tiên phát chế nhân",
			MetaDescription: "Lý Thường Kiệt: chiến lược tiên phát chế nhân, phòng tuyến Như Nguyệt, bài thơ Nam quốc sơn hà.",
			ReadingTime:     6,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc", "Danh tướng"},
		},
		{
			Title:       "Ngô Quyền và chiến thắng Bạch Đằng 938: Chấm dứt 1000 năm Bắc thuộc",
			Slug:        "ngo-quyen-chien-thang-bach-dang-938",
			Excerpt:     "Ngô Quyền với trận Bạch Đằng lịch sử năm 938, sử dụng cọc nhọn tiêu diệt quân Nam Hán, chấm dứt hơn 1000 năm Bắc thuộc.",
			Content:     `<h2>Ngô Quyền – Người khai sinh nền độc lập</h2><p>Ngô Quyền (897-944) là vị anh hùng đã chấm dứt hơn 1000 năm Bắc thuộc bằng chiến thắng Bạch Đằng vang dội năm 938.</p><h3>Trận Bạch Đằng 938</h3><p>Ông sử dụng kế cắm cọc nhọn dưới lòng sông, lợi dụng thủy triều để tiêu diệt hoàn toàn đoàn chiến thuyền của Nam Hán. Tướng địch Lưu Hoằng Tháo bị giết tại trận.</p><h3>Di sản</h3><p>Chiến thắng Bạch Đằng 938 mở ra kỷ nguyên độc lập tự chủ cho dân tộc Việt Nam, kéo dài suốt hơn 1000 năm sau đó.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Ngô Quyền - Chiến thắng Bạch Đằng 938",
			MetaDescription: "Ngô Quyền và trận Bạch Đằng 938: chấm dứt 1000 năm Bắc thuộc, khai sinh nền độc lập Việt Nam.",
			ReadingTime:     6,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc"},
		},
		{
			Title:       "Hai Bà Trưng: Nữ anh hùng đầu tiên trong lịch sử Việt Nam",
			Slug:        "hai-ba-trung-nu-anh-hung-dau-tien",
			Excerpt:     "Trưng Trắc và Trưng Nhị – hai nữ anh hùng đầu tiên khởi nghĩa chống giặc Hán, lập nên nhà nước độc lập ngắn ngủi nhưng vẻ vang.",
			Content:     `<h2>Hai Bà Trưng – Biểu tượng nữ quyền Việt Nam</h2><p>Trưng Trắc và Trưng Nhị là hai chị em sinh đôi ở Mê Linh, khởi nghĩa chống quân Đông Hán năm 40 sau Công nguyên.</p><h3>Cuộc khởi nghĩa</h3><p>Năm 40, Hai Bà Trưng phất cờ khởi nghĩa, nhanh chóng đánh chiếm 65 thành. Trưng Trắc xưng vương, đóng đô ở Mê Linh.</p><h3>Ý nghĩa lịch sử</h3><ul><li>Cuộc khởi nghĩa chống ngoại xâm đầu tiên do phụ nữ lãnh đạo</li><li>Thể hiện tinh thần bất khuất của dân tộc Việt</li><li>Nguồn cảm hứng cho phong trào đấu tranh giải phóng</li></ul>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Hai Bà Trưng - Nữ anh hùng đầu tiên Việt Nam",
			MetaDescription: "Hai Bà Trưng: nữ anh hùng khởi nghĩa chống Hán năm 40, biểu tượng nữ quyền lịch sử Việt Nam.",
			ReadingTime:     6,
			IsFeatured:      true,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc"},
		},
		{
			Title:       "Lê Lợi và khởi nghĩa Lam Sơn: 10 năm kháng chiến đánh đuổi quân Minh",
			Slug:        "le-loi-khoi-nghia-lam-son",
			Excerpt:     "Lê Lợi – người anh hùng áo vải khởi nghĩa Lam Sơn, 10 năm gian khổ đánh đuổi quân Minh, giành lại độc lập cho dân tộc.",
			Content:     `<h2>Lê Lợi – Bình Định Vương</h2><p>Lê Lợi (1385-1433) là người khởi xướng cuộc khởi nghĩa Lam Sơn (1418-1427), đánh đuổi quân Minh xâm lược, sáng lập nhà Hậu Lê.</p><h3>10 năm kháng chiến</h3><p>Từ năm 1418, Lê Lợi dựng cờ khởi nghĩa tại Lam Sơn (Thanh Hóa). Trải qua 10 năm gian khổ, nhiều lần suýt bị bắt, ông kiên trì đấu tranh.</p><h3>Chiến thắng Chi Lăng – Xương Giang</h3><p>Năm 1427, trận Chi Lăng – Xương Giang quyết định, tiêu diệt 10 vạn quân Minh viện binh, buộc địch phải đầu hàng.</p><h3>Di sản</h3><p>Sau khi thắng lợi, Lê Lợi lên ngôi, mở ra triều đại Hậu Lê kéo dài hơn 350 năm – triều đại dài nhất trong lịch sử Việt Nam.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Lê Lợi - Khởi nghĩa Lam Sơn đánh đuổi quân Minh",
			MetaDescription: "Lê Lợi và 10 năm khởi nghĩa Lam Sơn: đánh đuổi quân Minh, sáng lập nhà Hậu Lê. Tiểu sử và chiến công.",
			ReadingTime:     7,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc", "Triều đại Việt Nam"},
		},
		// === DANH NHÂN VĂN HÓA ===
		{
			Title:       "Nguyễn Du: Đại thi hào dân tộc và kiệt tác Truyện Kiều",
			Slug:        "nguyen-du-dai-thi-hao-truyen-kieu",
			Excerpt:     "Nguyễn Du – đại thi hào dân tộc, tác giả Truyện Kiều bất hủ. Cuộc đời, sự nghiệp và di sản văn học vĩ đại.",
			Content:     `<h2>Nguyễn Du – Đại thi hào</h2><p>Nguyễn Du (1765-1820) là đại thi hào dân tộc Việt Nam, được UNESCO công nhận là Danh nhân văn hóa thế giới. Kiệt tác "Truyện Kiều" của ông là niềm tự hào của văn học Việt Nam.</p><h3>Cuộc đời</h3><p>Sinh ra trong gia đình đại quý tộc ở Hà Tĩnh, Nguyễn Du trải qua cuộc đời nhiều biến cố với sự sụp đổ của nhà Lê và sự trỗi dậy của nhà Nguyễn.</p><h3>Truyện Kiều</h3><p>Truyện Kiều (Đoạn trường tân thanh) gồm 3.254 câu thơ lục bát, kể về cuộc đời nàng Kiều – một thiếu nữ tài sắc vẹn toàn nhưng bạc mệnh. Tác phẩm phản ánh xã hội phong kiến bất công và ca ngợi phẩm giá con người.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Nguyễn Du - Đại thi hào và Truyện Kiều",
			MetaDescription: "Nguyễn Du: đại thi hào dân tộc, tác giả Truyện Kiều. Cuộc đời, sự nghiệp và di sản văn hóa thế giới.",
			ReadingTime:     6,
			IsFeatured:      true,
			TagNames:        []string{"Nhân vật lịch sử", "Danh nhân văn hóa"},
		},
		{
			Title:       "Nguyễn Trãi: Anh hùng dân tộc, danh nhân văn hóa thế giới",
			Slug:        "nguyen-trai-anh-hung-danh-nhan-van-hoa",
			Excerpt:     "Nguyễn Trãi – người viết Bình Ngô đại cáo, cánh tay phải của Lê Lợi. Cuộc đời bi tráng và di sản bất diệt.",
			Content:     `<h2>Nguyễn Trãi – Anh hùng và danh nhân</h2><p>Nguyễn Trãi (1380-1442) là anh hùng dân tộc kiêm danh nhân văn hóa thế giới (UNESCO). Ông là mưu sĩ tài ba giúp Lê Lợi đánh đuổi quân Minh và tác giả Bình Ngô đại cáo.</p><h3>Bình Ngô đại cáo</h3><p>Được xem là bản Tuyên ngôn Độc lập thứ hai của Việt Nam, khẳng định chủ quyền dân tộc và nền văn hiến lâu đời.</p><h3>Cuộc đời bi kịch</h3><p>Dù có công lớn, Nguyễn Trãi bị oan án "tru di tam tộc" năm 1442. Mãi đến năm 1464, vua Lê Thánh Tông mới minh oan cho ông.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Nguyễn Trãi - Anh hùng và danh nhân văn hóa",
			MetaDescription: "Nguyễn Trãi: anh hùng dân tộc, tác giả Bình Ngô đại cáo, danh nhân văn hóa thế giới UNESCO.",
			ReadingTime:     6,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc", "Danh nhân văn hóa"},
		},
		{
			Title:       "Hồ Xuân Hương: Bà chúa thơ Nôm và tinh thần nữ quyền",
			Slug:        "ho-xuan-huong-ba-chua-tho-nom",
			Excerpt:     "Hồ Xuân Hương – Bà chúa thơ Nôm với lối thơ trào phúng, đậm chất dân gian và tinh thần nữ quyền đi trước thời đại.",
			Content:     `<h2>Hồ Xuân Hương – Bà chúa thơ Nôm</h2><p>Hồ Xuân Hương (khoảng 1772-1822) là nữ thi sĩ nổi tiếng nhất trong lịch sử văn học Việt Nam. Thơ bà vừa trào phúng, vừa trữ tình, phản ánh số phận người phụ nữ trong xã hội phong kiến.</p><h3>Phong cách thơ</h3><p>Thơ Hồ Xuân Hương nổi bật với nghệ thuật chơi chữ tài tình, hình ảnh đa nghĩa và giọng thơ mạnh mẽ, phá cách. Bà sử dụng chữ Nôm thuần Việt, gần gũi với ngôn ngữ dân gian.</p><h3>Tác phẩm tiêu biểu</h3><ul><li>Bánh trôi nước</li><li>Thiếu nữ ngủ ngày</li><li>Đánh đu</li><li>Tự tình</li></ul>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Hồ Xuân Hương - Bà chúa thơ Nôm",
			MetaDescription: "Hồ Xuân Hương: Bà chúa thơ Nôm, tinh thần nữ quyền. Cuộc đời và tác phẩm tiêu biểu.",
			ReadingTime:     5,
			TagNames:        []string{"Nhân vật lịch sử", "Danh nhân văn hóa"},
		},
		{
			Title:       "Nguyễn Bỉnh Khiêm: Trạng Trình và những lời sấm truyền bí ẩn",
			Slug:        "nguyen-binh-khiem-trang-trinh-sam-truyen",
			Excerpt:     "Nguyễn Bỉnh Khiêm (Trạng Trình) – nhà tiên tri lỗi lạc với Sấm Trạng Trình, nhà thơ lớn và bậc hiền triết thời Mạc.",
			Content:     `<h2>Nguyễn Bỉnh Khiêm – Trạng Trình</h2><p>Nguyễn Bỉnh Khiêm (1491-1585), hiệu Bạch Vân cư sĩ, là Trạng nguyên thời nhà Mạc. Ông nổi tiếng với tài tiên tri và những lời Sấm Trạng Trình.</p><h3>Sấm Trạng Trình</h3><p>Những lời sấm truyền của ông dự đoán nhiều biến cố lịch sử của Việt Nam và thế giới. Dù tính xác thực còn tranh luận, Sấm Trạng Trình vẫn là hiện tượng văn hóa độc đáo.</p><h3>Triết lý sống</h3><p>Ông chủ trương "nhàn" – sống thanh thản, hòa hợp thiên nhiên. Thơ ông phản ánh trí tuệ sâu sắc và nhân sinh quan thoáng đạt.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Nguyễn Bỉnh Khiêm - Trạng Trình và Sấm truyền",
			MetaDescription: "Nguyễn Bỉnh Khiêm: Trạng Trình, nhà tiên tri với Sấm Trạng Trình. Cuộc đời và triết lý sống.",
			ReadingTime:     6,
			TagNames:        []string{"Nhân vật lịch sử", "Danh nhân văn hóa"},
		},
		// === NHÂN VẬT CẬN - HIỆN ĐẠI ===
		{
			Title:       "Chủ tịch Hồ Chí Minh: Cuộc đời và sự nghiệp vĩ đại",
			Slug:        "ho-chi-minh-cuoc-doi-su-nghiep",
			Excerpt:     "Hồ Chí Minh – vị lãnh tụ kính yêu, anh hùng giải phóng dân tộc, danh nhân văn hóa thế giới. Tìm hiểu cuộc đời và di sản.",
			Content:     `<h2>Chủ tịch Hồ Chí Minh</h2><p>Hồ Chí Minh (1890-1969) là nhà cách mạng vĩ đại, anh hùng giải phóng dân tộc và danh nhân văn hóa kiệt xuất (UNESCO). Ông là người sáng lập nước Việt Nam Dân chủ Cộng hòa.</p><h3>Hành trình tìm đường cứu nước</h3><p>Năm 1911, Nguyễn Tất Thành ra đi từ bến Nhà Rồng, bôn ba qua 30 nước trong 30 năm để tìm đường giải phóng dân tộc.</p><h3>Tuyên ngôn Độc lập</h3><p>Ngày 2/9/1945, tại Quảng trường Ba Đình, Hồ Chí Minh đọc bản Tuyên ngôn Độc lập, khai sinh nước Việt Nam Dân chủ Cộng hòa.</p><h3>Di sản</h3><ul><li>Tư tưởng Hồ Chí Minh về giải phóng dân tộc</li><li>Phong cách sống giản dị, đạo đức cách mạng</li><li>Di chúc để lại cho thế hệ sau</li></ul>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Hồ Chí Minh - Cuộc đời và sự nghiệp",
			MetaDescription: "Hồ Chí Minh: anh hùng giải phóng dân tộc, danh nhân văn hóa thế giới. Cuộc đời, sự nghiệp và di sản.",
			ReadingTime:     7,
			IsFeatured:      true,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc", "Danh nhân văn hóa"},
		},
		{
			Title:       "Võ Nguyên Giáp: Đại tướng của nhân dân, huyền thoại Điện Biên Phủ",
			Slug:        "vo-nguyen-giap-dai-tuong-dien-bien-phu",
			Excerpt:     "Đại tướng Võ Nguyên Giáp – vị tướng tài ba nhất thế kỷ 20, người chỉ huy chiến dịch Điện Biên Phủ lừng lẫy năm châu.",
			Content:     `<h2>Đại tướng Võ Nguyên Giáp</h2><p>Võ Nguyên Giáp (1911-2013) là Đại tướng đầu tiên của Quân đội Nhân dân Việt Nam. Ông được quốc tế đánh giá là một trong những vị tướng vĩ đại nhất thế kỷ 20.</p><h3>Chiến thắng Điện Biên Phủ</h3><p>Năm 1954, Đại tướng chỉ huy chiến dịch Điện Biên Phủ – trận đánh "chấn động địa cầu" – đánh bại quân Pháp tại tập đoàn cứ điểm Điện Biên Phủ.</p><h3>Tầm nhìn chiến lược</h3><p>Quyết định thay đổi phương châm từ "đánh nhanh thắng nhanh" sang "đánh chắc tiến chắc" là bước ngoặt dẫn đến chiến thắng.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Võ Nguyên Giáp - Huyền thoại Điện Biên Phủ",
			MetaDescription: "Đại tướng Võ Nguyên Giáp: vị tướng vĩ đại, chiến thắng Điện Biên Phủ lừng lẫy năm châu.",
			ReadingTime:     6,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc", "Danh tướng"},
		},
		{
			Title:       "Phan Bội Châu: Nhà yêu nước tiên phong của phong trào Đông Du",
			Slug:        "phan-boi-chau-phong-trao-dong-du",
			Excerpt:     "Phan Bội Châu – chí sĩ cách mạng, người khởi xướng phong trào Đông Du, đưa thanh niên Việt sang Nhật Bản du học cứu nước.",
			Content:     `<h2>Phan Bội Châu – Chí sĩ yêu nước</h2><p>Phan Bội Châu (1867-1940) là nhà cách mạng tiêu biểu đầu thế kỷ 20. Ông khởi xướng phong trào Đông Du (1905-1908), đưa hơn 200 thanh niên Việt sang Nhật Bản học tập.</p><h3>Phong trào Đông Du</h3><p>Với khẩu hiệu "cầu ngoại viện, mưu khôi phục", Phan Bội Châu tìm kiếm sự giúp đỡ của Nhật Bản để giải phóng dân tộc. Dù phong trào thất bại, nó đã đánh thức tinh thần yêu nước.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Phan Bội Châu - Phong trào Đông Du",
			MetaDescription: "Phan Bội Châu: nhà yêu nước, phong trào Đông Du. Cuộc đời và đóng góp cho cách mạng Việt Nam.",
			ReadingTime:     5,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc"},
		},
		{
			Title:       "Lê Văn Hưu: Cha đẻ nền sử học Việt Nam",
			Slug:        "le-van-huu-cha-de-su-hoc-viet-nam",
			Excerpt:     "Lê Văn Hưu – sử gia đầu tiên của Việt Nam, tác giả Đại Việt sử ký, đặt nền móng cho ngành sử học dân tộc.",
			Content:     `<h2>Lê Văn Hưu – Sử gia tiên phong</h2><p>Lê Văn Hưu (1230-1322) là nhà sử học đầu tiên của Việt Nam. Ông biên soạn Đại Việt sử ký – bộ quốc sử đầu tiên ghi chép lịch sử dân tộc một cách hệ thống.</p><h3>Đại Việt sử ký</h3><p>Hoàn thành năm 1272 dưới triều Trần, bộ sử ghi chép từ thời Triệu Vũ Đế đến Lý Chiêu Hoàng. Đây là nền tảng để Ngô Sĩ Liên biên soạn Đại Việt sử ký toàn thư sau này.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Lê Văn Hưu - Cha đẻ sử học Việt Nam",
			MetaDescription: "Lê Văn Hưu: sử gia đầu tiên, tác giả Đại Việt sử ký. Đặt nền móng cho ngành sử học Việt Nam.",
			ReadingTime:     5,
			TagNames:        []string{"Nhân vật lịch sử", "Danh nhân văn hóa"},
		},
		{
			Title:       "Bà Triệu (Triệu Thị Trinh): Nữ tướng cưỡi voi đánh giặc",
			Slug:        "ba-trieu-nu-tuong-cuoi-voi",
			Excerpt:     "Bà Triệu – nữ tướng anh hùng với câu nói nổi tiếng: 'Tôi muốn cưỡi cơn gió mạnh, đạp luồng sóng dữ, chém cá kình ở biển Đông'.",
			Content:     `<h2>Bà Triệu – Nữ tướng anh hùng</h2><p>Triệu Thị Trinh (225-248) hay còn gọi là Bà Triệu, là nữ anh hùng khởi nghĩa chống nhà Ngô (Trung Quốc) năm 248.</p><h3>Khởi nghĩa Bà Triệu</h3><p>Năm 248, Bà Triệu cùng anh trai Triệu Quốc Đạt dấy binh ở Thanh Hóa. Bà cưỡi voi ra trận, khiến quân địch khiếp sợ. Quân Ngô phải huy động đại quân mới dẹp được.</p><h3>Di sản</h3><p>Tinh thần "cưỡi cơn gió mạnh" của Bà Triệu trở thành biểu tượng bất khuất của phụ nữ Việt Nam.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Bà Triệu - Nữ tướng cưỡi voi đánh giặc",
			MetaDescription: "Bà Triệu: nữ tướng cưỡi voi đánh quân Ngô, biểu tượng bất khuất của phụ nữ Việt Nam.",
			ReadingTime:     5,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc"},
		},
		{
			Title:       "Trần Nhân Tông: Vua Phật, người sáng lập Thiền phái Trúc Lâm",
			Slug:        "tran-nhan-tong-vua-phat-thien-phai-truc-lam",
			Excerpt:     "Trần Nhân Tông – vị vua lãnh đạo kháng chiến chống Nguyên Mông rồi từ bỏ ngai vàng, sáng lập Thiền phái Trúc Lâm Yên Tử.",
			Content:     `<h2>Trần Nhân Tông – Vua Phật</h2><p>Trần Nhân Tông (1258-1308) là vị vua thứ ba nhà Trần, cũng là vị Phật hoàng duy nhất trong lịch sử Việt Nam.</p><h3>Kháng chiến chống Nguyên Mông</h3><p>Ông lãnh đạo cuộc kháng chiến chống Nguyên Mông lần 2 (1285) và lần 3 (1288) thắng lợi. Hội nghị Diên Hồng do ông triệu tập thể hiện tinh thần đoàn kết toàn dân.</p><h3>Thiền phái Trúc Lâm</h3><p>Sau khi nhường ngôi, ông lên núi Yên Tử tu hành và sáng lập Thiền phái Trúc Lâm Yên Tử – thiền phái mang đậm bản sắc Việt Nam.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Trần Nhân Tông - Vua Phật, Thiền phái Trúc Lâm",
			MetaDescription: "Trần Nhân Tông: vua Phật chống Nguyên Mông, sáng lập Thiền phái Trúc Lâm Yên Tử.",
			ReadingTime:     6,
			TagNames:        []string{"Nhân vật lịch sử", "Vua chúa", "Danh nhân văn hóa"},
		},
		{
			Title:       "Nguyễn Trung Trực: Anh hùng kháng Pháp với câu nói bất hủ",
			Slug:        "nguyen-trung-truc-anh-hung-khang-phap",
			Excerpt:     "Nguyễn Trung Trực – người anh hùng đốt cháy tàu Espérance với câu nói: 'Bao giờ người Tây nhổ hết cỏ nước Nam thì mới hết người Nam đánh Tây'.",
			Content:     `<h2>Nguyễn Trung Trực</h2><p>Nguyễn Trung Trực (1838-1868) là anh hùng kháng Pháp nổi tiếng ở Nam Bộ. Ông đốt cháy tàu chiến Espérance trên sông Nhật Tảo năm 1861.</p><h3>Chiến công</h3><ul><li>Đốt tàu Espérance – chiến công đầu tiên đánh chìm tàu chiến Pháp</li><li>Đánh chiếm đồn Rạch Giá năm 1868</li></ul><h3>Câu nói bất hủ</h3><p>Trước khi bị xử tử, ông nói: "Bao giờ người Tây nhổ hết cỏ nước Nam, thì mới hết người Nam đánh Tây" – thể hiện ý chí bất khuất.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Nguyễn Trung Trực - Anh hùng kháng Pháp",
			MetaDescription: "Nguyễn Trung Trực: đốt tàu Espérance, anh hùng kháng Pháp với câu nói bất hủ.",
			ReadingTime:     5,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc"},
		},
		{
			Title:       "Lý Chiêu Hoàng: Nữ hoàng đế duy nhất trong lịch sử Việt Nam",
			Slug:        "ly-chieu-hoang-nu-hoang-de-duy-nhat",
			Excerpt:     "Lý Chiêu Hoàng – vị nữ hoàng đế đầu tiên và duy nhất của Việt Nam, người nhường ngôi cho chồng Trần Cảnh, kết thúc triều Lý.",
			Content:     `<h2>Lý Chiêu Hoàng – Nữ hoàng đế duy nhất</h2><p>Lý Chiêu Hoàng (1218-1278) là vị nữ hoàng đế đầu tiên và duy nhất trong lịch sử phong kiến Việt Nam. Bà lên ngôi lúc 6 tuổi, là vua cuối cùng của nhà Lý.</p><h3>Sự chuyển giao quyền lực</h3><p>Năm 1225, dưới sự sắp xếp của Trần Thủ Độ, Lý Chiêu Hoàng nhường ngôi cho chồng là Trần Cảnh (Trần Thái Tông), mở ra triều đại nhà Trần.</p><h3>Cuộc đời sau này</h3><p>Cuộc đời Lý Chiêu Hoàng là bi kịch của chính trị, khi bà trở thành công cụ trong cuộc chuyển giao quyền lực giữa hai triều đại.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Lý Chiêu Hoàng - Nữ hoàng đế duy nhất Việt Nam",
			MetaDescription: "Lý Chiêu Hoàng: nữ hoàng đế duy nhất lịch sử Việt Nam, câu chuyện chuyển giao nhà Lý sang nhà Trần.",
			ReadingTime:     5,
			TagNames:        []string{"Nhân vật lịch sử", "Vua chúa"},
		},
		{
			Title:       "Trương Định: Bình Tây Đại Nguyên Soái chống Pháp ở Nam Bộ",
			Slug:        "truong-dinh-binh-tay-dai-nguyen-soai",
			Excerpt:     "Trương Định – Bình Tây Đại Nguyên Soái, thủ lĩnh phong trào kháng Pháp ở Nam Bộ, người được nhân dân tôn phong vì lòng yêu nước.",
			Content:     `<h2>Trương Định – Bình Tây Đại Nguyên Soái</h2><p>Trương Định (1820-1864) là thủ lĩnh phong trào kháng Pháp ở Nam Kỳ. Ông được nhân dân tôn phong là Bình Tây Đại Nguyên Soái.</p><h3>Kháng chiến chống Pháp</h3><p>Khi triều đình Huế ký Hòa ước Nhâm Tuất nhường đất cho Pháp, Trương Định không tuân lệnh triều đình mà tiếp tục chiến đấu vì nhân dân.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Trương Định - Bình Tây Đại Nguyên Soái",
			MetaDescription: "Trương Định: Bình Tây Đại Nguyên Soái, thủ lĩnh kháng Pháp ở Nam Bộ.",
			ReadingTime:     5,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc"},
		},
		{
			Title:       "Đinh Bộ Lĩnh: Vạn Thắng Vương thống nhất 12 sứ quân",
			Slug:        "dinh-bo-linh-van-thang-vuong",
			Excerpt:     "Đinh Bộ Lĩnh – từ cậu bé chăn trâu đến Vạn Thắng Vương, người thống nhất 12 sứ quân, sáng lập nhà Đinh và nước Đại Cồ Việt.",
			Content:     `<h2>Đinh Bộ Lĩnh – Vạn Thắng Vương</h2><p>Đinh Bộ Lĩnh (924-979) là người thống nhất đất nước sau thời loạn 12 sứ quân, sáng lập nhà Đinh và đặt tên nước là Đại Cồ Việt.</p><h3>Tuổi thơ</h3><p>Sinh tại Ninh Bình, từ nhỏ đã nổi tiếng thông minh. Ông thường chơi trò cầm hoa lau tập trận với trẻ con trong làng, thể hiện tài lãnh đạo từ bé.</p><h3>Dẹp loạn 12 sứ quân</h3><p>Trong hơn 20 năm, ông lần lượt đánh dẹp 12 sứ quân, thống nhất đất nước. Ông xưng là Vạn Thắng Vương rồi lên ngôi Hoàng đế, đóng đô ở Hoa Lư.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Đinh Bộ Lĩnh - Vạn Thắng Vương thống nhất 12 sứ quân",
			MetaDescription: "Đinh Bộ Lĩnh: thống nhất 12 sứ quân, sáng lập nhà Đinh, nước Đại Cồ Việt.",
			ReadingTime:     5,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc", "Vua chúa"},
		},
		{
			Title:       "Lý Công Uẩn và giấc mơ rồng bay: Huyền thoại dời đô Thăng Long",
			Slug:        "ly-cong-uan-giac-mo-rong-bay-thang-long",
			Excerpt:     "Huyền thoại Lý Công Uẩn nhìn thấy rồng bay khi đến đất Đại La, từ đó đặt tên Thăng Long – thành phố rồng bay.",
			Content:     `<h2>Huyền thoại rồng bay Thăng Long</h2><p>Theo truyền thuyết, khi Lý Công Uẩn đến vùng đất Đại La, ông nhìn thấy hình tượng rồng vàng bay lên từ mặt đất. Điều này khiến ông quyết định đặt tên kinh đô mới là Thăng Long – "rồng bay lên".</p><h3>Ý nghĩa văn hóa</h3><p>Hình ảnh rồng bay tượng trưng cho sự hưng thịnh và vị thế đế vương. Thăng Long (nay là Hà Nội) đã trở thành thủ đô ngàn năm văn hiến.</p><h3>1010 năm Thăng Long</h3><p>Năm 2010, Hà Nội kỷ niệm 1000 năm Thăng Long, minh chứng cho tầm nhìn thiên tài của Lý Thái Tổ.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Lý Công Uẩn - Huyền thoại rồng bay Thăng Long",
			MetaDescription: "Huyền thoại rồng bay Thăng Long: Lý Công Uẩn dời đô, đặt tên Thăng Long - rồng bay lên.",
			ReadingTime:     5,
			TagNames:        []string{"Nhân vật lịch sử", "Vua chúa", "Triều đại Việt Nam"},
		},
		{
			Title:       "Nguyễn Huệ đại phá quân Thanh: 5 ngày hành quân thần tốc",
			Slug:        "nguyen-hue-dai-pha-quan-thanh-5-ngay",
			Excerpt:     "Phân tích chiến dịch thần tốc của Quang Trung Nguyễn Huệ: hành quân từ Phú Xuân ra Thăng Long trong 5 ngày Tết Kỷ Dậu 1789.",
			Content:     `<h2>5 ngày đại phá quân Thanh</h2><p>Chiến dịch xuân Kỷ Dậu 1789 là một trong những chiến công quân sự vĩ đại nhất trong lịch sử chiến tranh thế giới.</p><h3>Diễn biến</h3><p>Ngày 25 tháng Chạp: Nguyễn Huệ lên ngôi Hoàng đế tại Phú Xuân. Ngày 29 tháng Chạp: xuất quân ra Bắc. Mùng 3 Tết: đến Tam Điệp. Mùng 5 Tết: đại phá quân Thanh tại Ngọc Hồi – Đống Đa.</p><h3>Nghệ thuật quân sự</h3><ul><li>Hành quân thần tốc: 700km trong 5 ngày</li><li>Đánh bất ngờ vào dịp Tết</li><li>Phối hợp nhiều cánh quân hoàn hảo</li></ul>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Nguyễn Huệ đại phá quân Thanh - 5 ngày thần tốc",
			MetaDescription: "Chiến dịch thần tốc Kỷ Dậu 1789: Nguyễn Huệ đại phá 29 vạn quân Thanh trong 5 ngày Tết.",
			ReadingTime:     6,
			TagNames:        []string{"Nhân vật lịch sử", "Anh hùng dân tộc", "Danh tướng"},
		},
		{
			Title:       "Chu Văn An: Người thầy mẫu mực nhất lịch sử Việt Nam",
			Slug:        "chu-van-an-nguoi-thay-mau-muc",
			Excerpt:     "Chu Văn An – nhà giáo mẫu mực, người dâng Thất Trảm Sớ xin chém 7 gian thần. Biểu tượng của nền giáo dục Việt Nam.",
			Content:     `<h2>Chu Văn An – Người thầy vĩ đại</h2><p>Chu Văn An (1292-1370) là nhà giáo, nhà nho mẫu mực thời nhà Trần. Ông được tôn vinh là "Vạn thế sư biểu" – người thầy muôn đời.</p><h3>Sự nghiệp giáo dục</h3><p>Ông mở trường dạy học ở quê, đào tạo nhiều nhân tài cho đất nước. Phạm Sư Mạnh, Lê Quát là những học trò nổi tiếng.</p><h3>Thất Trảm Sớ</h3><p>Khi làm Tư nghiệp Quốc Tử Giám, ông dâng sớ xin vua Trần Dụ Tông chém 7 gian thần nhưng không được chấp nhận. Ông từ quan về núi Phượng Hoàng ẩn cư.</p>`,
			CategorySlug:    "nhan-vat-lich-su",
			MetaTitle:       "Chu Văn An - Người thầy mẫu mực Việt Nam",
			MetaDescription: "Chu Văn An: nhà giáo mẫu mực, Thất Trảm Sớ. Biểu tượng giáo dục Việt Nam muôn đời.",
			ReadingTime:     5,
			TagNames:        []string{"Nhân vật lịch sử", "Danh nhân văn hóa"},
		},
	}

	return createSeedArticles(db, seeds, tagMap, authorID)
}
