package main

import (
	"fmt"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

func seedLichSuArticles(db *gorm.DB, tagMap map[string]uuid.UUID, authorID *uuid.UUID) int {
	fmt.Println("\n   🏛️ Seeding Lịch Sử articles...")

	seeds := []ArticleSeed{
		{
			Title:           "Lịch sử Việt Nam qua các triều đại: Từ Hồng Bàng đến hiện đại",
			Slug:            "lich-su-viet-nam-qua-cac-trieu-dai",
			Excerpt:         "Tổng quan lịch sử Việt Nam từ thời Hồng Bàng, qua các triều đại phong kiến đến thời kỳ hiện đại. 4000 năm văn hiến.",
			Content:         `<h2>Lịch sử Việt Nam qua các triều đại</h2><p>Việt Nam có lịch sử hơn 4000 năm, trải qua nhiều triều đại và biến cố lớn lao.</p><h3>Thời kỳ dựng nước (2879 TCN – 207 TCN)</h3><ul><li>Hồng Bàng – Văn Lang: Vua Hùng, nông nghiệp lúa nước</li><li>Âu Lạc: An Dương Vương, thành Cổ Loa</li></ul><h3>Thời kỳ Bắc thuộc (207 TCN – 938)</h3><p>Hơn 1000 năm đô hộ, nhiều cuộc khởi nghĩa: Hai Bà Trưng, Lý Bí, Phùng Hưng...</p><h3>Thời kỳ độc lập (939 – 1945)</h3><ul><li>Ngô, Đinh, Tiền Lê (939-1009)</li><li>Lý (1009-1225): Thăng Long, Phật giáo hưng thịnh</li><li>Trần (1225-1400): 3 lần đánh Mông Nguyên</li><li>Hậu Lê (1428-1789): Luật Hồng Đức</li><li>Tây Sơn (1778-1802): Quang Trung thống nhất</li><li>Nguyễn (1802-1945): Huế kinh đô</li></ul>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Lịch sử Việt Nam qua các triều đại",
			MetaDescription: "Lịch sử Việt Nam: từ Hồng Bàng qua Lý, Trần, Lê, Nguyễn. 4000 năm văn hiến và dựng nước.",
			ReadingTime:     8,
			IsFeatured:      true,
			TagNames:        []string{"Lịch sử Việt Nam"},
		},
		{
			Title:       "Triều đại nhà Lý (1009-1225): Dời đô Thăng Long và thời kỳ hoàng kim",
			Slug:        "trieu-dai-nha-ly-1009-1225-doi-do-thang-long",
			Excerpt:     "Nhà Lý – triều đại mở đầu kỷ nguyên Thăng Long. Lý Thái Tổ dời đô, xây dựng nền văn minh Đại Việt rực rỡ.",
			Content:     `<h2>Triều đại nhà Lý (1009-1225)</h2><p>Nhà Lý là triều đại phong kiến kéo dài 216 năm, đánh dấu thời kỳ phát triển rực rỡ của Đại Việt.</p><h3>Dời đô Thăng Long (1010)</h3><p>Lý Thái Tổ viết Chiếu dời đô, chuyển kinh đô từ Hoa Lư (Ninh Bình) về Đại La, đổi tên thành Thăng Long – "rồng bay lên".</p><h3>Thành tựu</h3><ul><li>Xây dựng Văn Miếu – Quốc Tử Giám (1070)</li><li>Phật giáo phát triển cực thịnh</li><li>Lý Thường Kiệt chiến thắng quân Tống (1077)</li><li>Bài thơ Nam Quốc Sơn Hà – bản tuyên ngôn độc lập đầu tiên</li></ul><h3>Các vua tiêu biểu</h3><p>Lý Thái Tổ, Lý Thái Tông, Lý Thánh Tông, Lý Nhân Tông.</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Triều đại nhà Lý - Dời đô Thăng Long",
			MetaDescription: "Nhà Lý (1009-1225): dời đô Thăng Long, Văn Miếu Quốc Tử Giám. Thời kỳ hoàng kim Đại Việt.",
			ReadingTime:     6,
			IsFeatured:      true,
			TagNames:        []string{"Lịch sử Việt Nam", "Nhân vật lịch sử"},
		},
		{
			Title:       "Triều đại nhà Trần (1225-1400): Ba lần đánh bại Mông Nguyên",
			Slug:        "trieu-dai-nha-tran-1225-1400-ba-lan-danh-mong-nguyen",
			Excerpt:     "Nhà Trần với chiến công 3 lần đánh bại quân Mông Nguyên. Hào khí Đông A và tinh thần Sát Thát.",
			Content:     `<h2>Triều đại nhà Trần</h2><p>Nhà Trần trị vì 175 năm, nổi bật với hào khí Đông A và ba lần chiến thắng quân Mông – Nguyên hùng mạnh nhất thế giới thời bấy giờ.</p><h3>3 lần kháng chiến</h3><ul><li><strong>Lần 1 (1258):</strong> Trần Thái Tông đánh bại quân Mông Cổ</li><li><strong>Lần 2 (1285):</strong> Trần Hưng Đạo đại phá quân Nguyên</li><li><strong>Lần 3 (1288):</strong> Chiến thắng Bạch Đằng lịch sử</li></ul><h3>Hào khí Đông A</h3><p>Hội nghị Diên Hồng hỏi ý toàn dân. Các bô lão đồng thanh hô "Đánh!". Câu nói bất hủ: "Bệ hạ muốn hàng, hãy chém đầu thần trước đã!"</p><h3>Nhân vật nổi bật</h3><p>Trần Hưng Đạo, Trần Nhân Tông, Trần Quốc Toản, Phạm Ngũ Lão.</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Nhà Trần - 3 lần đánh Mông Nguyên",
			MetaDescription: "Nhà Trần (1225-1400): 3 lần đánh bại Mông Nguyên, hào khí Đông A. Trần Hưng Đạo, Bạch Đằng.",
			ReadingTime:     6,
			TagNames:        []string{"Lịch sử Việt Nam", "Nhân vật lịch sử"},
		},
		{
			Title:       "Triều Hậu Lê (1428-1789): Lê Lợi và bộ luật Hồng Đức",
			Slug:        "trieu-hau-le-1428-1789-le-loi-luat-hong-duc",
			Excerpt:     "Triều Hậu Lê: Lê Lợi khởi nghĩa Lam Sơn, Lê Thánh Tông ban hành bộ luật Hồng Đức tiến bộ nhất Đông Nam Á.",
			Content:     `<h2>Triều Hậu Lê</h2><p>Hậu Lê là triều đại dài nhất lịch sử Việt Nam (361 năm), được chia thành Lê Sơ và Lê Trung Hưng.</p><h3>Khởi nghĩa Lam Sơn (1418-1427)</h3><p>Lê Lợi cùng Nguyễn Trãi lãnh đạo cuộc kháng chiến 10 năm chống quân Minh, giành lại độc lập.</p><h3>Bộ luật Hồng Đức</h3><p>Do Lê Thánh Tông ban hành, gồm 722 điều, là bộ luật tiến bộ nhất thời phong kiến. Đặc biệt bảo vệ quyền phụ nữ, người yếu thế.</p><h3>Thời kỳ Lê Thánh Tông</h3><ul><li>Cải cách hành chính: chia 13 đạo thừa tuyên</li><li>Phát triển giáo dục: mở rộng thi cử</li><li>Lập Hội Tao Đàn: 28 vì sao thơ</li></ul>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Triều Hậu Lê - Lê Lợi và luật Hồng Đức",
			MetaDescription: "Hậu Lê (1428-1789): Lê Lợi khởi nghĩa Lam Sơn, luật Hồng Đức. Triều đại dài nhất lịch sử.",
			ReadingTime:     6,
			TagNames:        []string{"Lịch sử Việt Nam", "Nhân vật lịch sử"},
		},
		{
			Title:       "Phong trào Tây Sơn và hoàng đế Quang Trung – Nguyễn Huệ",
			Slug:        "phong-trao-tay-son-hoang-de-quang-trung",
			Excerpt:     "Phong trào Tây Sơn: ba anh em Nguyễn Nhạc, Nguyễn Huệ, Nguyễn Lữ thống nhất đất nước. Đại phá quân Thanh xuân Kỷ Dậu.",
			Content:     `<h2>Phong trào Tây Sơn</h2><p>Tây Sơn là phong trào nông dân lớn nhất lịch sử, do ba anh em nhà Tây Sơn lãnh đạo (1771-1802).</p><h3>Thống nhất đất nước</h3><ul><li>1777: Diệt chúa Nguyễn ở Đàng Trong</li><li>1786: Diệt chúa Trịnh ở Đàng Ngoài</li><li>1789: Đại phá 29 vạn quân Thanh</li></ul><h3>Đại phá quân Thanh (1789)</h3><p>Hoàng đế Quang Trung tiến quân thần tốc từ Phú Xuân ra Thăng Long trong 5 ngày đêm. Trận Ngọc Hồi – Đống Đa ngày mùng 5 Tết Kỷ Dậu là chiến thắng vang dội nhất.</p><h3>Cải cách của Quang Trung</h3><ul><li>Dùng chữ Nôm làm quốc ngữ</li><li>Cải cách giáo dục, thuế khóa</li><li>Phát triển thương mại với nước ngoài</li></ul>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Tây Sơn - Quang Trung đại phá quân Thanh",
			MetaDescription: "Phong trào Tây Sơn: Quang Trung Nguyễn Huệ thống nhất đất nước, đại phá quân Thanh xuân Kỷ Dậu.",
			ReadingTime:     6,
			TagNames:        []string{"Lịch sử Việt Nam", "Nhân vật lịch sử"},
		},
		{
			Title:       "Triều Nguyễn (1802-1945): Kinh đô Huế và di sản văn hóa",
			Slug:        "trieu-nguyen-1802-1945-kinh-do-hue-di-san",
			Excerpt:     "Triều Nguyễn – triều đại phong kiến cuối cùng: Gia Long thống nhất, kinh thành Huế và di sản UNESCO.",
			Content:     `<h2>Triều Nguyễn (1802-1945)</h2><p>Nhà Nguyễn là triều đại phong kiến cuối cùng của Việt Nam, đặt kinh đô tại Phú Xuân (Huế).</p><h3>Gia Long thống nhất</h3><p>Nguyễn Ánh sau nhiều năm chiến đấu với Tây Sơn, thống nhất đất nước năm 1802, lấy hiệu Gia Long, đặt tên nước là Việt Nam.</p><h3>Di sản kinh thành Huế</h3><ul><li>Hoàng thành, Tử Cấm Thành, lăng tẩm vua</li><li>Đại Nội – quần thể cung điện độc đáo</li><li>UNESCO công nhận Di sản Văn hóa Thế giới (1993)</li></ul><h3>Các vua tiêu biểu</h3><p>Gia Long, Minh Mạng (cải cách), Tự Đức (văn chương), Thành Thái, Duy Tân (yêu nước).</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Triều Nguyễn - Kinh đô Huế",
			MetaDescription: "Triều Nguyễn (1802-1945): kinh thành Huế di sản UNESCO, Gia Long thống nhất. Triều đại cuối cùng.",
			ReadingTime:     6,
			TagNames:        []string{"Lịch sử Việt Nam"},
		},
		{
			Title:       "Chiến thắng Bạch Đằng: Từ Ngô Quyền (938) đến Trần Hưng Đạo (1288)",
			Slug:        "chien-thang-bach-dang-ngo-quyen-tran-hung-dao",
			Excerpt:     "Sông Bạch Đằng – dòng sông huyền thoại với 3 trận thủy chiến vang dội. Từ Ngô Quyền đánh Nam Hán đến Trần Hưng Đạo phá Nguyên Mông.",
			Content:     `<h2>Chiến thắng Bạch Đằng</h2><p>Sông Bạch Đằng (Hải Phòng – Quảng Ninh) là nơi diễn ra 3 trận thủy chiến lừng danh lịch sử dân tộc.</p><h3>Trận 1: Ngô Quyền (938)</h3><p>Ngô Quyền dùng cọc gỗ bọc sắt cắm dưới lòng sông, dụ quân Nam Hán vào khi thủy triều lên, đợi nước rút rồi phản công. Chiến thắng chấm dứt 1000 năm Bắc thuộc.</p><h3>Trận 2: Lê Hoàn (981)</h3><p>Lê Đại Hành dùng chiến thuật tương tự đánh bại quân Tống xâm lược.</p><h3>Trận 3: Trần Hưng Đạo (1288)</h3><p>Trận Bạch Đằng vĩ đại nhất: hàng nghìn cọc gỗ, quân Trần mai phục, tiêu diệt toàn bộ thủy quân Nguyên Mông. Tướng giặc Ô Mã Nhi bị bắt sống.</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Chiến thắng Bạch Đằng - Ngô Quyền và Trần Hưng Đạo",
			MetaDescription: "3 trận Bạch Đằng: Ngô Quyền (938), Lê Hoàn (981), Trần Hưng Đạo (1288). Dòng sông huyền thoại.",
			ReadingTime:     6,
			TagNames:        []string{"Lịch sử Việt Nam", "Nhân vật lịch sử"},
		},
		{
			Title:       "Chiến thắng Điện Biên Phủ 1954: Trận đánh chấn động địa cầu",
			Slug:        "chien-thang-dien-bien-phu-1954-chan-dong-dia-cau",
			Excerpt:     "Chiến thắng Điện Biên Phủ 7/5/1954: 56 ngày đêm chiến đấu, Việt Nam đánh bại Pháp, chấm dứt chế độ thực dân.",
			Content:     `<h2>Chiến thắng Điện Biên Phủ</h2><p>Ngày 7/5/1954, lá cờ Việt Nam tung bay trên nóc hầm De Castries, đánh dấu chiến thắng vĩ đại nhất trong lịch sử kháng chiến chống Pháp.</p><h3>Bối cảnh</h3><p>Navarre xây dựng Điện Biên Phủ thành "pháo đài bất khả xâm phạm" với 16.000 quân tinh nhuệ, 49 cứ điểm.</p><h3>Diễn biến</h3><ul><li><strong>Đợt 1 (13-17/3):</strong> Tiêu diệt Him Lam, Độc Lập, Bản Kéo</li><li><strong>Đợt 2 (30/3-26/4):</strong> Đánh chiếm các đồi phía đông</li><li><strong>Đợt 3 (1-7/5):</strong> Tổng công kích, chiếm sở chỉ huy</li></ul><h3>Ý nghĩa</h3><p>Chấm dứt chế độ thực dân Pháp ở Đông Dương, dẫn đến Hiệp định Genève. Tướng Võ Nguyên Giáp được thế giới ca ngợi.</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Điện Biên Phủ 1954 - Chấn động địa cầu",
			MetaDescription: "Chiến thắng Điện Biên Phủ 7/5/1954: 56 ngày đêm, đánh bại Pháp. Trận đánh chấn động địa cầu.",
			ReadingTime:     7,
			IsFeatured:      true,
			TagNames:        []string{"Lịch sử Việt Nam", "Nhân vật lịch sử"},
		},
		{
			Title:       "Chữ Quốc Ngữ: Lịch sử ra đời và phát triển của chữ viết Việt Nam",
			Slug:        "chu-quoc-ngu-lich-su-ra-doi-phat-trien",
			Excerpt:     "Lịch sử chữ Quốc Ngữ: từ Alexandre de Rhodes đến Phong trào Duy Tân. Hành trình trở thành chữ viết chính thức.",
			Content:     `<h2>Chữ Quốc Ngữ</h2><p>Chữ Quốc Ngữ là hệ thống chữ viết dựa trên bảng chữ cái Latin, được sáng tạo và phát triển qua nhiều thế kỷ.</p><h3>Nguồn gốc</h3><p>Các giáo sĩ Bồ Đào Nha và Pháp sáng tạo chữ Quốc Ngữ từ thế kỷ 17. Alexandre de Rhodes hoàn thiện và xuất bản Từ điển Việt-Bồ-La (1651).</p><h3>Quá trình phát triển</h3><ul><li><strong>Thế kỷ 17:</strong> Chỉ dùng trong truyền giáo</li><li><strong>Cuối thế kỷ 19:</strong> Pháp áp dụng trong giáo dục</li><li><strong>Đầu thế kỷ 20:</strong> Phong trào Duy Tân phổ biến rộng rãi</li><li><strong>Từ 1945:</strong> Trở thành chữ viết chính thức</li></ul><h3>Trước Quốc Ngữ</h3><p>Người Việt dùng chữ Hán và chữ Nôm (sáng tạo từ chữ Hán).</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Chữ Quốc Ngữ - Lịch sử ra đời",
			MetaDescription: "Lịch sử chữ Quốc Ngữ: Alexandre de Rhodes, Phong trào Duy Tân đến chữ viết chính thức Việt Nam.",
			ReadingTime:     6,
			TagNames:        []string{"Lịch sử Việt Nam"},
		},
		{
			Title:       "Văn Miếu Quốc Tử Giám: Trường đại học đầu tiên của Việt Nam",
			Slug:        "van-mieu-quoc-tu-giam-truong-dai-hoc-dau-tien",
			Excerpt:     "Văn Miếu (1070) – Quốc Tử Giám (1076): di tích lịch sử, trường đại học đầu tiên và biểu tượng giáo dục Việt Nam.",
			Content:     `<h2>Văn Miếu Quốc Tử Giám</h2><p>Văn Miếu Quốc Tử Giám là quần thể di tích nổi tiếng nhất Hà Nội, biểu tượng cho truyền thống hiếu học của dân tộc.</p><h3>Lịch sử</h3><ul><li><strong>1070:</strong> Lý Thánh Tông cho xây Văn Miếu thờ Khổng Tử</li><li><strong>1076:</strong> Lý Nhân Tông lập Quốc Tử Giám – trường đại học đầu tiên</li><li><strong>1484:</strong> Dựng bia tiến sĩ trên lưng rùa đá</li></ul><h3>Kiến trúc</h3><p>5 lớp không gian: Văn Miếu Môn, Đại Trung Môn, Khuê Văn Các, sân Giếng Thiên Quang, Đại Thành Môn.</p><h3>82 tấm bia tiến sĩ</h3><p>Ghi tên 1.307 vị tiến sĩ qua các khoa thi từ 1442-1779. UNESCO công nhận Di sản Tư liệu Thế giới (2010).</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Văn Miếu Quốc Tử Giám - Đại học đầu tiên",
			MetaDescription: "Văn Miếu Quốc Tử Giám: trường đại học đầu tiên, 82 bia tiến sĩ. Di sản UNESCO tại Hà Nội.",
			ReadingTime:     5,
			TagNames:        []string{"Lịch sử Việt Nam"},
		},
		{
			Title:       "Con đường tơ lụa trên biển và thương cảng Hội An",
			Slug:        "con-duong-to-lua-bien-thuong-cang-hoi-an",
			Excerpt:     "Thương cảng Hội An trên con đường tơ lụa: giao thương quốc tế, Phố cổ UNESCO và lịch sử 400 năm sầm uất.",
			Content:     `<h2>Thương cảng Hội An</h2><p>Hội An (Quảng Nam) từng là một trong những thương cảng sầm uất nhất Đông Nam Á, nằm trên con đường tơ lụa trên biển.</p><h3>Thời kỳ hoàng kim (TK 16-18)</h3><p>Thương nhân Nhật Bản, Trung Quốc, Bồ Đào Nha, Hà Lan tụ hội buôn bán. Hàng hóa: tơ lụa, gốm sứ, gia vị, quế.</p><h3>Di sản phố cổ</h3><ul><li>Chùa Cầu (Lai Viễn Kiều) – biểu tượng Hội An</li><li>Hội quán người Hoa: Phúc Kiến, Quảng Đông, Triều Châu</li><li>Nhà cổ: kiến trúc Việt-Hoa-Nhật độc đáo</li></ul><h3>UNESCO (1999)</h3><p>Phố cổ Hội An được công nhận Di sản Văn hóa Thế giới nhờ bảo tồn nguyên vẹn kiến trúc và văn hóa đa dạng.</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Hội An - Thương cảng trên con đường tơ lụa",
			MetaDescription: "Thương cảng Hội An: con đường tơ lụa, phố cổ UNESCO. 400 năm giao thương quốc tế.",
			ReadingTime:     5,
			TagNames:        []string{"Lịch sử Việt Nam"},
		},
		{
			Title:       "Hoàng Sa và Trường Sa: Bằng chứng chủ quyền lịch sử của Việt Nam",
			Slug:        "hoang-sa-truong-sa-chu-quyen-lich-su-viet-nam",
			Excerpt:     "Bằng chứng lịch sử về chủ quyền Việt Nam đối với Hoàng Sa và Trường Sa. Châu bản triều Nguyễn và bản đồ cổ.",
			Content:     `<h2>Hoàng Sa và Trường Sa</h2><p>Quần đảo Hoàng Sa và Trường Sa là phần lãnh thổ không thể tách rời của Việt Nam, được khẳng định bằng nhiều bằng chứng lịch sử.</p><h3>Bằng chứng lịch sử</h3><ul><li><strong>Thế kỷ 17:</strong> Chúa Nguyễn thành lập đội Hoàng Sa, Bắc Hải để khai thác</li><li><strong>Châu bản triều Nguyễn:</strong> Nhiều văn bản chính thức ghi nhận việc quản lý</li><li><strong>Đại Nam thực lục:</strong> Ghi chép chi tiết hoạt động tại quần đảo</li></ul><h3>Bản đồ</h3><p>Bản đồ An Nam Đại Quốc (1838), Atlas Taberd và nhiều bản đồ phương Tây thế kỷ 17-19 đều ghi nhận hai quần đảo thuộc Việt Nam.</p><h3>Ý nghĩa</h3><p>Bảo vệ chủ quyền biển đảo là trách nhiệm thiêng liêng của mọi thế hệ người Việt.</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Hoàng Sa Trường Sa - Chủ quyền Việt Nam",
			MetaDescription: "Chủ quyền Hoàng Sa Trường Sa: bằng chứng lịch sử, châu bản triều Nguyễn, bản đồ cổ.",
			ReadingTime:     6,
			IsFeatured:      true,
			TagNames:        []string{"Lịch sử Việt Nam"},
		},
		{
			Title:       "Trống đồng Đông Sơn: Báu vật văn hóa Việt cổ 2500 năm",
			Slug:        "trong-dong-dong-son-bau-vat-van-hoa-viet-co",
			Excerpt:     "Trống đồng Đông Sơn – biểu tượng văn minh Việt cổ. Lịch sử 2500 năm, hoa văn độc đáo và ý nghĩa tâm linh.",
			Content:     `<h2>Trống đồng Đông Sơn</h2><p>Trống đồng Đông Sơn là hiện vật tiêu biểu nhất của văn hóa Đông Sơn (khoảng 700 TCN – 100 SCN), biểu tượng cho nền văn minh Việt cổ.</p><h3>Đặc điểm</h3><ul><li>Chất liệu: đồng pha thiếc, kỹ thuật đúc tinh xảo</li><li>Hoa văn: ngôi sao trung tâm, hình người, chim Lạc, thuyền</li><li>Kích thước: đường kính 60-80cm, nặng 50-100kg</li></ul><h3>Ý nghĩa</h3><p>Trống đồng dùng trong nghi lễ, cầu mưa, lễ hội, chiến tranh. Ngôi sao trung tâm tượng trưng cho Mặt Trời – tín ngưỡng phồn thực.</p><h3>Ngọc Lũ</h3><p>Trống đồng Ngọc Lũ (Hà Nam) là chiếc đẹp nhất, được công nhận Bảo vật Quốc gia, hiện trưng bày tại Bảo tàng Lịch sử Quốc gia.</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Trống đồng Đông Sơn - Báu vật Việt cổ",
			MetaDescription: "Trống đồng Đông Sơn 2500 năm: hoa văn, kỹ thuật đúc. Biểu tượng văn minh Việt cổ.",
			ReadingTime:     5,
			TagNames:        []string{"Lịch sử Việt Nam"},
		},
		{
			Title:       "Cách mạng tháng Tám 1945: Sự kiện lịch sử trọng đại của dân tộc",
			Slug:        "cach-mang-thang-tam-1945-su-kien-lich-su",
			Excerpt:     "Cách mạng tháng Tám: tổng khởi nghĩa thành công, Hồ Chí Minh đọc Tuyên ngôn Độc lập 2/9/1945 tại Ba Đình.",
			Content:     `<h2>Cách mạng tháng Tám 1945</h2><p>Cách mạng tháng Tám là cuộc cách mạng vĩ đại, lật đổ chế độ thực dân phong kiến, khai sinh nước Việt Nam Dân chủ Cộng hòa.</p><h3>Bối cảnh</h3><p>Nhật đầu hàng Đồng Minh (15/8/1945), khoảng trống quyền lực xuất hiện. Đảng phát động tổng khởi nghĩa.</p><h3>Diễn biến</h3><ul><li><strong>19/8:</strong> Khởi nghĩa thành công ở Hà Nội</li><li><strong>23/8:</strong> Khởi nghĩa ở Huế</li><li><strong>25/8:</strong> Khởi nghĩa ở Sài Gòn</li><li><strong>30/8:</strong> Bảo Đại thoái vị</li></ul><h3>Tuyên ngôn Độc lập</h3><p>Ngày 2/9/1945, tại Quảng trường Ba Đình, Chủ tịch Hồ Chí Minh đọc Tuyên ngôn Độc lập: "Tất cả mọi người đều sinh ra có quyền bình đẳng..."</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Cách mạng tháng Tám 1945",
			MetaDescription: "Cách mạng tháng Tám 1945: tổng khởi nghĩa, Tuyên ngôn Độc lập 2/9. Khai sinh Việt Nam mới.",
			ReadingTime:     6,
			TagNames:        []string{"Lịch sử Việt Nam", "Nhân vật lịch sử"},
		},
		{
			Title:       "10 trận đánh nổi tiếng nhất trong lịch sử Việt Nam",
			Slug:        "10-tran-danh-noi-tieng-lich-su-viet-nam",
			Excerpt:     "Điểm qua 10 trận đánh vang dội nhất: Bạch Đằng, Chi Lăng, Ngọc Hồi, Điện Biên Phủ... và ý nghĩa lịch sử.",
			Content:     `<h2>10 trận đánh nổi tiếng nhất</h2><p>Lịch sử Việt Nam gắn liền với những trận đánh vang dội, thể hiện tinh thần bất khuất của dân tộc.</p><ol><li><strong>Bạch Đằng (938):</strong> Ngô Quyền – cọc gỗ bọc sắt, chấm dứt Bắc thuộc</li><li><strong>Như Nguyệt (1077):</strong> Lý Thường Kiệt – Nam Quốc Sơn Hà</li><li><strong>Bạch Đằng (1288):</strong> Trần Hưng Đạo – diệt Nguyên Mông</li><li><strong>Chi Lăng – Xương Giang (1427):</strong> Lê Lợi – diệt quân Minh</li><li><strong>Rạch Gầm – Xoài Mút (1785):</strong> Nguyễn Huệ – diệt quân Xiêm</li><li><strong>Ngọc Hồi – Đống Đa (1789):</strong> Quang Trung – đại phá quân Thanh</li><li><strong>Điện Biên Phủ (1954):</strong> Võ Nguyên Giáp – chấn động địa cầu</li><li><strong>Ấp Bắc (1963):</strong> Đánh thắng chiến thuật trực thăng vận</li><li><strong>Tết Mậu Thân (1968):</strong> Tổng tiến công 36 tỉnh thành</li><li><strong>Hồ Chí Minh (1975):</strong> Giải phóng Sài Gòn, thống nhất đất nước</li></ol>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "10 trận đánh nổi tiếng nhất Việt Nam",
			MetaDescription: "10 trận đánh vĩ đại nhất: Bạch Đằng, Chi Lăng, Điện Biên Phủ... Lịch sử quân sự Việt Nam.",
			ReadingTime:     7,
			IsFeatured:      true,
			TagNames:        []string{"Lịch sử Việt Nam", "Nhân vật lịch sử"},
		},
		{
			Title:       "Kinh thành Thăng Long: 1000 năm lịch sử thủ đô Hà Nội",
			Slug:        "kinh-thanh-thang-long-1000-nam-ha-noi",
			Excerpt:     "Thăng Long – Hà Nội: từ Chiếu dời đô 1010 đến Đại lễ 1000 năm. Lịch sử, di sản và vị trí đặc biệt.",
			Content:     `<h2>Kinh thành Thăng Long</h2><p>Thăng Long (nay là Hà Nội) là thủ đô có lịch sử hơn 1000 năm, một trong những thành phố cổ nhất Đông Nam Á.</p><h3>Chiếu dời đô (1010)</h3><p>Lý Thái Tổ ban Chiếu dời đô từ Hoa Lư về Đại La: "Xem khắp đất Việt đây là nơi thắng địa, thực là chỗ hội tụ trọng yếu của bốn phương..."</p><h3>Hoàng thành</h3><ul><li>Xây dựng qua nhiều triều đại: Lý, Trần, Lê</li><li>Cấu trúc: thành ngoài, thành giữa (hoàng thành), thành trong (cấm thành)</li><li>UNESCO công nhận Di sản Thế giới (2010)</li></ul><h3>Tên gọi qua thời gian</h3><p>Đại La → Thăng Long → Đông Kinh → Bắc Thành → Hà Nội (1831)</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Kinh thành Thăng Long - 1000 năm Hà Nội",
			MetaDescription: "Thăng Long 1000 năm: Chiếu dời đô, hoàng thành UNESCO. Lịch sử thủ đô Hà Nội.",
			ReadingTime:     6,
			TagNames:        []string{"Lịch sử Việt Nam"},
		},
		{
			Title:       "Áo dài Việt Nam: Lịch sử, biến đổi và ý nghĩa văn hóa",
			Slug:        "ao-dai-viet-nam-lich-su-bien-doi-van-hoa",
			Excerpt:     "Áo dài – quốc phục Việt Nam: lịch sử 300 năm, từ áo ngũ thân đến áo dài hiện đại. Biểu tượng văn hóa dân tộc.",
			Content:     `<h2>Áo dài Việt Nam</h2><p>Áo dài là trang phục truyền thống, biểu tượng văn hóa và vẻ đẹp người phụ nữ Việt Nam.</p><h3>Lịch sử</h3><ul><li><strong>Thế kỷ 18:</strong> Chúa Nguyễn quy định áo ngũ thân, phân biệt với Đàng Ngoài</li><li><strong>1930s:</strong> Nghệ sĩ Cát Tường (Lemur) cách tân thành áo dài tân thời</li><li><strong>1960s:</strong> Bà Trần Lệ Xuân tạo phong cách áo dài cổ thuyền</li><li><strong>Hiện đại:</strong> Đa dạng chất liệu, họa tiết, phong cách</li></ul><h3>Ý nghĩa văn hóa</h3><p>Áo dài thể hiện sự kín đáo nhưng thanh lịch, tôn vinh vẻ đẹp hình thể mà vẫn giữ nét truyền thống.</p><h3>Áo dài ngày nay</h3><p>Mặc trong lễ cưới, tốt nghiệp, sự kiện ngoại giao, đồng phục nữ sinh và tiếp viên hàng không.</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Áo dài Việt Nam - Lịch sử và ý nghĩa",
			MetaDescription: "Áo dài: quốc phục 300 năm, từ ngũ thân đến hiện đại. Biểu tượng văn hóa Việt Nam.",
			ReadingTime:     5,
			TagNames:        []string{"Lịch sử Việt Nam"},
		},
		{
			Title:       "Tín ngưỡng thờ cúng tổ tiên: Nét đẹp văn hóa ngàn năm",
			Slug:        "tin-nguong-tho-cung-to-tien-van-hoa",
			Excerpt:     "Thờ cúng tổ tiên – tín ngưỡng quan trọng nhất của người Việt. Lịch sử, ý nghĩa tâm linh và cách thờ đúng.",
			Content:     `<h2>Tín ngưỡng thờ cúng tổ tiên</h2><p>Thờ cúng tổ tiên là tín ngưỡng lâu đời nhất, phổ biến nhất và quan trọng nhất trong đời sống tâm linh người Việt.</p><h3>Nguồn gốc</h3><p>Bắt nguồn từ tín ngưỡng bản địa thời Hùng Vương, kết hợp ảnh hưởng Nho giáo. Người Việt tin người chết vẫn có linh hồn, phù hộ con cháu.</p><h3>Bàn thờ tổ tiên</h3><ul><li>Vị trí: nơi trang trọng nhất trong nhà</li><li>Bài vị, di ảnh, lư hương, bình hoa, đèn</li><li>Luôn giữ sạch sẽ, thắp hương hàng ngày</li></ul><h3>Dịp cúng</h3><p>Ngày giỗ (quan trọng nhất), Tết, rằm, mùng 1, các sự kiện gia đình (cưới, sinh con, thi cử...).</p><h3>Ý nghĩa</h3><p>Nhắc nhở con cháu về cội nguồn, gắn kết gia đình, truyền thống "uống nước nhớ nguồn".</p>`,
			CategorySlug:    "lich-su",
			MetaTitle:       "Thờ cúng tổ tiên - Tín ngưỡng Việt Nam",
			MetaDescription: "Thờ cúng tổ tiên: tín ngưỡng quan trọng nhất người Việt. Ý nghĩa, bàn thờ, cách cúng đúng.",
			ReadingTime:     5,
			TagNames:        []string{"Lịch sử Việt Nam", "Phong tục"},
		},
	}

	return createSeedArticles(db, seeds, tagMap, authorID)
}
