package main

import (
	"fmt"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

func seedTuViArticles(db *gorm.DB, tagMap map[string]uuid.UUID, authorID *uuid.UUID) int {
	fmt.Println("\n   ⭐ Seeding Tử Vi articles...")

	seeds := []ArticleSeed{
		// === TỬ VI 12 CUNG HOÀNG ĐẠO NĂM 2026 ===
		{
			Title:           "Tử vi Bạch Dương 2026: Vận mệnh, tình yêu, sự nghiệp và tài lộc",
			Slug:            "tu-vi-bach-duong-2026",
			Excerpt:         "Tổng quan tử vi cung Bạch Dương năm 2026. Dự đoán chi tiết về tình yêu, sự nghiệp, tài chính và sức khỏe cho người sinh từ 21/3 - 19/4.",
			Content:         `<h2>Tổng quan tử vi Bạch Dương 2026</h2><p>Năm 2026 là một năm đầy năng lượng và cơ hội cho cung Bạch Dương. Với sự hỗ trợ của Sao Mộc đi qua cung Thiên Bình, các mối quan hệ đối tác sẽ được củng cố mạnh mẽ.</p><h3>Tình yêu</h3><p>Người Bạch Dương độc thân có cơ hội tìm thấy tình yêu đích thực vào nửa đầu năm. Những người đã có đôi sẽ trải qua giai đoạn lãng mạn và gắn kết hơn. Tháng 5 và tháng 9 là thời điểm vàng cho chuyện tình cảm.</p><h3>Sự nghiệp</h3><p>Công việc có nhiều bước tiến tích cực. Quý 2 mang đến cơ hội thăng tiến hoặc chuyển đổi công việc tốt hơn. Hãy tận dụng khả năng lãnh đạo bẩm sinh để ghi điểm với cấp trên.</p><h3>Tài chính</h3><p>Tài chính ổn định với xu hướng tăng trưởng. Nửa cuối năm là thời điểm tốt để đầu tư dài hạn. Tuy nhiên, cần tránh chi tiêu bốc đồng trong tháng 3 và tháng 8.</p><h3>Sức khỏe</h3><p>Sức khỏe nhìn chung tốt. Cần chú ý vùng đầu và mắt. Tập thể dục đều đặn và duy trì chế độ ăn uống lành mạnh sẽ giúp bạn luôn tràn đầy năng lượng.</p><h3>Lời khuyên cho Bạch Dương 2026</h3><ul><li>Kiên nhẫn hơn trong các mối quan hệ</li><li>Đầu tư vào học hỏi kỹ năng mới</li><li>Duy trì lối sống lành mạnh</li><li>Tận dụng cơ hội trong quý 2</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tử vi Bạch Dương 2026 - Vận mệnh, tình yêu, sự nghiệp",
			MetaDescription: "Xem tử vi cung Bạch Dương năm 2026 chi tiết. Dự đoán tình yêu, sự nghiệp, tài chính và sức khỏe cho người sinh 21/3 - 19/4.",
			ReadingTime:     5,
			IsFeatured:      true,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Bạch Dương", "Tử vi 2026"},
		},
		{
			Title:           "Tử vi Kim Ngưu 2026: Dự đoán chi tiết vận mệnh cả năm",
			Slug:            "tu-vi-kim-nguu-2026",
			Excerpt:         "Tử vi cung Kim Ngưu năm 2026 với những dự đoán về tình yêu, công việc, tiền bạc. Người sinh 20/4 - 20/5 cần biết điều gì?",
			Content:         `<h2>Tử vi Kim Ngưu 2026</h2><p>Năm 2026 mang đến cho Kim Ngưu sự ổn định và cơ hội phát triển bền vững. Sao Thổ ở vị trí thuận lợi giúp bạn xây dựng nền tảng vững chắc cho tương lai.</p><h3>Tình yêu</h3><p>Chuyện tình cảm có nhiều biến chuyển tích cực. Người độc thân có thể gặp được người phù hợp qua bạn bè hoặc công việc. Các cặp đôi nên dành nhiều thời gian chất lượng bên nhau.</p><h3>Sự nghiệp</h3><p>Đây là năm để Kim Ngưu thể hiện sự kiên trì và tận tâm. Cơ hội thăng tiến đến vào quý 3. Những dự án dài hạn sẽ mang lại kết quả xứng đáng.</p><h3>Tài chính</h3><p>Kim Ngưu vốn giỏi quản lý tài chính, năm 2026 tiếp tục phát huy thế mạnh này. Thu nhập tăng ổn định, có thể từ nhiều nguồn khác nhau. Bất động sản là kênh đầu tư đáng cân nhắc.</p><h3>Sức khỏe</h3><p>Cần chú ý vùng cổ họng và tuyến giáp. Giảm stress bằng yoga hoặc thiền định. Tháng 6-7 cần đặc biệt chăm sóc sức khỏe.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tử vi Kim Ngưu 2026 - Dự đoán vận mệnh chi tiết",
			MetaDescription: "Tử vi Kim Ngưu 2026: tình yêu, sự nghiệp, tài chính. Dự đoán chi tiết cho người sinh 20/4 - 20/5 trong năm mới.",
			ReadingTime:     5,
			IsFeatured:      true,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Kim Ngưu", "Tử vi 2026"},
		},
		{
			Title:           "Tử vi Song Tử 2026: Năm của giao tiếp và cơ hội mới",
			Slug:            "tu-vi-song-tu-2026",
			Excerpt:         "Cung Song Tử năm 2026 sẽ tỏa sáng với khả năng giao tiếp xuất sắc. Xem chi tiết tử vi tình yêu, sự nghiệp cho người sinh 21/5 - 20/6.",
			Content:         `<h2>Tử vi Song Tử 2026</h2><p>Năm 2026 là năm Song Tử tỏa sáng nhờ khả năng giao tiếp và sự linh hoạt. Sao Thủy – hành tinh chủ quản của bạn – đem lại nhiều cơ hội mở rộng mối quan hệ và kiến thức.</p><h3>Tình yêu</h3><p>Đời sống tình cảm sôi động với nhiều cuộc gặp gỡ thú vị. Người độc thân có thể gặp người ấy qua mạng xã hội hoặc sự kiện. Cặp đôi cần cải thiện giao tiếp để tránh hiểu lầm.</p><h3>Sự nghiệp</h3><p>Năng lực truyền thông và đàm phán là vũ khí lợi hại. Cơ hội chuyển việc hoặc làm thêm dự án phụ rất cao. Lĩnh vực viết lách, marketing, giáo dục đặc biệt thuận lợi.</p><h3>Tài chính</h3><p>Thu nhập có thể đến từ nhiều nguồn khác nhau. Tuy nhiên, Song Tử cần tránh đầu tư dàn trải. Tập trung vào 1-2 kênh chính sẽ hiệu quả hơn.</p><h3>Sức khỏe</h3><p>Hệ thần kinh và phổi cần được chú ý. Tránh làm việc quá sức, dành thời gian nghỉ ngơi đầy đủ. Tháng 4 và tháng 10 nên đi khám tổng quát.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tử vi Song Tử 2026 - Cơ hội mới trong năm",
			MetaDescription: "Tử vi Song Tử 2026: dự đoán tình yêu, sự nghiệp, tài chính cho người sinh 21/5 - 20/6. Năm của giao tiếp và cơ hội.",
			ReadingTime:     5,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Song Tử", "Tử vi 2026"},
		},
		{
			Title:           "Tử vi Cự Giải 2026: Gia đình và sự nghiệp song hành",
			Slug:            "tu-vi-cu-giai-2026",
			Excerpt:         "Tử vi cung Cự Giải 2026 cho thấy một năm cân bằng giữa gia đình và sự nghiệp. Xem ngay dự đoán cho người sinh 21/6 - 22/7.",
			Content:         `<h2>Tử vi Cự Giải 2026</h2><p>Cự Giải bước vào năm 2026 với năng lượng ấm áp và bảo vệ. Mặt Trăng – hành tinh chủ quản – mang đến nhiều cơ hội củng cố mái ấm gia đình đồng thời thăng tiến trong sự nghiệp.</p><h3>Tình yêu</h3><p>Đây là năm tuyệt vời cho chuyện tình cảm. Người độc thân dễ tìm được người đồng điệu về tâm hồn. Các cặp đôi có thể tiến tới hôn nhân hoặc có thêm thành viên mới.</p><h3>Sự nghiệp</h3><p>Khả năng chăm sóc và đồng cảm giúp bạn được đồng nghiệp yêu quý. Vị trí quản lý nhóm hoặc dự án liên quan đến con người rất phù hợp. Quý 1 và quý 4 là giai đoạn thuận lợi nhất.</p><h3>Tài chính</h3><p>Tài chính ổn định. Nên ưu tiên tiết kiệm và đầu tư vào gia đình, nhà cửa. Tránh cho người khác vay mượn lớn trong tháng 7-8.</p><h3>Sức khỏe</h3><p>Dạ dày và hệ tiêu hóa cần chú ý. Ăn uống điều độ, tránh đồ cay nóng. Bơi lội và đi bộ là các hoạt động thể chất phù hợp.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tử vi Cự Giải 2026 - Gia đình và sự nghiệp",
			MetaDescription: "Xem tử vi Cự Giải 2026: tình yêu, sự nghiệp, tài chính. Dự đoán vận mệnh cho người sinh 21/6 - 22/7 trong năm mới.",
			ReadingTime:     5,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Cự Giải", "Tử vi 2026"},
		},
		{
			Title:           "Tử vi Sư Tử 2026: Tỏa sáng và chinh phục đỉnh cao",
			Slug:            "tu-vi-su-tu-2026",
			Excerpt:         "Năm 2026 là năm Sư Tử tỏa sáng rực rỡ. Tử vi chi tiết về tình yêu, sự nghiệp, tài chính cho người sinh 23/7 - 22/8.",
			Content:         `<h2>Tử vi Sư Tử 2026</h2><p>Sư Tử chào đón năm 2026 với nguồn năng lượng mãnh liệt. Mặt Trời – hành tinh chủ quản – chiếu sáng con đường sự nghiệp, giúp bạn đạt được những thành tựu đáng tự hào.</p><h3>Tình yêu</h3><p>Sư Tử thu hút mọi ánh nhìn trong năm nay. Tình yêu đến bất ngờ và mãnh liệt. Người có đôi cần cân bằng giữa cái tôi và sự nhượng bộ để mối quan hệ bền vững.</p><h3>Sự nghiệp</h3><p>Đây là năm để Sư Tử chinh phục đỉnh cao sự nghiệp. Khả năng lãnh đạo được công nhận, cơ hội được giao vị trí quan trọng. Lĩnh vực giải trí, nghệ thuật, quản lý đặc biệt thuận lợi.</p><h3>Tài chính</h3><p>Thu nhập tăng theo sự thăng tiến. Tuy nhiên, Sư Tử có xu hướng chi tiêu phóng khoáng. Hãy lập kế hoạch tài chính rõ ràng ngay từ đầu năm.</p><h3>Sức khỏe</h3><p>Tim mạch và lưng cần được chú ý. Tập cardio đều đặn, tránh ngồi quá lâu. Mùa hè là thời điểm cần bổ sung vitamin D.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tử vi Sư Tử 2026 - Tỏa sáng đỉnh cao",
			MetaDescription: "Tử vi Sư Tử 2026: dự đoán tình yêu, sự nghiệp, tài chính cho người sinh 23/7 - 22/8. Năm tỏa sáng và chinh phục.",
			ReadingTime:     5,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Sư Tử", "Tử vi 2026"},
		},
		{
			Title:           "Tử vi Xử Nữ 2026: Hoàn thiện bản thân và gặt hái thành công",
			Slug:            "tu-vi-xu-nu-2026",
			Excerpt:         "Cung Xử Nữ năm 2026 tập trung vào sự hoàn thiện và phát triển bản thân. Xem chi tiết tử vi cho người sinh 23/8 - 22/9.",
			Content:         `<h2>Tử vi Xử Nữ 2026</h2><p>Năm 2026 là năm Xử Nữ đạt được sự cân bằng hoàn hảo giữa công việc và cuộc sống. Sao Thủy mang đến trí tuệ sắc bén và khả năng phân tích xuất sắc.</p><h3>Tình yêu</h3><p>Xử Nữ bớt khó tính hơn trong năm nay, mở lòng đón nhận tình yêu. Người độc thân gặp được người chín chắn, phù hợp. Các cặp đôi cải thiện sự thấu hiểu lẫn nhau.</p><h3>Sự nghiệp</h3><p>Sự tỉ mỉ và cầu toàn là chìa khóa thành công. Các dự án đòi hỏi phân tích dữ liệu, nghiên cứu rất thuận lợi. Tháng 3 và tháng 9 có cơ hội thăng tiến.</p><h3>Tài chính</h3><p>Xử Nữ quản lý tài chính tốt, năm nay tài sản tích lũy tăng đáng kể. Nên đầu tư vào giáo dục và sức khỏe bản thân. Tránh cho vay không đảm bảo.</p><h3>Sức khỏe</h3><p>Hệ tiêu hóa và ruột cần chú ý. Ăn nhiều chất xơ, uống đủ nước. Tập yoga giúp giảm stress hiệu quả.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tử vi Xử Nữ 2026 - Hoàn thiện và thành công",
			MetaDescription: "Tử vi Xử Nữ 2026: tình yêu, sự nghiệp, tài chính cho người sinh 23/8 - 22/9. Năm hoàn thiện bản thân.",
			ReadingTime:     5,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Xử Nữ", "Tử vi 2026"},
		},
		{
			Title:           "Tử vi Thiên Bình 2026: Cân bằng và hài hòa trong mọi lĩnh vực",
			Slug:            "tu-vi-thien-binh-2026",
			Excerpt:         "Năm 2026 mang đến cho Thiên Bình sự hài hòa trong tình yêu và sự nghiệp. Dự đoán chi tiết cho người sinh 23/9 - 22/10.",
			Content:         `<h2>Tử vi Thiên Bình 2026</h2><p>Sao Mộc đi qua cung Thiên Bình trong năm 2026 mang đến may mắn và mở rộng trên mọi phương diện. Đây là năm đặc biệt thuận lợi cho các mối quan hệ.</p><h3>Tình yêu</h3><p>Thiên Bình thu hút tình yêu tự nhiên trong năm nay. Người độc thân dễ gặp được tri kỷ. Hôn nhân và cam kết lâu dài được ưu ái. Tháng 2 và tháng 10 là thời điểm vàng.</p><h3>Sự nghiệp</h3><p>Kỹ năng ngoại giao và thẩm mỹ là lợi thế lớn. Lĩnh vực luật, thiết kế, nghệ thuật, PR rất thuận lợi. Hợp tác kinh doanh mang lại thành công bất ngờ.</p><h3>Tài chính</h3><p>Tài chính cải thiện rõ rệt nhờ các mối quan hệ và đối tác. Thu nhập bổ sung từ công việc sáng tạo. Nên đầu tư vào bản thân và các mối quan hệ.</p><h3>Sức khỏe</h3><p>Thận và lưng dưới cần được chú ý. Uống đủ nước, hạn chế muối. Nhảy múa hoặc pilates là hoạt động thể chất lý tưởng.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tử vi Thiên Bình 2026 - Cân bằng hài hòa",
			MetaDescription: "Tử vi Thiên Bình 2026: tình yêu, sự nghiệp, tài chính cho người sinh 23/9 - 22/10. Năm may mắn với Sao Mộc.",
			ReadingTime:     5,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Thiên Bình", "Tử vi 2026"},
		},
		{
			Title:           "Tử vi Bọ Cạp 2026: Biến đổi sâu sắc và tái sinh",
			Slug:            "tu-vi-bo-cap-2026",
			Excerpt:         "Cung Bọ Cạp năm 2026 trải qua quá trình chuyển đổi mạnh mẽ. Xem dự đoán tử vi cho người sinh 23/10 - 21/11.",
			Content:         `<h2>Tử vi Bọ Cạp 2026</h2><p>Năm 2026 đánh dấu sự biến đổi sâu sắc cho Bọ Cạp. Sao Diêm Vương tiếp tục tác động mạnh, mang đến cơ hội tái sinh và đổi mới hoàn toàn.</p><h3>Tình yêu</h3><p>Tình yêu sâu sắc và đam mê. Bọ Cạp tìm kiếm sự kết nối tâm hồn hơn là bề ngoài. Các mối quan hệ không thực sự có thể kết thúc để nhường chỗ cho điều tốt đẹp hơn.</p><h3>Sự nghiệp</h3><p>Khả năng nghiên cứu và phân tích sắc bén. Lĩnh vực y tế, tâm lý, điều tra, tài chính rất phù hợp. Quý 2 mang đến bước ngoặt trong sự nghiệp.</p><h3>Tài chính</h3><p>Tài chính có biến động nhưng xu hướng chung là tích cực. Đầu tư vào bất động sản hoặc cổ phiếu dài hạn mang lại lợi nhuận. Tránh đánh bạc hoặc đầu cơ.</p><h3>Sức khỏe</h3><p>Hệ sinh sản và bàng quang cần chú ý. Tập thể dục đều đặn, đặc biệt bơi lội. Thiền định giúp cân bằng cảm xúc.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tử vi Bọ Cạp 2026 - Biến đổi và tái sinh",
			MetaDescription: "Tử vi Bọ Cạp 2026: tình yêu, sự nghiệp, tài chính cho người sinh 23/10 - 21/11. Năm biến đổi mạnh mẽ.",
			ReadingTime:     5,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Bọ Cạp", "Tử vi 2026"},
		},
		{
			Title:           "Tử vi Nhân Mã 2026: Khám phá và mở rộng chân trời",
			Slug:            "tu-vi-nhan-ma-2026",
			Excerpt:         "Nhân Mã năm 2026 khao khát khám phá và trải nghiệm mới. Tử vi tình yêu, sự nghiệp, tài chính cho người sinh 22/11 - 21/12.",
			Content:         `<h2>Tử vi Nhân Mã 2026</h2><p>Năm 2026 kích thích tinh thần phiêu lưu của Nhân Mã. Sao Mộc – hành tinh chủ quản – ở vị trí tốt, mở ra cánh cửa cho du lịch, học hỏi và phát triển tinh thần.</p><h3>Tình yêu</h3><p>Nhân Mã gặp gỡ người thú vị từ nền văn hóa khác hoặc qua du lịch. Tình yêu mang tính phiêu lưu và kích thích. Cặp đôi nên cùng nhau khám phá điều mới.</p><h3>Sự nghiệp</h3><p>Cơ hội làm việc ở nước ngoài hoặc với đối tác quốc tế. Lĩnh vực giáo dục, du lịch, xuất bản, triết học thuận lợi. Quý 3 là thời điểm mở rộng sự nghiệp.</p><h3>Tài chính</h3><p>Thu nhập tăng từ hoạt động quốc tế hoặc trực tuyến. Tuy nhiên, chi tiêu cho du lịch và trải nghiệm cũng tăng. Cân bằng giữa hưởng thụ và tiết kiệm.</p><h3>Sức khỏe</h3><p>Hông và đùi cần chú ý. Chạy bộ, cưỡi ngựa, leo núi là hoạt động phù hợp. Tránh ăn uống quá độ khi đi du lịch.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tử vi Nhân Mã 2026 - Khám phá chân trời mới",
			MetaDescription: "Tử vi Nhân Mã 2026: dự đoán tình yêu, sự nghiệp, tài chính cho người sinh 22/11 - 21/12. Năm phiêu lưu.",
			ReadingTime:     5,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Nhân Mã", "Tử vi 2026"},
		},
		{
			Title:           "Tử vi Ma Kết 2026: Kiên trì xây dựng đế chế riêng",
			Slug:            "tu-vi-ma-ket-2026",
			Excerpt:         "Ma Kết năm 2026 tiếp tục xây dựng nền tảng vững chắc cho tương lai. Dự đoán tử vi cho người sinh 22/12 - 19/1.",
			Content:         `<h2>Tử vi Ma Kết 2026</h2><p>Năm 2026 là năm Ma Kết gặt hái thành quả từ những nỗ lực bền bỉ. Sao Thổ – hành tinh chủ quản – trao thưởng cho sự kiên trì và kỷ luật.</p><h3>Tình yêu</h3><p>Ma Kết nghiêm túc hơn trong chuyện tình cảm. Người độc thân tìm kiếm mối quan hệ lâu dài, ổn định. Các cặp đôi có thể tiến tới hôn nhân hoặc mua nhà chung.</p><h3>Sự nghiệp</h3><p>Thăng tiến chắc chắn nhờ năng lực và sự cam kết. Vị trí quản lý cấp cao trong tầm tay. Lĩnh vực tài chính, xây dựng, chính phủ rất thuận lợi. Nửa cuối năm là đỉnh cao.</p><h3>Tài chính</h3><p>Tài chính tăng trưởng bền vững. Bất động sản và vàng là kênh đầu tư an toàn. Nên xây dựng quỹ dự phòng cho tương lai.</p><h3>Sức khỏe</h3><p>Xương khớp và da cần chú ý. Bổ sung canxi và collagen. Tập yoga hoặc bơi lội giúp duy trì sự dẻo dai.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tử vi Ma Kết 2026 - Xây dựng đế chế",
			MetaDescription: "Tử vi Ma Kết 2026: tình yêu, sự nghiệp, tài chính cho người sinh 22/12 - 19/1. Năm gặt hái thành quả.",
			ReadingTime:     5,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Ma Kết", "Tử vi 2026"},
		},
		{
			Title:           "Tử vi Bảo Bình 2026: Sáng tạo đột phá và tự do",
			Slug:            "tu-vi-bao-binh-2026",
			Excerpt:         "Bảo Bình năm 2026 bùng nổ sáng tạo và khao khát tự do. Xem tử vi chi tiết cho người sinh 20/1 - 18/2.",
			Content:         `<h2>Tử vi Bảo Bình 2026</h2><p>Năm 2026 là năm Bảo Bình thể hiện cá tính và sự sáng tạo đột phá. Sao Thiên Vương tiếp tục kích thích tư duy tiến bộ và mong muốn thay đổi thế giới.</p><h3>Tình yêu</h3><p>Bảo Bình tìm kiếm tình yêu trí tuệ, kết nối tinh thần. Người độc thân gặp đối tác qua hoạt động cộng đồng hoặc công nghệ. Cặp đôi cần tôn trọng không gian riêng của nhau.</p><h3>Sự nghiệp</h3><p>Công nghệ, khoa học, hoạt động xã hội là lĩnh vực tỏa sáng. Ý tưởng đột phá được đánh giá cao. Khởi nghiệp hoặc làm việc tự do rất thuận lợi. Quý 1 có cơ hội lớn.</p><h3>Tài chính</h3><p>Thu nhập có thể đến từ công nghệ, tiền điện tử hoặc các dự án sáng tạo. Cần đa dạng hóa nguồn thu. Tránh đầu tư quá mạo hiểm.</p><h3>Sức khỏe</h3><p>Mắt cá chân và hệ tuần hoàn cần chú ý. Tập aerobic giúp cải thiện tuần hoàn máu. Tránh ngồi lâu trước máy tính.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tử vi Bảo Bình 2026 - Sáng tạo đột phá",
			MetaDescription: "Tử vi Bảo Bình 2026: tình yêu, sự nghiệp, tài chính cho người sinh 20/1 - 18/2. Năm sáng tạo và tự do.",
			ReadingTime:     5,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Bảo Bình", "Tử vi 2026"},
		},
		{
			Title:           "Tử vi Song Ngư 2026: Trực giác dẫn lối thành công",
			Slug:            "tu-vi-song-ngu-2026",
			Excerpt:         "Song Ngư năm 2026 phát huy trực giác và sự nhạy cảm. Tử vi tình yêu, sự nghiệp, tài chính cho người sinh 19/2 - 20/3.",
			Content:         `<h2>Tử vi Song Ngư 2026</h2><p>Năm 2026, Song Ngư được Sao Hải Vương hỗ trợ, trực giác và sức sáng tạo đạt đỉnh cao. Đây là năm để biến giấc mơ thành hiện thực.</p><h3>Tình yêu</h3><p>Song Ngư lãng mạn và dễ tổn thương nhưng năm nay tình yêu đến nhẹ nhàng và chân thành. Người độc thân gặp người hiểu tâm hồn mình. Các cặp đôi thêm gắn bó.</p><h3>Sự nghiệp</h3><p>Nghệ thuật, âm nhạc, điện ảnh, chăm sóc sức khỏe là lĩnh vực thuận lợi. Sự nhạy cảm giúp bạn hiểu khách hàng và đồng nghiệp. Quý 2 mang đến cơ hội đặc biệt.</p><h3>Tài chính</h3><p>Tài chính ổn định dù không có đột phá lớn. Nên thận trọng khi cho vay hoặc đầu tư theo cảm xúc. Tháng 6 và tháng 11 có tin vui về tiền bạc.</p><h3>Sức khỏe</h3><p>Bàn chân và hệ miễn dịch cần chú ý. Tránh tiếp xúc với chất kích thích. Thiền định, yoga, bơi lội rất tốt cho Song Ngư.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tử vi Song Ngư 2026 - Trực giác dẫn lối",
			MetaDescription: "Tử vi Song Ngư 2026: tình yêu, sự nghiệp, tài chính cho người sinh 19/2 - 20/3. Năm của trực giác và sáng tạo.",
			ReadingTime:     5,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Song Ngư", "Tử vi 2026"},
		},

		// === ĐẶC ĐIỂM TÍNH CÁCH 12 CUNG HOÀNG ĐẠO ===
		{
			Title:       "Đặc điểm tính cách cung Bạch Dương: Mạnh mẽ, năng động và quyết đoán",
			Slug:        "dac-diem-tinh-cach-bach-duong",
			Excerpt:     "Khám phá đặc điểm tính cách cung Bạch Dương – người tiên phong đầy nhiệt huyết. Ưu điểm, nhược điểm và cách cải thiện bản thân.",
			Content:     `<h2>Tính cách cung Bạch Dương</h2><p>Bạch Dương (21/3 - 19/4) là cung đầu tiên trong hoàng đạo, tượng trưng cho sự khởi đầu và năng lượng tiên phong. Người Bạch Dương nổi bật với sự mạnh mẽ, quyết đoán và tinh thần dũng cảm.</p><h3>Ưu điểm</h3><ul><li><strong>Dũng cảm:</strong> Không ngại đối mặt thử thách</li><li><strong>Năng động:</strong> Luôn tràn đầy năng lượng</li><li><strong>Trung thực:</strong> Thẳng thắn, không che giấu</li><li><strong>Lãnh đạo:</strong> Bẩm sinh có khả năng dẫn dắt</li></ul><h3>Nhược điểm</h3><ul><li>Nóng nảy, thiếu kiên nhẫn</li><li>Bốc đồng, hay hành động trước suy nghĩ</li><li>Ích kỷ khi tập trung mục tiêu</li></ul><h3>Trong tình yêu</h3><p>Bạch Dương yêu mãnh liệt, chủ động theo đuổi. Cần người bạn đời biết chấp nhận và cân bằng.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Đặc điểm tính cách cung Bạch Dương chi tiết nhất",
			MetaDescription: "Tìm hiểu tính cách cung Bạch Dương: ưu nhược điểm, tình yêu, sự nghiệp. Đặc trưng người sinh 21/3 - 19/4.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Bạch Dương"},
		},
		{
			Title:       "Đặc điểm tính cách cung Kim Ngưu: Kiên định, thực tế và đáng tin cậy",
			Slug:        "dac-diem-tinh-cach-kim-nguu",
			Excerpt:     "Tính cách cung Kim Ngưu – những người kiên định nhất hoàng đạo. Ưu điểm, nhược điểm và bí mật về cung Kim Ngưu.",
			Content:     `<h2>Tính cách cung Kim Ngưu</h2><p>Kim Ngưu (20/4 - 20/5) thuộc nguyên tố Đất, nổi tiếng với sự kiên định và thực tế. Họ là những người đáng tin cậy, yêu thích sự ổn định và vẻ đẹp cuộc sống.</p><h3>Ưu điểm</h3><ul><li><strong>Kiên nhẫn:</strong> Bền bỉ theo đuổi mục tiêu</li><li><strong>Đáng tin:</strong> Luôn giữ lời hứa</li><li><strong>Thẩm mỹ:</strong> Yêu cái đẹp và nghệ thuật</li><li><strong>Thực tế:</strong> Biết cân nhắc thiệt hơn</li></ul><h3>Nhược điểm</h3><ul><li>Cố chấp, khó thay đổi quan điểm</li><li>Ghen tuông và chiếm hữu</li><li>Lười biếng khi ở vùng an toàn</li></ul><h3>Trong tình yêu</h3><p>Kim Ngưu trung thành và lãng mạn theo cách thiết thực. Họ thể hiện tình yêu qua hành động chăm sóc hàng ngày hơn là lời nói hoa mỹ.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Đặc điểm tính cách cung Kim Ngưu chi tiết",
			MetaDescription: "Khám phá tính cách Kim Ngưu: kiên định, thực tế, đáng tin cậy. Ưu nhược điểm và tình yêu của người sinh 20/4 - 20/5.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Kim Ngưu"},
		},
		{
			Title:       "Đặc điểm tính cách cung Song Tử: Linh hoạt, thông minh và đa tài",
			Slug:        "dac-diem-tinh-cach-song-tu",
			Excerpt:     "Tính cách Song Tử – cung hoàng đạo đa diện nhất. Khám phá hai mặt của Song Tử và cách họ tỏa sáng.",
			Content:     `<h2>Tính cách cung Song Tử</h2><p>Song Tử (21/5 - 20/6) thuộc nguyên tố Khí, nổi tiếng với sự linh hoạt và khả năng giao tiếp xuất sắc. Họ như một cuốn bách khoa toàn thư sống.</p><h3>Ưu điểm</h3><ul><li><strong>Thông minh:</strong> Học hỏi nhanh, đa tài</li><li><strong>Giao tiếp:</strong> Nói chuyện cuốn hút</li><li><strong>Linh hoạt:</strong> Thích nghi mọi hoàn cảnh</li><li><strong>Vui vẻ:</strong> Mang lại niềm vui cho mọi người</li></ul><h3>Nhược điểm</h3><ul><li>Hay thay đổi, thiếu kiên trì</li><li>Hời hợt, không đi sâu vào việc gì</li><li>Lo lắng quá mức</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Đặc điểm tính cách cung Song Tử",
			MetaDescription: "Tính cách Song Tử: linh hoạt, thông minh, đa tài. Khám phá ưu nhược điểm và bí mật của người sinh 21/5 - 20/6.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Song Tử"},
		},
		{
			Title:       "Đặc điểm tính cách cung Cự Giải: Nhạy cảm, chu đáo và giàu tình cảm",
			Slug:        "dac-diem-tinh-cach-cu-giai",
			Excerpt:     "Cung Cự Giải – người bảo vệ gia đình. Tìm hiểu tính cách nhạy cảm và đầy yêu thương của người sinh 21/6 - 22/7.",
			Content:     `<h2>Tính cách cung Cự Giải</h2><p>Cự Giải (21/6 - 22/7) thuộc nguyên tố Nước, được Mặt Trăng cai quản. Họ nổi tiếng với trái tim nhạy cảm và bản năng bảo vệ gia đình mạnh mẽ.</p><h3>Ưu điểm</h3><ul><li><strong>Chu đáo:</strong> Luôn quan tâm đến người khác</li><li><strong>Trung thành:</strong> Hết lòng với gia đình</li><li><strong>Trực giác:</strong> Nhạy cảm, hiểu lòng người</li></ul><h3>Nhược điểm</h3><ul><li>Nhạy cảm quá mức, dễ bị tổn thương</li><li>Hay tâm trạng thất thường</li><li>Bám víu quá khứ</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Đặc điểm tính cách cung Cự Giải chi tiết",
			MetaDescription: "Tính cách Cự Giải: nhạy cảm, chu đáo, yêu gia đình. Ưu nhược điểm của người sinh 21/6 - 22/7.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Cự Giải"},
		},
		{
			Title:       "Đặc điểm tính cách cung Sư Tử: Tự tin, hào phóng và đầy quyền lực",
			Slug:        "dac-diem-tinh-cach-su-tu",
			Excerpt:     "Sư Tử – vị vua của hoàng đạo. Khám phá tính cách tự tin, hào phóng nhưng cũng đầy kiêu hãnh của cung Sư Tử.",
			Content:     `<h2>Tính cách cung Sư Tử</h2><p>Sư Tử (23/7 - 22/8) thuộc nguyên tố Lửa, được Mặt Trời cai quản. Họ tỏa sáng ở bất cứ đâu với sự tự tin và phong thái đầy quyền lực.</p><h3>Ưu điểm</h3><ul><li><strong>Tự tin:</strong> Phong thái vương giả</li><li><strong>Hào phóng:</strong> Rộng lượng với mọi người</li><li><strong>Trung thành:</strong> Bảo vệ người thân yêu</li></ul><h3>Nhược điểm</h3><ul><li>Kiêu ngạo, thích được khen</li><li>Độc đoán, muốn kiểm soát</li><li>Dễ bị tổn thương khi bị phớt lờ</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Đặc điểm tính cách cung Sư Tử",
			MetaDescription: "Tính cách Sư Tử: tự tin, hào phóng, quyền lực. Khám phá ưu nhược điểm của người sinh 23/7 - 22/8.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Sư Tử"},
		},
		{
			Title:       "Đặc điểm tính cách cung Xử Nữ: Cầu toàn, chỉn chu và đáng tin cậy",
			Slug:        "dac-diem-tinh-cach-xu-nu",
			Excerpt:     "Xử Nữ – cung hoàng đạo cầu toàn nhất. Tìm hiểu sự chỉn chu và trí tuệ phân tích của người sinh 23/8 - 22/9.",
			Content:     `<h2>Tính cách cung Xử Nữ</h2><p>Xử Nữ (23/8 - 22/9) thuộc nguyên tố Đất, được Sao Thủy cai quản. Họ nổi tiếng với sự tỉ mỉ, cầu toàn và khả năng phân tích logic vượt trội.</p><h3>Ưu điểm</h3><ul><li><strong>Tỉ mỉ:</strong> Chú ý từng chi tiết nhỏ</li><li><strong>Đáng tin:</strong> Hoàn thành mọi cam kết</li><li><strong>Thông minh:</strong> Phân tích sắc bén</li></ul><h3>Nhược điểm</h3><ul><li>Cầu toàn đến mức khó tính</li><li>Hay lo lắng và tự phê bình</li><li>Khó biểu lộ cảm xúc</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Đặc điểm tính cách cung Xử Nữ",
			MetaDescription: "Tính cách Xử Nữ: cầu toàn, chỉn chu, thông minh. Ưu nhược điểm của người sinh 23/8 - 22/9.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Xử Nữ"},
		},
		{
			Title:       "Đặc điểm tính cách cung Thiên Bình: Hài hòa, công bằng và thanh lịch",
			Slug:        "dac-diem-tinh-cach-thien-binh",
			Excerpt:     "Thiên Bình – biểu tượng của sự cân bằng. Khám phá tính cách hài hòa và khiếu thẩm mỹ của người sinh 23/9 - 22/10.",
			Content:     `<h2>Tính cách cung Thiên Bình</h2><p>Thiên Bình (23/9 - 22/10) thuộc nguyên tố Khí, được Sao Kim cai quản. Họ là hiện thân của sự cân bằng, hài hòa và vẻ đẹp trong cuộc sống.</p><h3>Ưu điểm</h3><ul><li><strong>Công bằng:</strong> Luôn tìm sự cân bằng</li><li><strong>Thanh lịch:</strong> Khiếu thẩm mỹ cao</li><li><strong>Ngoại giao:</strong> Giải quyết xung đột tài tình</li></ul><h3>Nhược điểm</h3><ul><li>Do dự, khó đưa ra quyết định</li><li>Tránh đối đầu bằng mọi giá</li><li>Phụ thuộc vào ý kiến người khác</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Đặc điểm tính cách cung Thiên Bình",
			MetaDescription: "Tính cách Thiên Bình: hài hòa, công bằng, thanh lịch. Ưu nhược điểm của người sinh 23/9 - 22/10.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Thiên Bình"},
		},
		{
			Title:       "Đặc điểm tính cách cung Bọ Cạp: Bí ẩn, mãnh liệt và sâu sắc",
			Slug:        "dac-diem-tinh-cach-bo-cap",
			Excerpt:     "Bọ Cạp – cung hoàng đạo bí ẩn nhất. Tìm hiểu chiều sâu nội tâm và sức mạnh tinh thần của người sinh 23/10 - 21/11.",
			Content:     `<h2>Tính cách cung Bọ Cạp</h2><p>Bọ Cạp (23/10 - 21/11) thuộc nguyên tố Nước, được Sao Diêm Vương cai quản. Họ là cung hoàng đạo sâu sắc và mãnh liệt nhất, mang trong mình sức mạnh chuyển hóa.</p><h3>Ưu điểm</h3><ul><li><strong>Quyết tâm:</strong> Không bỏ cuộc khi đã quyết</li><li><strong>Trung thành:</strong> Bảo vệ người thân tuyệt đối</li><li><strong>Sáng suốt:</strong> Nhìn thấu bản chất sự việc</li></ul><h3>Nhược điểm</h3><ul><li>Ghen tuông và thù dai</li><li>Bí mật, khó tin người</li><li>Có xu hướng kiểm soát</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Đặc điểm tính cách cung Bọ Cạp",
			MetaDescription: "Tính cách Bọ Cạp: bí ẩn, mãnh liệt, sâu sắc. Ưu nhược điểm của người sinh 23/10 - 21/11.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Bọ Cạp"},
		},
		{
			Title:       "Đặc điểm tính cách cung Nhân Mã: Tự do, lạc quan và phiêu lưu",
			Slug:        "dac-diem-tinh-cach-nhan-ma",
			Excerpt:     "Nhân Mã – cung hoàng đạo của sự tự do. Khám phá tinh thần phiêu lưu và triết lý sống của người sinh 22/11 - 21/12.",
			Content:     `<h2>Tính cách cung Nhân Mã</h2><p>Nhân Mã (22/11 - 21/12) thuộc nguyên tố Lửa, được Sao Mộc cai quản. Họ là những nhà phiêu lưu bẩm sinh, luôn khao khát tự do và khám phá.</p><h3>Ưu điểm</h3><ul><li><strong>Lạc quan:</strong> Luôn nhìn về phía tích cực</li><li><strong>Trung thực:</strong> Nói thẳng, nói thật</li><li><strong>Triết lý:</strong> Tư duy sâu rộng</li></ul><h3>Nhược điểm</h3><ul><li>Thiếu tế nhị, vô tâm</li><li>Không kiên nhẫn, hay nhàm chán</li><li>Hứa nhiều nhưng khó giữ lời</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Đặc điểm tính cách cung Nhân Mã",
			MetaDescription: "Tính cách Nhân Mã: tự do, lạc quan, phiêu lưu. Ưu nhược điểm của người sinh 22/11 - 21/12.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Nhân Mã"},
		},
		{
			Title:       "Đặc điểm tính cách cung Ma Kết: Tham vọng, kỷ luật và bền bỉ",
			Slug:        "dac-diem-tinh-cach-ma-ket",
			Excerpt:     "Ma Kết – nhà chinh phục kiên cường. Tìm hiểu tính cách tham vọng và kỷ luật của người sinh 22/12 - 19/1.",
			Content:     `<h2>Tính cách cung Ma Kết</h2><p>Ma Kết (22/12 - 19/1) thuộc nguyên tố Đất, được Sao Thổ cai quản. Họ là những người tham vọng nhất hoàng đạo, kiên trì leo lên đỉnh cao bằng nỗ lực bền bỉ.</p><h3>Ưu điểm</h3><ul><li><strong>Kỷ luật:</strong> Tự giác và có trách nhiệm</li><li><strong>Tham vọng:</strong> Luôn đặt mục tiêu cao</li><li><strong>Thực tế:</strong> Không mơ mộng viển vông</li></ul><h3>Nhược điểm</h3><ul><li>Cứng nhắc, bảo thủ</li><li>Lạnh lùng, khó gần</li><li>Workaholic, quên chăm sóc bản thân</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Đặc điểm tính cách cung Ma Kết",
			MetaDescription: "Tính cách Ma Kết: tham vọng, kỷ luật, bền bỉ. Ưu nhược điểm của người sinh 22/12 - 19/1.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Ma Kết"},
		},
		{
			Title:       "Đặc điểm tính cách cung Bảo Bình: Sáng tạo, độc lập và nhân đạo",
			Slug:        "dac-diem-tinh-cach-bao-binh",
			Excerpt:     "Bảo Bình – nhà cách mạng của hoàng đạo. Khám phá tính cách độc đáo và tư duy tiến bộ của người sinh 20/1 - 18/2.",
			Content:     `<h2>Tính cách cung Bảo Bình</h2><p>Bảo Bình (20/1 - 18/2) thuộc nguyên tố Khí, được Sao Thiên Vương cai quản. Họ là những người đi trước thời đại, với tư duy đột phá và lòng nhân đạo.</p><h3>Ưu điểm</h3><ul><li><strong>Sáng tạo:</strong> Tư duy khác biệt</li><li><strong>Nhân đạo:</strong> Quan tâm cộng đồng</li><li><strong>Độc lập:</strong> Không chạy theo đám đông</li></ul><h3>Nhược điểm</h3><ul><li>Xa cách cảm xúc, khó gần</li><li>Bướng bỉnh, cố chấp với ý tưởng</li><li>Hay thay đổi bất ngờ</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Đặc điểm tính cách cung Bảo Bình",
			MetaDescription: "Tính cách Bảo Bình: sáng tạo, độc lập, nhân đạo. Ưu nhược điểm của người sinh 20/1 - 18/2.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Bảo Bình"},
		},
		{
			Title:       "Đặc điểm tính cách cung Song Ngư: Lãng mạn, nhạy cảm và giàu trí tưởng tượng",
			Slug:        "dac-diem-tinh-cach-song-ngu",
			Excerpt:     "Song Ngư – cung hoàng đạo giàu cảm xúc nhất. Tìm hiểu sự lãng mạn và trực giác phi thường của người sinh 19/2 - 20/3.",
			Content:     `<h2>Tính cách cung Song Ngư</h2><p>Song Ngư (19/2 - 20/3) thuộc nguyên tố Nước, được Sao Hải Vương cai quản. Họ là những người giàu cảm xúc nhất hoàng đạo, sống bằng trực giác và trí tưởng tượng.</p><h3>Ưu điểm</h3><ul><li><strong>Đồng cảm:</strong> Thấu hiểu nỗi đau người khác</li><li><strong>Sáng tạo:</strong> Trí tưởng tượng phong phú</li><li><strong>Hiền lành:</strong> Không muốn làm tổn thương ai</li></ul><h3>Nhược điểm</h3><ul><li>Dễ bị ảnh hưởng bởi cảm xúc người khác</li><li>Hay mơ mộng, xa rời thực tế</li><li>Thiếu quyết đoán</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Đặc điểm tính cách cung Song Ngư",
			MetaDescription: "Tính cách Song Ngư: lãng mạn, nhạy cảm, giàu tưởng tượng. Ưu nhược điểm của người sinh 19/2 - 20/3.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Cung hoàng đạo", "Song Ngư"},
		},

		// === CUNG HOÀNG ĐẠO VÀ TÌNH YÊU ===
		{
			Title:       "Bạch Dương trong tình yêu: Đam mê, chinh phục và cháy bỏng",
			Slug:        "bach-duong-trong-tinh-yeu",
			Excerpt:     "Tìm hiểu cung Bạch Dương khi yêu: cách thể hiện tình cảm, cung hoàng đạo phù hợp và bí quyết giữ lửa yêu thương.",
			Content:     `<h2>Bạch Dương khi yêu</h2><p>Khi yêu, Bạch Dương là người đam mê và chủ động. Họ không ngại theo đuổi và chinh phục người mình thích bằng mọi cách.</p><h3>Cách thể hiện tình yêu</h3><ul><li>Chủ động tỏ tình, không úp mở</li><li>Bảo vệ người yêu bằng mọi giá</li><li>Thích tạo bất ngờ lãng mạn</li><li>Ghen tuông nhưng cũng nhanh hết giận</li></ul><h3>Cung hoàng đạo phù hợp</h3><p><strong>Rất hợp:</strong> Sư Tử, Nhân Mã, Song Tử<br><strong>Khá hợp:</strong> Bảo Bình, Thiên Bình<br><strong>Cần nỗ lực:</strong> Cự Giải, Ma Kết</p><h3>Bí quyết yêu Bạch Dương</h3><ul><li>Cho họ không gian tự do</li><li>Luôn giữ sự mới mẻ</li><li>Trung thực và thẳng thắn</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Bạch Dương trong tình yêu - Đặc điểm và cung hợp",
			MetaDescription: "Bạch Dương khi yêu: đam mê, chinh phục. Cung hoàng đạo phù hợp và bí quyết giữ lửa tình yêu cho Bạch Dương.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Bạch Dương", "Tình yêu"},
		},
		{
			Title:       "Kim Ngưu trong tình yêu: Trung thành, lãng mạn và kiên nhẫn",
			Slug:        "kim-nguu-trong-tinh-yeu",
			Excerpt:     "Kim Ngưu khi yêu là người trung thành nhất. Tìm hiểu cách Kim Ngưu yêu, cung phù hợp và cách chinh phục trái tim họ.",
			Content:     `<h2>Kim Ngưu khi yêu</h2><p>Kim Ngưu yêu chậm rãi nhưng sâu sắc. Họ không dễ rung động nhưng một khi đã yêu thì vô cùng trung thành và tận tâm.</p><h3>Cách thể hiện tình yêu</h3><ul><li>Chăm sóc bằng hành động thiết thực</li><li>Nấu ăn, tặng quà có giá trị</li><li>Luôn ở bên khi cần</li><li>Xây dựng tương lai ổn định</li></ul><h3>Cung hoàng đạo phù hợp</h3><p><strong>Rất hợp:</strong> Xử Nữ, Ma Kết, Cự Giải<br><strong>Khá hợp:</strong> Song Ngư, Bọ Cạp<br><strong>Cần nỗ lực:</strong> Sư Tử, Bảo Bình</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Kim Ngưu trong tình yêu - Trung thành và lãng mạn",
			MetaDescription: "Kim Ngưu khi yêu: trung thành, lãng mạn. Cung phù hợp và bí quyết chinh phục trái tim Kim Ngưu.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Kim Ngưu", "Tình yêu"},
		},
		{
			Title:       "Song Tử trong tình yêu: Thú vị, bất ngờ và đầy màu sắc",
			Slug:        "song-tu-trong-tinh-yeu",
			Excerpt:     "Song Tử khi yêu luôn mang đến sự thú vị và bất ngờ. Cung phù hợp, cách thể hiện tình cảm và bí quyết giữ chân Song Tử.",
			Content:     `<h2>Song Tử khi yêu</h2><p>Yêu Song Tử là một cuộc phiêu lưu không bao giờ nhàm chán. Họ yêu bằng trí tuệ và sự hài hước, mang đến bầu không khí tươi mới cho mối quan hệ.</p><h3>Cách thể hiện tình yêu</h3><ul><li>Trò chuyện và chia sẻ không ngừng</li><li>Tạo bất ngờ liên tục</li><li>Yêu bằng lời nói ngọt ngào</li></ul><h3>Cung hoàng đạo phù hợp</h3><p><strong>Rất hợp:</strong> Thiên Bình, Bảo Bình, Bạch Dương<br><strong>Khá hợp:</strong> Sư Tử, Nhân Mã<br><strong>Cần nỗ lực:</strong> Xử Nữ, Song Ngư</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Song Tử trong tình yêu - Thú vị và bất ngờ",
			MetaDescription: "Song Tử khi yêu: thú vị, đa sắc. Cung phù hợp và bí quyết giữ chân trái tim Song Tử.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Song Tử", "Tình yêu"},
		},
		{
			Title:       "Cự Giải trong tình yêu: Ấm áp, bao bọc và chân thành",
			Slug:        "cu-giai-trong-tinh-yeu",
			Excerpt:     "Cự Giải khi yêu là người ấm áp nhất. Tìm hiểu cách Cự Giải yêu, cung phù hợp và cách để được yêu thương trọn vẹn.",
			Content:     `<h2>Cự Giải khi yêu</h2><p>Cự Giải yêu bằng cả trái tim, chăm sóc và bao bọc người yêu như gia đình. Họ tìm kiếm sự gắn bó sâu sắc và cam kết lâu dài.</p><h3>Cách thể hiện tình yêu</h3><ul><li>Chăm sóc tận tình từ bữa ăn đến giấc ngủ</li><li>Ghi nhớ mọi chi tiết nhỏ</li><li>Xây dựng tổ ấm hạnh phúc</li></ul><h3>Cung hoàng đạo phù hợp</h3><p><strong>Rất hợp:</strong> Bọ Cạp, Song Ngư, Kim Ngưu<br><strong>Khá hợp:</strong> Xử Nữ, Ma Kết<br><strong>Cần nỗ lực:</strong> Bạch Dương, Thiên Bình</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Cự Giải trong tình yêu - Ấm áp và chân thành",
			MetaDescription: "Cự Giải khi yêu: ấm áp, bao bọc. Cung phù hợp và bí quyết để Cự Giải yêu thương trọn vẹn.",
			ReadingTime:     4,
			TagNames:        []string{"Tử vi", "Cự Giải", "Tình yêu"},
		},
		{
			Title:       "Sư Tử trong tình yêu: Hào phóng, lãng mạn và mãnh liệt",
			Slug:        "su-tu-trong-tinh-yeu",
			Excerpt:     "Sư Tử yêu hết mình và hào phóng trong tình cảm. Cung phù hợp và cách chinh phục trái tim Sư Tử kiêu hãnh.",
			Content:     `<h2>Sư Tử khi yêu</h2><p>Sư Tử yêu mãnh liệt và hào phóng. Họ muốn được ngưỡng mộ và đáp lại bằng sự trung thành tuyệt đối. Yêu Sư Tử như được sống trong một câu chuyện cổ tích.</p><h3>Cung hoàng đạo phù hợp</h3><p><strong>Rất hợp:</strong> Bạch Dương, Nhân Mã, Thiên Bình<br><strong>Khá hợp:</strong> Song Tử, Bảo Bình<br><strong>Cần nỗ lực:</strong> Bọ Cạp, Kim Ngưu</p>`,
			CategorySlug: "tu-vi",
			MetaTitle:    "Sư Tử trong tình yêu - Hào phóng và mãnh liệt",
			MetaDescription: "Sư Tử khi yêu: hào phóng, lãng mạn. Cung phù hợp và cách chinh phục Sư Tử kiêu hãnh.",
			ReadingTime: 4,
			TagNames:    []string{"Tử vi", "Sư Tử", "Tình yêu"},
		},
		{
			Title:       "Xử Nữ trong tình yêu: Tận tâm, chu đáo và lặng lẽ yêu thương",
			Slug:        "xu-nu-trong-tinh-yeu",
			Excerpt:     "Xử Nữ yêu bằng hành động hơn lời nói. Cung phù hợp và cách hiểu tình yêu thầm lặng nhưng sâu sắc của Xử Nữ.",
			Content:     `<h2>Xử Nữ khi yêu</h2><p>Xử Nữ thể hiện tình yêu qua sự chăm sóc tỉ mỉ và chu đáo. Họ không nói nhiều nhưng luôn ở bên bạn khi cần nhất.</p><h3>Cung hoàng đạo phù hợp</h3><p><strong>Rất hợp:</strong> Kim Ngưu, Ma Kết, Cự Giải<br><strong>Khá hợp:</strong> Bọ Cạp, Song Ngư<br><strong>Cần nỗ lực:</strong> Song Tử, Nhân Mã</p>`,
			CategorySlug: "tu-vi",
			MetaTitle:    "Xử Nữ trong tình yêu - Tận tâm và sâu sắc",
			MetaDescription: "Xử Nữ khi yêu: tận tâm, chu đáo. Cung phù hợp và bí quyết hiểu tình yêu lặng lẽ của Xử Nữ.",
			ReadingTime: 4,
			TagNames:    []string{"Tử vi", "Xử Nữ", "Tình yêu"},
		},
		{
			Title:       "Thiên Bình trong tình yêu: Lãng mạn, hài hòa và ngọt ngào",
			Slug:        "thien-binh-trong-tinh-yeu",
			Excerpt:     "Thiên Bình sinh ra để yêu. Cung phù hợp, cách yêu và bí quyết giữ mối quan hệ hài hòa với Thiên Bình.",
			Content:     `<h2>Thiên Bình khi yêu</h2><p>Thiên Bình là cung lãng mạn nhất hoàng đạo. Họ yêu cái đẹp và luôn mong muốn mối quan hệ hoàn hảo, hài hòa.</p><h3>Cung hoàng đạo phù hợp</h3><p><strong>Rất hợp:</strong> Song Tử, Bảo Bình, Sư Tử<br><strong>Khá hợp:</strong> Nhân Mã, Bạch Dương<br><strong>Cần nỗ lực:</strong> Cự Giải, Ma Kết</p>`,
			CategorySlug: "tu-vi",
			MetaTitle:    "Thiên Bình trong tình yêu - Lãng mạn và hài hòa",
			MetaDescription: "Thiên Bình khi yêu: lãng mạn, ngọt ngào. Cung phù hợp và bí quyết yêu Thiên Bình.",
			ReadingTime: 4,
			TagNames:    []string{"Tử vi", "Thiên Bình", "Tình yêu"},
		},
		{
			Title:       "Bọ Cạp trong tình yêu: Đam mê cháy bỏng và trung thành tuyệt đối",
			Slug:        "bo-cap-trong-tinh-yeu",
			Excerpt:     "Bọ Cạp yêu sâu sắc và mãnh liệt. Cung phù hợp và cách đối mặt với sự ghen tuông nổi tiếng của Bọ Cạp.",
			Content:     `<h2>Bọ Cạp khi yêu</h2><p>Bọ Cạp yêu đến tận cùng – hoặc tất cả hoặc không gì cả. Họ đòi hỏi sự trung thành tuyệt đối và đáp lại bằng một tình yêu sâu thẳm.</p><h3>Cung hoàng đạo phù hợp</h3><p><strong>Rất hợp:</strong> Cự Giải, Song Ngư, Xử Nữ<br><strong>Khá hợp:</strong> Ma Kết, Kim Ngưu<br><strong>Cần nỗ lực:</strong> Sư Tử, Bảo Bình</p>`,
			CategorySlug: "tu-vi",
			MetaTitle:    "Bọ Cạp trong tình yêu - Đam mê và trung thành",
			MetaDescription: "Bọ Cạp khi yêu: đam mê cháy bỏng, trung thành. Cung phù hợp và bí quyết yêu Bọ Cạp.",
			ReadingTime: 4,
			TagNames:    []string{"Tử vi", "Bọ Cạp", "Tình yêu"},
		},
		{
			Title:       "Nhân Mã trong tình yêu: Tự do, vui vẻ và đầy bất ngờ",
			Slug:        "nhan-ma-trong-tinh-yeu",
			Excerpt:     "Nhân Mã yêu tự do và phiêu lưu. Cung phù hợp, cách hiểu và giữ chân Nhân Mã trong tình yêu.",
			Content:     `<h2>Nhân Mã khi yêu</h2><p>Nhân Mã mang đến tiếng cười và sự phiêu lưu trong tình yêu. Họ không thích bị ràng buộc nhưng khi tìm đúng người, họ sẵn sàng cam kết.</p><h3>Cung hoàng đạo phù hợp</h3><p><strong>Rất hợp:</strong> Bạch Dương, Sư Tử, Thiên Bình<br><strong>Khá hợp:</strong> Bảo Bình, Song Tử<br><strong>Cần nỗ lực:</strong> Xử Nữ, Song Ngư</p>`,
			CategorySlug: "tu-vi",
			MetaTitle:    "Nhân Mã trong tình yêu - Tự do và bất ngờ",
			MetaDescription: "Nhân Mã khi yêu: tự do, vui vẻ. Cung phù hợp và bí quyết giữ chân Nhân Mã phiêu lưu.",
			ReadingTime: 4,
			TagNames:    []string{"Tử vi", "Nhân Mã", "Tình yêu"},
		},
		{
			Title:       "Ma Kết trong tình yêu: Nghiêm túc, cam kết và xây dựng tương lai",
			Slug:        "ma-ket-trong-tinh-yeu",
			Excerpt:     "Ma Kết yêu nghiêm túc và hướng đến tương lai lâu dài. Cung phù hợp và cách chinh phục trái tim Ma Kết.",
			Content:     `<h2>Ma Kết khi yêu</h2><p>Ma Kết yêu chậm nhưng chắc. Họ tìm kiếm đối tác có cùng tầm nhìn về tương lai và sẵn sàng cùng nhau xây dựng cuộc sống.</p><h3>Cung hoàng đạo phù hợp</h3><p><strong>Rất hợp:</strong> Kim Ngưu, Xử Nữ, Song Ngư<br><strong>Khá hợp:</strong> Bọ Cạp, Cự Giải<br><strong>Cần nỗ lực:</strong> Bạch Dương, Thiên Bình</p>`,
			CategorySlug: "tu-vi",
			MetaTitle:    "Ma Kết trong tình yêu - Cam kết và xây dựng",
			MetaDescription: "Ma Kết khi yêu: nghiêm túc, cam kết lâu dài. Cung phù hợp và bí quyết chinh phục Ma Kết.",
			ReadingTime: 4,
			TagNames:    []string{"Tử vi", "Ma Kết", "Tình yêu"},
		},
		{
			Title:       "Bảo Bình trong tình yêu: Độc đáo, trí tuệ và không theo khuôn mẫu",
			Slug:        "bao-binh-trong-tinh-yeu",
			Excerpt:     "Bảo Bình yêu khác biệt và không theo khuôn mẫu. Cung phù hợp và cách hiểu tình yêu trí tuệ của Bảo Bình.",
			Content:     `<h2>Bảo Bình khi yêu</h2><p>Bảo Bình yêu bằng trí tuệ trước cảm xúc. Họ cần kết nối tinh thần và tôn trọng không gian cá nhân. Tình yêu của họ không bình thường nhưng đáng quý.</p><h3>Cung hoàng đạo phù hợp</h3><p><strong>Rất hợp:</strong> Song Tử, Thiên Bình, Nhân Mã<br><strong>Khá hợp:</strong> Bạch Dương, Sư Tử<br><strong>Cần nỗ lực:</strong> Kim Ngưu, Bọ Cạp</p>`,
			CategorySlug: "tu-vi",
			MetaTitle:    "Bảo Bình trong tình yêu - Độc đáo và trí tuệ",
			MetaDescription: "Bảo Bình khi yêu: độc đáo, trí tuệ. Cung phù hợp và bí quyết hiểu Bảo Bình trong tình yêu.",
			ReadingTime: 4,
			TagNames:    []string{"Tử vi", "Bảo Bình", "Tình yêu"},
		},
		{
			Title:       "Song Ngư trong tình yêu: Lãng mạn tuyệt đối và hy sinh vô điều kiện",
			Slug:        "song-ngu-trong-tinh-yeu",
			Excerpt:     "Song Ngư yêu lãng mạn như trong truyện cổ tích. Cung phù hợp và cách bảo vệ trái tim nhạy cảm của Song Ngư.",
			Content:     `<h2>Song Ngư khi yêu</h2><p>Song Ngư yêu bằng cả linh hồn. Họ sẵn sàng hy sinh và cống hiến tất cả cho người mình yêu. Tình yêu của Song Ngư mang tính nghệ thuật và tâm linh.</p><h3>Cung hoàng đạo phù hợp</h3><p><strong>Rất hợp:</strong> Bọ Cạp, Cự Giải, Ma Kết<br><strong>Khá hợp:</strong> Kim Ngưu, Xử Nữ<br><strong>Cần nỗ lực:</strong> Song Tử, Nhân Mã</p>`,
			CategorySlug: "tu-vi",
			MetaTitle:    "Song Ngư trong tình yêu - Lãng mạn tuyệt đối",
			MetaDescription: "Song Ngư khi yêu: lãng mạn, hy sinh. Cung phù hợp và bí quyết bảo vệ trái tim Song Ngư.",
			ReadingTime: 4,
			TagNames:    []string{"Tử vi", "Song Ngư", "Tình yêu"},
		},

		// === TỬ VI 12 CON GIÁP ===
		{
			Title:       "Tử vi tuổi Tý 2026: Năm Bính Ngọ mang đến thử thách và cơ hội",
			Slug:        "tu-vi-tuoi-ty-2026",
			Excerpt:     "Người tuổi Tý năm 2026 gặp xung đối với Thái Tuế. Tìm hiểu cách hóa giải và tận dụng cơ hội trong năm Bính Ngọ.",
			Content:     `<h2>Tử vi tuổi Tý 2026</h2><p>Năm Bính Ngọ 2026, tuổi Tý xung Thái Tuế nên cần đặc biệt thận trọng. Tuy nhiên, với sự chuẩn bị kỹ lưỡng, bạn vẫn có thể biến thách thức thành cơ hội.</p><h3>Sự nghiệp</h3><p>Công việc có nhiều biến động, cần linh hoạt ứng biến. Tránh mạo hiểm trong quý 1 và quý 3. Quý 2 là thời điểm thuận lợi nhất.</p><h3>Tài chính</h3><p>Cần thắt chặt chi tiêu và tránh đầu tư lớn. Tiết kiệm là ưu tiên hàng đầu.</p><h3>Cách hóa giải</h3><ul><li>Đeo vật phẩm hợp mệnh</li><li>Tham gia hoạt động thiện nguyện</li><li>Đi lễ chùa đầu năm</li></ul>`,
			CategorySlug: "tu-vi",
			MetaTitle:    "Tử vi tuổi Tý 2026 - Vận mệnh năm Bính Ngọ",
			MetaDescription: "Tử vi tuổi Tý năm 2026: sự nghiệp, tài chính, tình yêu. Cách hóa giải xung Thái Tuế trong năm Bính Ngọ.",
			ReadingTime: 5,
			TagNames:    []string{"Tử vi", "Con giáp", "Tử vi 2026"},
		},
		{
			Title:       "Tử vi tuổi Sửu 2026: Vận hạn khởi sắc, tài lộc hanh thông",
			Slug:        "tu-vi-tuoi-suu-2026",
			Excerpt:     "Tuổi Sửu năm 2026 được Lục Hợp hỗ trợ, mang đến nhiều may mắn trong sự nghiệp và tài chính.",
			Content:     `<h2>Tử vi tuổi Sửu 2026</h2><p>Năm 2026, tuổi Sửu được hưởng nhiều may mắn nhờ Lục Hợp với Tý. Đây là năm thuận lợi để phát triển sự nghiệp và tích lũy tài sản.</p><h3>Sự nghiệp</h3><p>Công việc thuận lợi, có quý nhân phù trợ. Cơ hội thăng tiến và mở rộng kinh doanh rất tốt.</p><h3>Tài chính</h3><p>Tiền bạc vào đều, đầu tư sinh lời. Nên tận dụng năm tốt để tích lũy.</p>`,
			CategorySlug: "tu-vi",
			MetaTitle:    "Tử vi tuổi Sửu 2026 - Tài lộc hanh thông",
			MetaDescription: "Tử vi tuổi Sửu 2026: sự nghiệp khởi sắc, tài lộc dồi dào. Năm thuận lợi cho tuổi Sửu.",
			ReadingTime: 4,
			TagNames:    []string{"Tử vi", "Con giáp", "Tử vi 2026"},
		},
		{
			Title:       "Tử vi tuổi Dần 2026: Năm của sức mạnh và đột phá",
			Slug:        "tu-vi-tuoi-dan-2026",
			Excerpt:     "Người tuổi Dần năm 2026 tràn đầy năng lượng. Tử vi chi tiết về sự nghiệp, tài chính và tình duyên.",
			Content:     `<h2>Tử vi tuổi Dần 2026</h2><p>Tuổi Dần bước vào năm 2026 với sức mạnh và quyết tâm. Tam Hợp với Ngọ mang đến nguồn năng lượng tích cực, hỗ trợ đột phá trong mọi lĩnh vực.</p><h3>Sự nghiệp</h3><p>Đây là năm tuyệt vời để tuổi Dần khẳng định vị thế. Quý nhân phù trợ giúp vượt qua mọi trở ngại.</p><h3>Tài chính</h3><p>Thu nhập tăng đáng kể. Đầu tư dài hạn mang lại kết quả tốt.</p>`,
			CategorySlug: "tu-vi",
			MetaTitle:    "Tử vi tuổi Dần 2026 - Sức mạnh và đột phá",
			MetaDescription: "Tử vi tuổi Dần 2026: năm đột phá, tam hợp với Ngọ mang đến nhiều may mắn và thành công.",
			ReadingTime: 4,
			TagNames:    []string{"Tử vi", "Con giáp", "Tử vi 2026"},
		},
		{
			Title:       "Tử vi tuổi Mão 2026: Cẩn trọng và kiên nhẫn",
			Slug:        "tu-vi-tuoi-mao-2026",
			Excerpt:     "Tuổi Mão năm 2026 cần cẩn trọng do xung khắc. Lời khuyên và cách hóa giải cho năm mới.",
			Content:     `<h2>Tử vi tuổi Mão 2026</h2><p>Năm Bính Ngọ 2026, tuổi Mão gặp một số thử thách do vị trí Phá Thái Tuế. Kiên nhẫn và cẩn trọng là chìa khóa để vượt qua.</p><h3>Sự nghiệp</h3><p>Cần tránh thay đổi công việc trong nửa đầu năm. Tập trung củng cố những gì đang có.</p><h3>Lời khuyên</h3><ul><li>Giữ bình tĩnh trước mọi tình huống</li><li>Không nên mạo hiểm tài chính</li><li>Chăm sóc sức khỏe đều đặn</li></ul>`,
			CategorySlug: "tu-vi",
			MetaTitle:    "Tử vi tuổi Mão 2026 - Cẩn trọng và kiên nhẫn",
			MetaDescription: "Tử vi tuổi Mão 2026: cần cẩn trọng. Lời khuyên và cách hóa giải vận xấu trong năm Bính Ngọ.",
			ReadingTime: 4,
			TagNames:    []string{"Tử vi", "Con giáp", "Tử vi 2026"},
		},
		{
			Title:       "Tử vi tuổi Thìn 2026: Rồng bay cao, vạn sự hanh thông",
			Slug:        "tu-vi-tuoi-thin-2026",
			Excerpt:     "Tuổi Thìn năm 2026 gặp nhiều thuận lợi. Dự đoán chi tiết vận mệnh tình yêu, sự nghiệp, tài chính.",
			Content:     `<h2>Tử vi tuổi Thìn 2026</h2><p>Tuổi Thìn được phù trợ tốt trong năm 2026. Sự tương sinh giúp mọi việc hanh thông, đặc biệt trong sự nghiệp và tài chính.</p>`,
			CategorySlug: "tu-vi", MetaTitle: "Tử vi tuổi Thìn 2026", MetaDescription: "Tử vi tuổi Thìn 2026: hanh thông, thuận lợi.", ReadingTime: 4, TagNames: []string{"Tử vi", "Con giáp", "Tử vi 2026"},
		},
		{
			Title: "Tử vi tuổi Tỵ 2026: Cơ hội biến đổi và phát triển",
			Slug:  "tu-vi-tuoi-ty-ran-2026",
			Excerpt: "Tuổi Tỵ (Rắn) năm 2026 có nhiều biến chuyển tích cực. Xem chi tiết tử vi tài lộc, tình duyên.",
			Content: `<h2>Tử vi tuổi Tỵ 2026</h2><p>Năm 2026, tuổi Tỵ có nhiều cơ hội phát triển nhờ sự tương sinh với Ngọ. Đặc biệt thuận lợi cho việc học tập và mở rộng kiến thức.</p>`,
			CategorySlug: "tu-vi", MetaTitle: "Tử vi tuổi Tỵ 2026", MetaDescription: "Tử vi tuổi Tỵ 2026: biến đổi tích cực.", ReadingTime: 4, TagNames: []string{"Tử vi", "Con giáp", "Tử vi 2026"},
		},
		{
			Title: "Tử vi tuổi Ngọ 2026: Năm bản mệnh - thận trọng và tỉnh táo",
			Slug:  "tu-vi-tuoi-ngo-2026",
			Excerpt: "Năm 2026 Bính Ngọ là năm bản mệnh của tuổi Ngọ. Phạm Thái Tuế cần hóa giải để tránh vận xấu.",
			Content: `<h2>Tử vi tuổi Ngọ 2026</h2><p>Năm Bính Ngọ 2026 là năm bản mệnh, tuổi Ngọ Phạm Thái Tuế nên cần đặc biệt cẩn thận. Tuy nhiên không phải tất cả đều xấu, vẫn có cơ hội nếu biết tận dụng.</p><h3>Cách hóa giải</h3><ul><li>Đeo vòng tay ngọc phỉ thúy</li><li>Tham gia thiện nguyện</li><li>Kiêng xuất hành xa vào tháng 1 và tháng 7 âm lịch</li></ul>`,
			CategorySlug: "tu-vi", MetaTitle: "Tử vi tuổi Ngọ 2026 - Năm bản mệnh", MetaDescription: "Tử vi tuổi Ngọ 2026: năm phạm Thái Tuế, cần hóa giải.", ReadingTime: 5, IsFeatured: true, TagNames: []string{"Tử vi", "Con giáp", "Tử vi 2026"},
		},
		{
			Title: "Tử vi tuổi Mùi 2026: Hòa hợp và bình an",
			Slug:  "tu-vi-tuoi-mui-2026",
			Excerpt: "Tuổi Mùi năm 2026 được Lục Hợp hỗ trợ, mang đến sự hòa hợp trong mọi mối quan hệ.",
			Content: `<h2>Tử vi tuổi Mùi 2026</h2><p>Tuổi Mùi hưởng nhiều may mắn nhờ Lục Hợp. Đây là năm bình an, thuận lợi cho việc xây dựng gia đình và phát triển sự nghiệp ổn định.</p>`,
			CategorySlug: "tu-vi", MetaTitle: "Tử vi tuổi Mùi 2026", MetaDescription: "Tử vi tuổi Mùi 2026: hòa hợp, bình an.", ReadingTime: 4, TagNames: []string{"Tử vi", "Con giáp", "Tử vi 2026"},
		},
		{
			Title: "Tử vi tuổi Thân 2026: Năng động và nhiều cơ hội",
			Slug:  "tu-vi-tuoi-than-2026",
			Excerpt: "Tuổi Thân năm 2026 tràn đầy năng lượng. Cơ hội kinh doanh và thăng tiến đang chờ đón.",
			Content: `<h2>Tử vi tuổi Thân 2026</h2><p>Năm 2026 mang đến nhiều năng lượng tích cực cho tuổi Thân. Khả năng thích ứng và sáng tạo giúp bạn nắm bắt cơ hội trong mọi lĩnh vực.</p>`,
			CategorySlug: "tu-vi", MetaTitle: "Tử vi tuổi Thân 2026", MetaDescription: "Tử vi tuổi Thân 2026: năng động, nhiều cơ hội.", ReadingTime: 4, TagNames: []string{"Tử vi", "Con giáp", "Tử vi 2026"},
		},
		{
			Title: "Tử vi tuổi Dậu 2026: Thận trọng đầu năm, hanh thông cuối năm",
			Slug:  "tu-vi-tuoi-dau-2026",
			Excerpt: "Tuổi Dậu cần cẩn thận nửa đầu 2026 nhưng nửa cuối năm sẽ rất thuận lợi.",
			Content: `<h2>Tử vi tuổi Dậu 2026</h2><p>Tuổi Dậu trong năm 2026 có vận trình chia hai: nửa đầu cần thận trọng, nửa sau thu hoạch thành quả. Kiên nhẫn chờ đợi thời cơ là chiến lược đúng đắn.</p>`,
			CategorySlug: "tu-vi", MetaTitle: "Tử vi tuổi Dậu 2026", MetaDescription: "Tử vi tuổi Dậu 2026: cẩn thận đầu năm, thuận lợi cuối năm.", ReadingTime: 4, TagNames: []string{"Tử vi", "Con giáp", "Tử vi 2026"},
		},
		{
			Title: "Tử vi tuổi Tuất 2026: Tam Hợp cát khí, vạn sự như ý",
			Slug:  "tu-vi-tuoi-tuat-2026",
			Excerpt: "Tuổi Tuất năm 2026 được Tam Hợp với Dần và Ngọ hỗ trợ mạnh mẽ. Năm đại cát đại lợi.",
			Content: `<h2>Tử vi tuổi Tuất 2026</h2><p>Năm Bính Ngọ 2026, tuổi Tuất nằm trong bộ Tam Hợp Dần-Ngọ-Tuất, mang đến vận khí cực kỳ thuận lợi. Đây là năm để bạn dám nghĩ dám làm.</p><h3>Sự nghiệp</h3><p>Thăng tiến mạnh mẽ, được cấp trên tin tưởng giao trọng trách. Kinh doanh phát đạt.</p><h3>Tài chính</h3><p>Tiền tài dồi dào, đầu tư sinh lời. Nên tận dụng vận tốt để mở rộng.</p>`,
			CategorySlug: "tu-vi", MetaTitle: "Tử vi tuổi Tuất 2026 - Tam Hợp đại cát", MetaDescription: "Tử vi tuổi Tuất 2026: Tam Hợp mang đại cát, sự nghiệp và tài chính thuận lợi.", ReadingTime: 5, IsFeatured: true, TagNames: []string{"Tử vi", "Con giáp", "Tử vi 2026"},
		},
		{
			Title: "Tử vi tuổi Hợi 2026: Bình ổn và phát triển từ từ",
			Slug:  "tu-vi-tuoi-hoi-2026",
			Excerpt: "Tuổi Hợi năm 2026 có vận trình ổn định. Phát triển từ từ nhưng chắc chắn.",
			Content: `<h2>Tử vi tuổi Hợi 2026</h2><p>Năm 2026, tuổi Hợi có vận trình bình ổn và tích cực. Không có biến động lớn nhưng từng bước tiến đều mang lại kết quả tốt đẹp.</p>`,
			CategorySlug: "tu-vi", MetaTitle: "Tử vi tuổi Hợi 2026", MetaDescription: "Tử vi tuổi Hợi 2026: bình ổn, phát triển chắc chắn.", ReadingTime: 4, TagNames: []string{"Tử vi", "Con giáp", "Tử vi 2026"},
		},
	}

	return createSeedArticles(db, seeds, tagMap, authorID)
}
