package main

import (
	"fmt"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

func seedTuongSoArticles(db *gorm.DB, tagMap map[string]uuid.UUID, authorID *uuid.UUID) int {
	fmt.Println("\n   🧑 Seeding Tướng Số articles...")

	seeds := []ArticleSeed{
		{
			Title:           "Nhân tướng học là gì? Tổng quan về thuật xem tướng mặt",
			Slug:            "nhan-tuong-hoc-la-gi-tong-quan-xem-tuong-mat",
			Excerpt:         "Nhân tướng học (tướng số) là bộ môn phân tích tính cách và vận mệnh qua gương mặt. Nguồn gốc, nguyên lý và cách ứng dụng.",
			Content:         `<h2>Nhân tướng học là gì?</h2><p>Nhân tướng học (Physiognomy) là bộ môn cổ đại nghiên cứu mối quan hệ giữa ngoại hình và tính cách, vận mệnh con người. Đặc biệt, tướng mặt được xem là "tấm gương" phản chiếu bản chất bên trong.</p><h3>Nguồn gốc</h3><p>Nhân tướng học có lịch sử hàng nghìn năm, phát triển mạnh ở Trung Quốc (Ma Y tướng thuật), Hy Lạp (Aristotle) và Ấn Độ (Samudrika Shastra).</p><h3>Nguyên lý cơ bản</h3><ul><li><strong>Tam đình:</strong> Chia khuôn mặt thành 3 phần: thượng đình (trán), trung đình (mũi), hạ đình (miệng, cằm)</li><li><strong>Ngũ quan:</strong> Tai, mắt, mũi, miệng, lông mày</li><li><strong>Thập nhị cung:</strong> 12 vị trí trên khuôn mặt tương ứng 12 lĩnh vực cuộc sống</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Nhân tướng học là gì? Tổng quan xem tướng mặt",
			MetaDescription: "Nhân tướng học: bộ môn xem tướng mặt cổ đại. Nguồn gốc, nguyên lý tam đình, ngũ quan, thập nhị cung.",
			ReadingTime:     6,
			IsFeatured:      true,
			TagNames:        []string{"Tướng số", "Nhân tướng học", "Huyền học"},
		},
		{
			Title:       "Xem tướng trán: 7 kiểu trán và ý nghĩa vận mệnh",
			Slug:        "xem-tuong-tran-7-kieu-tran-van-menh",
			Excerpt:     "Trán (thượng đình) tiết lộ trí tuệ, sự nghiệp thời trẻ. 7 kiểu trán phổ biến và ý nghĩa trong nhân tướng học.",
			Content:     `<h2>Xem tướng trán</h2><p>Trong nhân tướng học, trán thuộc "thượng đình" – phản ánh vận mệnh từ 15-30 tuổi, trí tuệ và gia thế.</p><h3>7 kiểu trán</h3><ul><li><strong>Trán rộng, cao:</strong> Thông minh, sáng tạo, sự nghiệp sớm thành đạt</li><li><strong>Trán hẹp, thấp:</strong> Chịu khó, kiên trì nhưng tuổi trẻ vất vả</li><li><strong>Trán phẳng:</strong> Lý trí, logic, phù hợp công việc phân tích</li><li><strong>Trán gồ:</strong> Tham vọng lớn, quyết đoán nhưng hay nóng vội</li><li><strong>Trán tròn:</strong> Lạc quan, hòa đồng, may mắn về tài chính</li><li><strong>Trán vuông:</strong> Ý chí mạnh, lãnh đạo tốt</li><li><strong>Trán M (góc nhọn):</strong> Sáng tạo đặc biệt, tư duy độc lập</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Xem tướng trán - 7 kiểu trán và vận mệnh",
			MetaDescription: "Xem tướng trán: 7 kiểu trán phổ biến, ý nghĩa trí tuệ và sự nghiệp trong nhân tướng học.",
			ReadingTime:     5,
			TagNames:        []string{"Tướng số", "Nhân tướng học"},
		},
		{
			Title:       "Xem tướng mắt: Cửa sổ tâm hồn tiết lộ tính cách",
			Slug:        "xem-tuong-mat-cua-so-tam-hon",
			Excerpt:     "Mắt là bộ phận quan trọng nhất trong tướng mặt. Các kiểu mắt phổ biến và ý nghĩa tính cách, vận mệnh.",
			Content:     `<h2>Xem tướng mắt</h2><p>Mắt được coi là "cửa sổ tâm hồn" và là yếu tố quan trọng nhất trong nhân tướng học. Đôi mắt tiết lộ tính cách, trí tuệ và vận mệnh tình cảm.</p><h3>Các kiểu mắt</h3><ul><li><strong>Mắt phượng:</strong> Dài, đuôi mắt hếch lên – thanh cao, quý phái, sự nghiệp thuận lợi</li><li><strong>Mắt rồng:</strong> To, sáng, mí rõ – quyền uy, lãnh đạo</li><li><strong>Mắt tròn:</strong> Thẳng thắn, nhiệt tình, hay nóng vội</li><li><strong>Mắt tam giác:</strong> Sắc sảo, đa nghi, giỏi tính toán</li><li><strong>Mắt một mí:</strong> Kiên định, lý trí, không dễ bị chi phối</li><li><strong>Mắt hai mí:</strong> Giàu cảm xúc, hòa đồng, thu hút</li></ul><h3>Ánh mắt</h3><p>Ánh mắt sáng, có thần: người thông minh, may mắn. Ánh mắt đục, vô thần: vận khí suy giảm.</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Xem tướng mắt - Tính cách qua đôi mắt",
			MetaDescription: "Xem tướng mắt: các kiểu mắt phổ biến, ý nghĩa tính cách, vận mệnh trong nhân tướng học.",
			ReadingTime:     5,
			TagNames:        []string{"Tướng số", "Nhân tướng học"},
		},
		{
			Title:       "Xem tướng mũi: Tài lộc và sự nghiệp qua dáng mũi",
			Slug:        "xem-tuong-mui-tai-loc-su-nghiep",
			Excerpt:     "Mũi (Tài Bạch cung) phản ánh tài lộc, sự nghiệp ở tuổi trung niên. Các dáng mũi đẹp và xấu trong tướng số.",
			Content:     `<h2>Xem tướng mũi</h2><p>Mũi thuộc "Tài Bạch cung" trong nhân tướng học, phản ánh tài chính, sự nghiệp và bản lĩnh. Mũi tốt là điềm may mắn về tiền bạc.</p><h3>Các dáng mũi</h3><ul><li><strong>Mũi sư tử:</strong> Cao, thẳng, đầu tròn – đại phú đại quý</li><li><strong>Mũi treo mật:</strong> Tròn, đầy đặn – tài lộc dồi dào</li><li><strong>Mũi ưng:</strong> Khoằm xuống – quyền lực, mưu lược</li><li><strong>Mũi gãy:</strong> Sự nghiệp tuổi trung niên gặp trở ngại</li><li><strong>Mũi hếch:</strong> Tốt bụng nhưng khó giữ tiền</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Xem tướng mũi - Tài lộc qua dáng mũi",
			MetaDescription: "Xem tướng mũi: Tài Bạch cung, các dáng mũi và ý nghĩa tài lộc, sự nghiệp.",
			ReadingTime:     5,
			TagNames:        []string{"Tướng số", "Nhân tướng học"},
		},
		{
			Title:       "Xem tướng miệng và môi: Tướng ẩm thực và phúc đức",
			Slug:        "xem-tuong-mieng-moi-am-thuc-phuc-duc",
			Excerpt:     "Miệng (Xuất Nạp cung) tiết lộ phúc đức, tài ăn nói và hưởng thụ. Các kiểu miệng và ý nghĩa trong tướng số.",
			Content:     `<h2>Xem tướng miệng</h2><p>Miệng thuộc "hạ đình" và "Xuất Nạp cung", phản ánh phúc đức, khả năng ăn nói và hưởng thụ vật chất.</p><h3>Tướng miệng tốt</h3><ul><li>Miệng rộng, khóe hướng lên: phúc đức, giàu sang</li><li>Môi đỏ, răng đều trắng: may mắn, được lòng người</li><li>Miệng vuông, đầy đặn: uy quyền, lãnh đạo</li></ul><h3>Tướng miệng cần chú ý</h3><ul><li>Miệng hẹp, mỏng: tình duyên nhiều sóng gió</li><li>Khóe miệng chúc xuống: hay buồn, vận trung niên vất vả</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Xem tướng miệng - Phúc đức qua miệng",
			MetaDescription: "Xem tướng miệng: phúc đức, tài ăn nói. Các kiểu miệng tốt xấu trong nhân tướng học.",
			ReadingTime:     4,
			TagNames:        []string{"Tướng số", "Nhân tướng học"},
		},
		{
			Title:       "Xem tướng lông mày: Anh em cung và tính cách tiềm ẩn",
			Slug:        "xem-tuong-long-may-anh-em-cung",
			Excerpt:     "Lông mày (Anh Em cung) phản ánh mối quan hệ anh em, bạn bè. Các kiểu lông mày và ý nghĩa tướng số.",
			Content:     `<h2>Xem tướng lông mày</h2><p>Lông mày thuộc "Anh Em cung" trong nhân tướng học. Hình dáng lông mày tiết lộ tính cách, mối quan hệ và sự nghiệp.</p><h3>Các kiểu lông mày</h3><ul><li><strong>Mày kiếm:</strong> Thẳng, dày, đuôi nhọn – cương trực, dũng cảm, có quý nhân phù trợ</li><li><strong>Mày lá liễu:</strong> Cong nhẹ, mảnh – thanh nhã, nghệ sĩ, tình cảm phong phú</li><li><strong>Mày rậm:</strong> Dày, đen – ý chí mạnh, tình anh em sâu sắc</li><li><strong>Mày thưa:</strong> Nhạt, ít lông – tình bạn bè ít, cần tự lập</li><li><strong>Mày bát tự:</strong> Đuôi xụ xuống – nhân hậu nhưng dễ bị lợi dụng</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Xem tướng lông mày - Nhân tướng học",
			MetaDescription: "Xem tướng lông mày: Anh Em cung, các kiểu mày và ý nghĩa tính cách, mối quan hệ.",
			ReadingTime:     4,
			TagNames:        []string{"Tướng số", "Nhân tướng học"},
		},
		{
			Title:       "Xem tướng tai: Thọ nguyên cung và phúc phận từ thuở nhỏ",
			Slug:        "xem-tuong-tai-tho-nguyen-cung",
			Excerpt:     "Tai (Thọ Nguyên cung) phản ánh sức khỏe, trí tuệ và phúc phận thời thơ ấu. Các tướng tai tốt và xấu.",
			Content:     `<h2>Xem tướng tai</h2><p>Tai thuộc "Thọ Nguyên cung", phản ánh sức khỏe, tuổi thọ, trí tuệ và phúc phận từ nhỏ (1-14 tuổi).</p><h3>Tướng tai tốt</h3><ul><li><strong>Tai to, dày, dái tai lớn:</strong> Phúc đức, trường thọ, giàu có (như tai Phật)</li><li><strong>Tai cao hơn mày:</strong> Thông minh xuất chúng, sớm thành công</li><li><strong>Tai sát đầu:</strong> Bí mật, thận trọng, giỏi giữ tiền</li></ul><h3>Tướng tai cần chú ý</h3><ul><li>Tai nhỏ, mỏng: sức khỏe yếu, tuổi thơ vất vả</li><li>Tai vểnh ra: phóng khoáng nhưng hay chi tiêu quá đà</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Xem tướng tai - Phúc phận và sức khỏe",
			MetaDescription: "Xem tướng tai: Thọ Nguyên cung, tướng tai Phật, ý nghĩa sức khỏe và phúc phận.",
			ReadingTime:     4,
			TagNames:        []string{"Tướng số", "Nhân tướng học"},
		},
		{
			Title:       "Xem tướng bàn tay: Đường chỉ tay và vận mệnh cuộc đời",
			Slug:        "xem-tuong-ban-tay-duong-chi-tay",
			Excerpt:     "Thuật xem tay (Palmistry): các đường chỉ tay chính và phụ, hình dáng bàn tay. Hướng dẫn xem tướng tay cơ bản.",
			Content:     `<h2>Xem tướng bàn tay</h2><p>Thuật xem tay (Chiromancy/Palmistry) là bộ môn phân tích tính cách và vận mệnh thông qua hình dáng bàn tay và các đường chỉ tay.</p><h3>3 đường chỉ tay chính</h3><ul><li><strong>Đường sinh mệnh:</strong> Bao quanh gò Kim Tinh – phản ánh sức khỏe, tuổi thọ, năng lượng sống</li><li><strong>Đường trí tuệ:</strong> Từ giữa ngón trỏ và ngón cái kéo ngang – phản ánh trí thông minh, tư duy</li><li><strong>Đường tình cảm:</strong> Phía trên đường trí tuệ – phản ánh đời sống tình cảm, hôn nhân</li></ul><h3>Đường phụ</h3><ul><li>Đường sự nghiệp (vận mệnh)</li><li>Đường Mặt Trời (thành công, danh tiếng)</li><li>Đường hôn nhân</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Xem tướng bàn tay - Đường chỉ tay vận mệnh",
			MetaDescription: "Xem tướng bàn tay: đường sinh mệnh, trí tuệ, tình cảm. Hướng dẫn xem chỉ tay cơ bản.",
			ReadingTime:     6,
			IsFeatured:      true,
			TagNames:        []string{"Tướng số", "Nhân tướng học"},
		},
		{
			Title:       "Nốt ruồi trên mặt: Vị trí và ý nghĩa phong thủy tướng số",
			Slug:        "not-ruoi-tren-mat-vi-tri-y-nghia",
			Excerpt:     "Nốt ruồi ở các vị trí trên khuôn mặt mang ý nghĩa gì? Bản đồ nốt ruồi chi tiết và cách giải đoán trong tướng số.",
			Content:     `<h2>Nốt ruồi trên mặt</h2><p>Trong nhân tướng học, nốt ruồi trên khuôn mặt được xem là "dấu ấn vận mệnh". Mỗi vị trí mang ý nghĩa riêng về tính cách, tài lộc và tình duyên.</p><h3>Bản đồ nốt ruồi</h3><ul><li><strong>Giữa trán:</strong> Thông minh, sự nghiệp tốt, dễ được cấp trên tin tưởng</li><li><strong>Đuôi mắt:</strong> Đào hoa, tình duyên phức tạp</li><li><strong>Sống mũi:</strong> Sức khỏe cần chú ý, vất vả tuổi trung niên</li><li><strong>Cánh mũi:</strong> Tài lộc dễ đến nhưng cũng dễ đi</li><li><strong>Cằm:</strong> Tuổi già yên vui, con cháu hiếu thảo</li><li><strong>Gò má:</strong> Quyền lực, nhưng hay gặp thị phi</li></ul><h3>Lưu ý</h3><p>Nốt ruồi sống (đen, nổi, tròn) thường tốt hơn nốt ruồi chết (nhạt, phẳng, méo).</p>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Nốt ruồi trên mặt - Vị trí và ý nghĩa",
			MetaDescription: "Nốt ruồi trên mặt: bản đồ vị trí và ý nghĩa tướng số. Nốt ruồi ở đâu may mắn, ở đâu cần chú ý?",
			ReadingTime:     5,
			TagNames:        []string{"Tướng số", "Nhân tướng học"},
		},
		{
			Title:       "Tướng người phụ nữ vượng phu ích tử: 10 đặc điểm nhận biết",
			Slug:        "tuong-phu-nu-vuong-phu-ich-tu",
			Excerpt:     "10 đặc điểm tướng mạo phụ nữ vượng phu ích tử theo nhân tướng học. Người phụ nữ mang lại phúc lộc cho chồng con.",
			Content:     `<h2>Tướng phụ nữ vượng phu ích tử</h2><p>"Vượng phu ích tử" là cách nói trong tướng số, chỉ người phụ nữ mang lại may mắn, phúc lộc cho chồng và con cái.</p><h3>10 đặc điểm</h3><ol><li><strong>Trán rộng, sáng:</strong> Thông minh, biết lo liệu</li><li><strong>Mắt sáng, hiền từ:</strong> Tâm hồn trong sáng, trung thành</li><li><strong>Mũi thẳng, cánh mũi đầy:</strong> Giỏi quản lý tài chính gia đình</li><li><strong>Miệng nhỏ, môi đầy:</strong> Khéo léo, ăn nói duyên dáng</li><li><strong>Cằm tròn, đầy đặn:</strong> Hậu vận tốt, con cháu đầy đàn</li><li><strong>Tai dày, dái tai lớn:</strong> Phúc đức, sống lâu</li><li><strong>Da mịn, hồng hào:</strong> Sức khỏe tốt, sinh lực dồi dào</li><li><strong>Lưng thẳng, vai đều:</strong> Bản lĩnh, gánh vác gia đình</li><li><strong>Bàn tay ấm, ngón dài:</strong> Khéo léo, tinh tế</li><li><strong>Giọng nói nhẹ nhàng:</strong> Thu hút, tạo sự an tâm</li></ol>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tướng phụ nữ vượng phu ích tử - 10 đặc điểm",
			MetaDescription: "10 đặc điểm tướng phụ nữ vượng phu ích tử: mắt sáng, mũi thẳng, cằm tròn. Nhân tướng học.",
			ReadingTime:     5,
			IsFeatured:      true,
			TagNames:        []string{"Tướng số", "Nhân tướng học"},
		},
		{
			Title:       "Tướng người đàn ông thành đạt: Ngũ nhạc triều quy",
			Slug:        "tuong-dan-ong-thanh-dat-ngu-nhac-trieu-quy",
			Excerpt:     "Nhận diện tướng đàn ông thành đạt theo nhân tướng học: Ngũ nhạc triều quy, tam đình cân đối và các đặc điểm quý.",
			Content:     `<h2>Tướng đàn ông thành đạt</h2><p>Theo nhân tướng học, tướng đàn ông thành đạt thể hiện qua sự cân đối, khí chất mạnh mẽ và các đặc điểm quý phái.</p><h3>Ngũ nhạc triều quy</h3><p>Ngũ nhạc là 5 "núi" trên khuôn mặt: trán (Nam Nhạc), cằm (Bắc Nhạc), mũi (Trung Nhạc), gò má trái (Đông Nhạc), gò má phải (Tây Nhạc). Khi 5 vị trí này nổi bật, hài hòa – gọi là "triều quy" – đại phú đại quý.</p><h3>Đặc điểm khác</h3><ul><li>Tam đình (trán, mũi, cằm) cân đối: sự nghiệp hanh thông suốt đời</li><li>Mắt sáng, có thần: trí tuệ, quyền uy</li><li>Mũi cao, thẳng: tài lộc dồi dào</li><li>Giọng nói trầm, vang: uy quyền, được kính trọng</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tướng đàn ông thành đạt - Ngũ nhạc triều quy",
			MetaDescription: "Tướng đàn ông thành đạt: Ngũ nhạc triều quy, tam đình cân đối. Nhân tướng học nhận diện quý tướng.",
			ReadingTime:     5,
			TagNames:        []string{"Tướng số", "Nhân tướng học"},
		},
		{
			Title:       "Thập nhị cung trên khuôn mặt: 12 vị trí tiết lộ vận mệnh",
			Slug:        "thap-nhi-cung-khuon-mat-12-vi-tri",
			Excerpt:     "Thập nhị cung là 12 vị trí trên khuôn mặt tương ứng 12 lĩnh vực cuộc sống. Hướng dẫn xem chi tiết từng cung.",
			Content:     `<h2>Thập nhị cung</h2><p>Thập nhị cung là hệ thống 12 vị trí trên khuôn mặt, mỗi vị trí phản ánh một khía cạnh của cuộc sống.</p><h3>12 cung</h3><ol><li><strong>Mệnh cung:</strong> Giữa hai lông mày – vận mệnh tổng quát</li><li><strong>Tài Bạch cung:</strong> Mũi – tài chính, tiền bạc</li><li><strong>Huynh Đệ cung:</strong> Lông mày – anh em, bạn bè</li><li><strong>Điền Trạch cung:</strong> Mắt – nhà cửa, bất động sản</li><li><strong>Nam Nữ cung:</strong> Dưới mắt – con cái</li><li><strong>Nô Bộc cung:</strong> Hàm dưới – cấp dưới, người giúp việc</li><li><strong>Thê Thiếp cung:</strong> Đuôi mắt – vợ/chồng, hôn nhân</li><li><strong>Tật Ách cung:</strong> Sống mũi – bệnh tật, tai nạn</li><li><strong>Thiên Di cung:</strong> Hai bên trán – xuất ngoại, di chuyển</li><li><strong>Quan Lộc cung:</strong> Giữa trán – sự nghiệp, công danh</li><li><strong>Phúc Đức cung:</strong> Trán trên – phúc đức, gia thế</li><li><strong>Phụ Mẫu cung:</strong> Hai bên Nhật Nguyệt – cha mẹ</li></ol>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Thập nhị cung khuôn mặt - 12 vị trí vận mệnh",
			MetaDescription: "Thập nhị cung: 12 vị trí trên khuôn mặt tiết lộ vận mệnh. Hướng dẫn xem chi tiết từng cung.",
			ReadingTime:     6,
			TagNames:        []string{"Tướng số", "Nhân tướng học"},
		},
		{
			Title:       "Tướng đi và dáng người: Phân tích tính cách qua cử chỉ",
			Slug:        "tuong-di-dang-nguoi-phan-tich-tinh-cach",
			Excerpt:     "Dáng đi, cách ngồi, tư thế đứng tiết lộ tính cách và vận mệnh. Nhân tướng học phân tích dáng người.",
			Content:     `<h2>Tướng đi và dáng người</h2><p>Ngoài khuôn mặt, nhân tướng học còn xem xét dáng đi, tư thế và cử chỉ để đánh giá con người.</p><h3>Dáng đi</h3><ul><li><strong>Đi nhanh, dứt khoát:</strong> Tính cách quyết đoán, năng động</li><li><strong>Đi chậm, vững vàng:</strong> Thận trọng, suy tính kỹ lưỡng</li><li><strong>Đi lắc lư:</strong> Bất ổn, thiếu quyết đoán</li><li><strong>Đi thẳng lưng:</strong> Tự tin, bản lĩnh, có uy</li></ul><h3>Dáng ngồi</h3><ul><li>Ngồi thẳng, không cử động nhiều: ý chí mạnh, tập trung</li><li>Hay rung chân: bồn chồn, thiếu kiên nhẫn, tiền bạc khó giữ</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tướng đi dáng người - Phân tích tính cách",
			MetaDescription: "Tướng đi, dáng ngồi tiết lộ tính cách: dứt khoát, thận trọng hay bất ổn? Nhân tướng học cử chỉ.",
			ReadingTime:     4,
			TagNames:        []string{"Tướng số", "Nhân tướng học"},
		},
		{
			Title:       "Tướng ngũ hành: Kim, Mộc, Thủy, Hỏa, Thổ trong nhân tướng",
			Slug:        "tuong-ngu-hanh-kim-moc-thuy-hoa-tho",
			Excerpt:     "Phân loại 5 tướng người theo Ngũ Hành: Kim hình, Mộc hình, Thủy hình, Hỏa hình, Thổ hình. Đặc điểm và vận mệnh.",
			Content:     `<h2>Tướng Ngũ Hành</h2><p>Nhân tướng học phân loại con người thành 5 dạng tướng theo Ngũ Hành. Mỗi dạng có đặc điểm ngoại hình, tính cách và vận mệnh khác nhau.</p><h3>5 dạng tướng</h3><ul><li><strong>Kim hình:</strong> Da trắng, xương rõ, giọng trong – cương trực, công bằng, hợp nghề quản lý</li><li><strong>Mộc hình:</strong> Cao, gầy, thẳng – thẳng thắn, nhân từ, hợp nghề giáo dục</li><li><strong>Thủy hình:</strong> Tròn, mập, da đen – thông minh, linh hoạt, hợp nghề kinh doanh</li><li><strong>Hỏa hình:</strong> Đỏ, gầy, nhọn – nóng nảy, quyết đoán, hợp nghề quân sự</li><li><strong>Thổ hình:</strong> Đầy đặn, vàng – trung hậu, kiên trì, hợp nghề bất động sản</li></ul>`,
			CategorySlug:    "tu-vi",
			MetaTitle:       "Tướng Ngũ Hành - Kim Mộc Thủy Hỏa Thổ",
			MetaDescription: "Tướng Ngũ Hành: 5 dạng Kim, Mộc, Thủy, Hỏa, Thổ. Đặc điểm ngoại hình và vận mệnh.",
			ReadingTime:     5,
			TagNames:        []string{"Tướng số", "Nhân tướng học", "Ngũ hành"},
		},
	}

	return createSeedArticles(db, seeds, tagMap, authorID)
}
